/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:36 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UILabel, NSDate, UIFont;

@interface DayTwoPartLabel : UIView {

	UILabel* _firstLabel;
	UILabel* _secondLabel;
	UILabel* _entireString;
	UILabel* _overlayLabel;
	NSDate* _date;
	char _useSeparateFormat;
	char _dayNameOnLeft;
	char _showOverlayDate;

}

@property (nonatomic,retain) UIFont * font; 
@property (assign,nonatomic) char showOverlayDate;                             //@synthesize showOverlayDate=_showOverlayDate - In the implementation block
@property (nonatomic,retain) NSDate * date;                                    //@synthesize date=_date - In the implementation block
@property (nonatomic,readonly) float baselineOffsetFromBoundsTop; 
-(id)createCopy;
-(float)baselineOffsetFromBoundsTop;
-(void)setShowOverlayDate:(char)arg1 ;
-(void)_resetUI;
-(void)_updateOverlayLabel;
-(void)setDayOfWeekString:(id)arg1 ;
-(void)setDateYearString:(id)arg1 ;
-(void)_copyLabelParametersFrom:(id)arg1 to:(id)arg2 ;
-(id)dayOfWeekString;
-(id)dateYearString;
-(char)showOverlayDate;
-(void)localeChanged;
-(void)_createSubviews;
-(void)setBackgroundColor:(id)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(NSDate *)date;
-(void)setFont:(UIFont *)arg1 ;
-(void)sizeToFit;
-(UIFont *)font;
-(void)setDate:(NSDate *)arg1 ;
@end

