/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:34 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MainViewControllerOptionalMethods <NSObject,FutureTraitEnvironment>
@property (assign,nonatomic) char isWaitingForBackgroundLoadingOfSelectedEventOccurrenceView; 
@property (nonatomic,readonly) char shouldAdaptEventViewControllers; 
@optional
-(void)updateBackButtonToDate:(id)arg1;
-(void)showNowAnimated:(char)arg1;
-(char)shouldPushNextLevelViewControllerWhenTodayIsVisible;
-(void)enableGestureRecognizers;
-(void)disableGestureRecognizers;
-(float)leftBarButtonBlankFixedSpaceWidth;
-(void)updatePalette:(id)arg1;
-(id)bestDateForNewEvent;
-(char)showEventDetailsWhenNewEventAdded;
-(id)toolBarTintColor;
-(int)supportedToggleMode;
-(id)navigationBarDisplayedDateString;
-(void)updateNavigationBarDisplayedDateString;
-(void)invalidateBackButtonDate;
-(char)shouldUpdateOwnBackButtonWhenTopViewController;
-(id)updateBackButtonWhileTopViewControllerToDate:(id)arg1;
-(char)shouldRespondToApplicationDidBecomeActiveStateChange;
-(void)setShouldRespondToApplicationDidBecomeActiveStateChange:(char)arg1;
-(char)isTodayVisible;
-(char)isWaitingForBackgroundLoadingOfSelectedEventOccurrenceView;
-(void)setIsWaitingForBackgroundLoadingOfSelectedEventOccurrenceView:(char)arg1;
-(char)shouldAdaptEventViewControllers;
-(id)navigationBarTintColor;

@end

