/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:17 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <iBooks/iBooks-Structs.h>
@class UIColor, UIFont;

@interface AEAnnotationTheme : NSObject {

	int _pageTheme;

}

@property (assign,nonatomic) int pageTheme;                                         //@synthesize pageTheme=_pageTheme - In the implementation block
@property (nonatomic,readonly) int annotationStyle; 
@property (nonatomic,readonly) char isUnderline; 
@property (nonatomic,readonly) UIColor * highlightColor; 
@property (nonatomic,readonly) UIColor * noteFillColor; 
@property (nonatomic,readonly) UIColor * noteBorderColor; 
@property (nonatomic,readonly) float noteShadowRadius; 
@property (nonatomic,readonly) float noteShadowOpacity; 
@property (nonatomic,readonly) UIColor * noteShadowColor; 
@property (nonatomic,readonly) CGSize noteShadowOffset; 
@property (nonatomic,readonly) UIColor * notesSidebarBarColor; 
@property (nonatomic,readonly) UIColor * notesSidebarTextColor; 
@property (nonatomic,readonly) UIFont * noteTextFont; 
@property (nonatomic,readonly) UIFont * noteTextFontInTable; 
@property (nonatomic,readonly) UIColor * noteTextColor; 
@property (nonatomic,readonly) UIColor * noteMarkerFillColor; 
@property (nonatomic,readonly) UIColor * noteMarkerBorderColor; 
@property (nonatomic,readonly) UIColor * noteMarkerStrikethroughColor; 
+(id)themeForAnnotationStyle:(int)arg1 pageTheme:(int)arg2 isUnderline:(char)arg3 ;
+(id)blueTheme:(int)arg1 ;
+(id)greenTheme:(int)arg1 ;
+(id)yellowTheme:(int)arg1 ;
+(id)pinkTheme:(int)arg1 ;
+(id)purpleTheme:(int)arg1 ;
+(id)underlineTheme:(int)arg1 ;
+(id)themeDescriptions;
+(id)themeItemForAnnotationStyle:(int)arg1 propertyName:(id)arg2 ;
+(id)colorForThemeItem:(id)arg1 pageTheme:(int)arg2 ;
+(id)colorForAnnotationStyle:(int)arg1 propertyName:(id)arg2 pageTheme:(int)arg3 ;
+(id)themeForAnnotationStyle:(int)arg1 pageTheme:(int)arg2 ;
+(id)theme:(int)arg1 ;
+(id)highlightTextColor:(int)arg1 ;
-(int)annotationStyle;
-(UIColor *)notesSidebarBarColor;
-(int)pageTheme;
-(UIColor *)noteFillColor;
-(void)setPageTheme:(int)arg1 ;
-(UIColor *)noteTextColor;
-(char)isUnderline;
-(UIColor *)noteMarkerFillColor;
-(UIColor *)noteMarkerBorderColor;
-(UIColor *)noteMarkerStrikethroughColor;
-(UIColor *)noteBorderColor;
-(UIColor *)notesSidebarTextColor;
-(float)noteShadowRadius;
-(float)noteShadowOpacity;
-(UIColor *)noteShadowColor;
-(CGSize)noteShadowOffset;
-(UIFont *)noteTextFont;
-(UIFont *)noteTextFontInTable;
-(UIColor *)highlightColor;
@end

