/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:16 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/IMActivityItemSourceExpanding.h>

@protocol AEAnnotationPaginationDataSource;
@class NSNumber, NSArray, NSString;

@interface AEAssetActivityItemProvider : NSObject <IMActivityItemSourceExpanding> {

	NSNumber* _contentProtected;
	char _citationsAllowed;
	NSArray* _annotations;
	int _shareType;
	/*^block*/id _propertySource;
	id<AEAnnotationPaginationDataSource> _paginationDataSource;
	NSString* _activityType;

}

@property (nonatomic,retain) NSArray * annotations;                                                         //@synthesize annotations=_annotations - In the implementation block
@property (assign,nonatomic) int shareType;                                                                 //@synthesize shareType=_shareType - In the implementation block
@property (nonatomic,copy) id propertySource;                                                               //@synthesize propertySource=_propertySource - In the implementation block
@property (assign,nonatomic,__weak) id<AEAnnotationPaginationDataSource> paginationDataSource;              //@synthesize paginationDataSource=_paginationDataSource - In the implementation block
@property (assign,getter=areCitationsAllowed,nonatomic) char citationsAllowed;                              //@synthesize citationsAllowed=_citationsAllowed - In the implementation block
@property (nonatomic,retain) NSString * activityType;                                                       //@synthesize activityType=_activityType - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithPropertySource:(/*^block*/id)arg1 ;
-(void)setCitationsAllowed:(char)arg1 ;
-(id)expandedItemProviders;
-(id)initWithAnnotations:(id)arg1 propertySource:(/*^block*/id)arg2 ;
-(id<AEAnnotationPaginationDataSource>)paginationDataSource;
-(void)setPaginationDataSource:(id<AEAnnotationPaginationDataSource>)arg1 ;
-(char)areCitationsAllowed;
-(int)shareType;
-(id)propertySource;
-(id)initWithAnnotation:(id)arg1 propertySource:(/*^block*/id)arg2 ;
-(id)pasteboardString;
-(void)setShareType:(int)arg1 ;
-(void)setPropertySource:(id)arg1 ;
-(void)setActivityType:(NSString *)arg1 ;
-(NSArray *)annotations;
-(void)dealloc;
-(NSString *)activityType;
-(void)setAnnotations:(NSArray *)arg1 ;
@end

