/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:20 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <iBooks/IMMediaChapter.h>

@class NSString, UIImage, NSURL, NSDate, NSNumber, MPMediaItem, MPMediaChapter;

@interface AEAudiobookChapterSegment : NSObject <IMMediaChapter> {

	MPMediaItem* _mediaItem;
	MPMediaChapter* _mediaChapter;
	NSString* _title;
	NSURL* _url;
	SCD_Struct_AE41 _mediaTimeRange;
	SCD_Struct_AE41 _assetTimeRange;
	NSString* _customTitle;
	char _hasAlternateArtwork;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSString * customTitle; 
@property (nonatomic,readonly) NSString * bookTitle; 
@property (nonatomic,readonly) UIImage * artwork; 
@property (nonatomic,readonly) SCD_Struct_AE41 mediaTimeRange; 
@property (nonatomic,readonly) SCD_Struct_AE41 assetTimeRange; 
@property (nonatomic,readonly) NSURL * assetURL; 
@property (nonatomic,readonly) NSURL * externalURL; 
@property (nonatomic,readonly) int type; 
@property (nonatomic,readonly) int metadataType; 
@property (nonatomic,readonly) char hasAlternateArtwork; 
@property (nonatomic,retain) NSDate * dateLastOpened; 
@property (nonatomic,readonly) NSNumber * persistentID; 
+(id)customChapterSegmentTitleWithIndex:(unsigned)arg1 mediaItem:(id)arg2 mediaChapter:(id)arg3 ;
-(void)setDateLastOpened:(NSDate *)arg1 ;
-(NSDate *)dateLastOpened;
-(NSString *)bookTitle;
-(SCD_Struct_AE41)assetTimeRange;
-(SCD_Struct_AE41)mediaTimeRange;
-(void)incrementPlayCount;
-(char)hasAlternateArtwork;
-(id)artworkCatalogForTime:(double)arg1 ;
-(id)initWithMediaItem:(id)arg1 andMediaChapter:(id)arg2 ;
-(void)setCustomTitle:(NSString *)arg1 ;
-(void)setChapterStartTime:(double)arg1 ;
-(id)_mediaItemURL:(id)arg1 ;
-(int)metadataType;
-(NSURL *)externalURL;
-(id)initWithMediaItem:(id)arg1 ;
-(NSURL *)assetURL;
-(NSNumber *)persistentID;
-(void)dealloc;
-(NSString *)description;
-(int)type;
-(NSString *)title;
-(NSString *)customTitle;
-(char)hasUrl;
-(UIImage *)artwork;
@end

