/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:15 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <iBooks/iBooks-Structs.h>
@class NSMapTable;

@interface AEHighlightRenderingController : NSObject {

	char _canUseFilters;
	char _addingHighlights;
	int _annotationBlendMode;
	int _pageTheme;
	NSMapTable* _dataHighlights;
	NSMapTable* _containerLayers;

}

@property (assign,nonatomic) char canUseFilters;                                           //@synthesize canUseFilters=_canUseFilters - In the implementation block
@property (assign,nonatomic) int annotationBlendMode;                                      //@synthesize annotationBlendMode=_annotationBlendMode - In the implementation block
@property (assign,nonatomic) int pageTheme;                                                //@synthesize pageTheme=_pageTheme - In the implementation block
@property (assign,getter=isAddingHighlights,nonatomic) char addingHighlights;              //@synthesize addingHighlights=_addingHighlights - In the implementation block
@property (nonatomic,retain) NSMapTable * dataHighlights;                                  //@synthesize dataHighlights=_dataHighlights - In the implementation block
@property (nonatomic,retain) NSMapTable * containerLayers;                                 //@synthesize containerLayers=_containerLayers - In the implementation block
+(UIEdgeInsets)highlightInsets:(char)arg1 ;
+(UIEdgeInsets)insetsForHighlight:(id)arg1 ;
+(CGRect)p_currentLineRectForLine:(id)arg1 ofHighlight:(id)arg2 ;
+(UIEdgeInsets)insetsForHighlight:(id)arg1 lineRect:(CGRect)arg2 numberOfLines:(unsigned)arg3 ;
+(CGRect)p_fullLineRectForLine:(id)arg1 ofHighlight:(id)arg2 ;
-(void)setAnnotationBlendMode:(int)arg1 ;
-(int)annotationBlendMode;
-(int)pageTheme;
-(void)setPageTheme:(int)arg1 ;
-(void)setDataHighlights:(NSMapTable *)arg1 ;
-(void)setContainerLayers:(NSMapTable *)arg1 ;
-(NSMapTable *)dataHighlights;
-(id)p_lineRectsForHighlight:(id)arg1 ;
-(char)canUseFilters;
-(NSMapTable *)containerLayers;
-(void)p_renderLinesForHighlight:(id)arg1 intoContainerLayer:(id)arg2 ;
-(void)updatedHighlight:(id)arg1 forceRerender:(char)arg2 ;
-(id)p_orderHighlights:(id)arg1 ;
-(id)p_highlightForContainerLayer:(id)arg1 ;
-(id)highlightWithData:(id)arg1 ;
-(void)addHighlight:(id)arg1 forData:(id)arg2 ;
-(void)removeHighlightForData:(id)arg1 ;
-(void)updatedHighlight:(id)arg1 ;
-(id)highlightLayers;
-(id)annotationUuidForHighlightLayer:(id)arg1 ;
-(char)layer:(id)arg1 containsHighlightAtPoint:(CGPoint)arg2 ;
-(void)setCanUseFilters:(char)arg1 ;
-(char)isAddingHighlights;
-(void)setAddingHighlights:(char)arg1 ;
-(id)init;
@end

