/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:16 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol AEUserPublishingDataSource <NSObject>
@optional
-(char)userPublishing:(id)arg1 isLocalGenerationEnabledForStoreId:(id)arg2;
-(id)userPublishing:(id)arg1 assetAuthorForStoreId:(id)arg2;
-(id)userPublishing:(id)arg1 assetTitleForStoreId:(id)arg2;
-(id)userPublishing:(id)arg1 assetCategoryForStoreId:(id)arg2;
-(id)userPublishing:(id)arg1 assetCoverImageForStoreId:(id)arg2;
-(id)userPublishing:(id)arg1 storeURLForStoreId:(id)arg2;
-(id)userPublishing:(id)arg1 storeShortURLForStoreId:(id)arg2;
-(char)userPublishing:(id)arg1 isDownloadEnabledForStoreId:(id)arg2;
-(id)userPublishing:(id)arg1 tellAFriendEmailBaseURLForStoreId:(id)arg2;

@end

