/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:13 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSURL, NSDictionary, NSObject;

@interface BKAssetLookup : NSObject {

	NSURL* _url;
	NSDictionary* _options;
	/*^block*/id _completion;
	NSObject*<OS_dispatch_queue> _sync;

}

@property (nonatomic,copy) NSURL * url;                                      //@synthesize url=_url - In the implementation block
@property (nonatomic,copy) NSDictionary * options;                           //@synthesize options=_options - In the implementation block
@property (nonatomic,copy) id completion;                                    //@synthesize completion=_completion - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> sync;              //@synthesize sync=_sync - In the implementation block
+(id)assetLookupWithURL:(id)arg1 options:(id)arg2 completion:(/*^block*/id)arg3 ;
+(id)validateAssetAuthorization:(id)arg1 ;
-(id)initWithURL:(id)arg1 options:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setSync:(NSObject*<OS_dispatch_queue>)arg1 ;
-(char)_isProperlyInstalledAssetURL:(id)arg1 ;
-(void)_completeWithAssetViewController:(id)arg1 helper:(id)arg2 error:(id)arg3 ;
-(void)cancel;
-(NSURL *)url;
-(id)completion;
-(void)setCompletion:(id)arg1 ;
-(void)setUrl:(NSURL *)arg1 ;
-(void)setOptions:(NSDictionary *)arg1 ;
-(NSDictionary *)options;
-(void)_load;
-(NSObject*<OS_dispatch_queue>)sync;
@end

