/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:12 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/IMAssertion.h>

@class IMMutableFuture, NSString;

@interface BKAssetPresentingViewControllerHoldAnimationAssertion : NSObject <IMAssertion> {

	IMMutableFuture* _future;

}

@property (nonatomic,retain) IMMutableFuture * future;              //@synthesize future=_future - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setFuture:(IMMutableFuture *)arg1 ;
-(IMMutableFuture *)future;
-(void)dealloc;
-(id)init;
-(void)invalidate;
@end

