/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:13 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/__BKBookViewControllerAccessibility_super.h>

@interface BKBookViewControllerAccessibility : __BKBookViewControllerAccessibility_super
+(id)imaxTargetClassName;
+(Class)imaxBaseSafeCategoryClass;
-(void)showTOC:(id)arg1 ;
-(void)scrub:(id)arg1 ;
-(void)_axSendLayoutChange;
-(void)setControlsVisible:(char)arg1 ;
-(void)tocViewController:(id)arg1 didSelectChapter:(id)arg2 ;
-(void)directoryContent:(id)arg1 didSelectLocation:(id)arg2 ;
-(void)goToPath:(id)arg1 fragment:(id)arg2 animated:(char)arg3 ;
-(void)setControlsVisible:(char)arg1 animated:(char)arg2 animations:(/*^block*/id)arg3 completion:(/*^block*/id)arg4 ;
-(void)_bkaxHandleAssistiveTechStatusChanged:(id)arg1 ;
-(void)_accessibilityLoadAccessibilityInformation;
-(void)dealloc;
-(void)viewDidLoad;
-(void)resume:(id)arg1 ;
@end

