/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:21 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSArray;

@interface BKFont : NSObject {

	NSString* _familyName;
	NSString* _displayName;
	NSString* _localizedName;
	NSString* _postscriptName;
	NSString* _postscriptBoldName;
	NSString* _fileNamePrefix;
	NSString* _fileExtension;
	NSArray* _registeredFiles;
	int _state;
	char _continueDownloading;
	float _downloadProgress;

}

@property (nonatomic,retain) NSString * familyName;                      //@synthesize familyName=_familyName - In the implementation block
@property (nonatomic,retain) NSString * displayName;                     //@synthesize displayName=_displayName - In the implementation block
@property (nonatomic,retain) NSString * postscriptName;                  //@synthesize postscriptName=_postscriptName - In the implementation block
@property (nonatomic,retain) NSString * postscriptBoldName;              //@synthesize postscriptBoldName=_postscriptBoldName - In the implementation block
@property (nonatomic,retain) NSString * fileNamePrefix;                  //@synthesize fileNamePrefix=_fileNamePrefix - In the implementation block
@property (nonatomic,retain) NSString * fileExtension;                   //@synthesize fileExtension=_fileExtension - In the implementation block
@property (assign) int state;                                            //@synthesize state=_state - In the implementation block
@property (nonatomic,readonly) char isInstalled; 
@property (assign,nonatomic) float downloadProgress;                     //@synthesize downloadProgress=_downloadProgress - In the implementation block
@property (assign,nonatomic) char continueDownloading;                   //@synthesize continueDownloading=_continueDownloading - In the implementation block
+(id)_fontDescriptorLookupQueue;
+(void)_lookupLocalizedNameForAttrs:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)checkStateSynchronously:(char)arg1 ;
-(void)setPostscriptBoldName:(NSString *)arg1 ;
-(void)checkStateSynchronously:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)unregisterFiles;
-(NSString *)fileNamePrefix;
-(void)setContinueDownloading:(char)arg1 ;
-(char)continueDownloading;
-(NSString *)postscriptBoldName;
-(void)registerFiles;
-(void)setFileNamePrefix:(NSString *)arg1 ;
-(void)setFamilyName:(NSString *)arg1 ;
-(char)isInstalled;
-(void)download;
-(void)dealloc;
-(int)state;
-(void)setState:(int)arg1 ;
-(id)localizedName;
-(NSString *)familyName;
-(NSString *)displayName;
-(void)setPostscriptName:(NSString *)arg1 ;
-(void)setDisplayName:(NSString *)arg1 ;
-(void)cancelDownload;
-(NSString *)fileExtension;
-(void)setFileExtension:(NSString *)arg1 ;
-(float)downloadProgress;
-(void)setDownloadProgress:(float)arg1 ;
-(NSString *)postscriptName;
@end

