/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:17 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BKThumbnailBookViewConfiguring;
#import <iBooks/iBooks-Structs.h>
@interface BKPictureBookViewGeometry : NSObject {

	CGSize _contentSize;
	char _drawsSpine;
	id<BKThumbnailBookViewConfiguring> _configuration;

}

@property (readonly) CGSize contentSize;                                                    //@synthesize contentSize=_contentSize - In the implementation block
@property (readonly) char drawsSpine;                                                       //@synthesize drawsSpine=_drawsSpine - In the implementation block
@property (nonatomic,retain) id<BKThumbnailBookViewConfiguring> configuration;              //@synthesize configuration=_configuration - In the implementation block
+(id)geometryWithContentSize:(CGSize)arg1 configuration:(id)arg2 drawsSpine:(char)arg3 ;
+(CGSize)imageSizeForSize:(CGSize)arg1 ;
-(char)drawsSpine;
-(CGSize)sizeForSpread:(char)arg1 landscape:(char)arg2 ;
-(float)scaleForSpread:(char)arg1 landscape:(char)arg2 ;
-(id)initWithContentSize:(CGSize)arg1 configuration:(id)arg2 drawsSpine:(char)arg3 ;
-(CGSize)imageSizeForSpread:(char)arg1 landscape:(char)arg2 ;
-(float)scaleForSize:(CGSize)arg1 ;
-(id)imageSizes;
-(void)dealloc;
-(CGSize)contentSize;
-(void)setConfiguration:(id<BKThumbnailBookViewConfiguring>)arg1 ;
-(id<BKThumbnailBookViewConfiguring>)configuration;
-(id)sizes;
-(CGSize)maximumSize;
@end

