/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:14 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface BKSeriesCoverSourceObserver : NSObject {

	/*^block*/id _handler;
	NSObject*<OS_dispatch_queue> _queue;

}
-(void)invokeAsync:(id)arg1 ;
-(void)invokeSync:(id)arg1 ;
-(id)initWithHandler:(/*^block*/id)arg1 queue:(id)arg2 ;
@end

