/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:13 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/__BKSpreadThumbnailDirectoryCellAccessibility_super.h>

@interface BKSpreadThumbnailDirectoryCellAccessibility : __BKSpreadThumbnailDirectoryCellAccessibility_super
+(id)imaxTargetClassName;
+(Class)imaxBaseSafeCategoryClass;
-(id)accessibilityLabel;
@end

