/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:17 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <iBooks/iBooks-Structs.h>
@class NSMutableDictionary, NSObject;

@interface IMDatabaseHandle : NSObject {

	sqlite3Ref _databaseHandle;
	NSMutableDictionary* _statementCache;
	NSObject*<OS_dispatch_queue> _accessQueue;

}
+(id)questionMarkListForCollection:(id)arg1 ;
-(id)tableNames;
-(char)runStatement:(id)arg1 arguments:(id)arg2 ;
-(id)arrayForQuery:(id)arg1 arguments:(id)arg2 rawRows:(char)arg3 ;
-(id)stringColumnDataForQuery:(id)arg1 withArguments:(id)arg2 ;
-(id)_stringRowsForQuery:(id)arg1 ;
-(sqlite3Ref)_databaseHandle;
-(char)_bindArguments:(id)arg1 inStatement:(sqlite3_stmtRef)arg2 ;
-(void)_reportErrorInFunction:(const char*)arg1 ;
-(id)_cursorForQuery:(id)arg1 withArguments:(id)arg2 ;
-(id)columnInfoForTable:(id)arg1 ;
-(char)runSql:(id)arg1 withArguments:(id)arg2 ;
-(id)arrayForQuery:(id)arg1 arguments:(id)arg2 ;
-(void)dealloc;
-(id)initWithPath:(id)arg1 ;
-(id)version;
-(char)passesIntegrityCheck;
@end

