/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:15 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IMLibraryBooksDataSourceDelegateNSObject;
#import <iBooks/iBooks-Structs.h>
@interface IMLibraryBooksDataSource : NSObject {

	struct {
		unsigned hasWillChangeContent : 1;
		unsigned hasDidChangeSection : 1;
		unsigned hasDidChangeObject : 1;
		unsigned hasDidChangeContent : 1;
	}  _delegateFlags;
	id<IMLibraryBooksDataSourceDelegate><NSObject> _delegate;

}

@property (assign,nonatomic,__weak) id<IMLibraryBooksDataSourceDelegate><NSObject> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)currentSectionNameKeyPath;
-(id)objectsInSection:(int)arg1 ;
-(unsigned)numberOfObjectsInSection:(int)arg1 ;
-(id)checkedObjectAtIndexPath:(id)arg1 ;
-(id)nameForSection:(int)arg1 ;
-(id)objectAtIndexPath:(id)arg1 ;
-(id)indexPathForObject:(id)arg1 ;
-(int)sectionForSectionIndexTitle:(id)arg1 atIndex:(int)arg2 ;
-(void)setDelegate:(id<IMLibraryBooksDataSourceDelegate><NSObject>)arg1 ;
-(void)dealloc;
-(void)reloadData;
-(id<IMLibraryBooksDataSourceDelegate><NSObject>)delegate;
-(id)allObjects;
-(id)sectionIndexTitles;
-(unsigned)sectionsCount;
@end

