/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:22 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <TSReading/TSDGLParticleSystem.h>

@interface KNBuildFlameSystem : TSDGLParticleSystem {

	CGSize _actualSize;
	CGPoint* _bottomRow;
	char shouldDraw;

}
+(char)useVisibilities;
+(char)willOverrideStartingPoints;
-(void)setShouldDraw:(char)arg1 ;
-(void)p_setupParticleDataWithTexture:(id)arg1 ;
-(char)shouldDraw;
-(float)speedMax;
-(float)rotationMax;
-(CGPoint)startingPointAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN57)speedAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN57)rotationAtIndexPoint:(CGPoint)arg1 ;
-(CGPoint)lifeSpanAtIndexPoint:(CGPoint)arg1 ;
-(void)dealloc;
@end

