/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:17 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIViewControllerContextTransitioning <NSObject>
@required
-(id)containerView;
-(id)viewControllerForKey:(id)arg1;
-(id)viewForKey:(id)arg1;
-(CGRect*)initialFrameForViewController:(id)arg1;
-(CGRect*)finalFrameForViewController:(id)arg1;
-(char)isInteractive;
-(char)transitionWasCancelled;
-(void)completeTransition:(char)arg1;
-(void)cancelInteractiveTransition;
-(void)finishInteractiveTransition;
-(void)updateInteractiveTransition:(float)arg1;
-(int)presentationStyle;
-(char)isAnimated;
-(CGAffineTransform*)targetTransform;

@end

