/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:23 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/iCloudDriveApp.app/iCloudDriveApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iCloudDriveApp/iCloudDriveApp-Structs.h>
#import <QuickLook/QLPreviewController.h>
#import <iCloudDriveApp/QLPreviewControllerDataSource.h>
#import <libobjc.A.dylib/QLPreviewControllerDelegate.h>

@class PreviewItemManager, NSArray, UIBarButtonItem, NSString;

@interface QuickLookItemController : QLPreviewController <QLPreviewControllerDataSource, QLPreviewControllerDelegate> {

	PreviewItemManager* _itemManager;
	NSArray* _arrayOfDocuments;
	UIBarButtonItem* _barButtonMoveItem;
	UIBarButtonItem* _barButtonDeleteItem;

}

@property (assign,nonatomic,__weak) PreviewItemManager * itemManager;              //@synthesize itemManager=_itemManager - In the implementation block
@property (nonatomic,retain) NSArray * arrayOfDocuments;                           //@synthesize arrayOfDocuments=_arrayOfDocuments - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * barButtonMoveItem;                  //@synthesize barButtonMoveItem=_barButtonMoveItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * barButtonDeleteItem;                //@synthesize barButtonDeleteItem=_barButtonDeleteItem - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)defaultController;
-(PreviewItemManager *)itemManager;
-(void)showMoveTarget:(id)arg1 ;
-(void)showWarningAndDeleteDocument:(id)arg1 ;
-(id)initWithItemManager:(id)arg1 ;
-(void)quickLookNewItem:(id)arg1 ;
-(void)setItemManager:(PreviewItemManager *)arg1 ;
-(NSArray *)arrayOfDocuments;
-(void)setArrayOfDocuments:(NSArray *)arg1 ;
-(UIBarButtonItem *)barButtonMoveItem;
-(void)setBarButtonMoveItem:(UIBarButtonItem *)arg1 ;
-(UIBarButtonItem *)barButtonDeleteItem;
-(void)setBarButtonDeleteItem:(UIBarButtonItem *)arg1 ;
-(id)init;
-(void)viewWillDisappear:(char)arg1 ;
-(char)isVisible;
-(int)numberOfPreviewItemsInPreviewController:(id)arg1 ;
-(id)previewController:(id)arg1 previewItemAtIndex:(int)arg2 ;
@end

