/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:24 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/InCallService.app/InCallService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class TUCall, NSDictionary, AVQueuePlayer, NSString, AVPlayer, PHHoldMusicAudioPlayer;

@interface PHRingtoneController : NSObject {

	char _interrupted;
	char _lastCategoryWasTTY;
	char _listeningForAVNotifications;
	char _isLoggingCallAudio;
	char _isObservingQueuePlayer;
	char _audioMuted;
	int _pid;
	int _currentAudioCategory;
	int _currentAudioMode;
	TUCall* _callNeedingRingtone;
	NSDictionary* _currentActivationContext;
	AVQueuePlayer* _queuePlayer;
	NSString* _currentRingtoneIdentifier;
	NSDictionary* _currentVibrationPattern;
	AVPlayer* _callRecordingPlayer;
	PHHoldMusicAudioPlayer* _holdMusicAudioPlayer;

}

@property (assign,setter=setPID:,nonatomic) int pid;                                     //@synthesize pid=_pid - In the implementation block
@property (assign,nonatomic) char interrupted;                                           //@synthesize interrupted=_interrupted - In the implementation block
@property (assign,nonatomic) char lastCategoryWasTTY;                                    //@synthesize lastCategoryWasTTY=_lastCategoryWasTTY - In the implementation block
@property (assign,nonatomic) char listeningForAVNotifications;                           //@synthesize listeningForAVNotifications=_listeningForAVNotifications - In the implementation block
@property (assign,nonatomic) char isLoggingCallAudio;                                    //@synthesize isLoggingCallAudio=_isLoggingCallAudio - In the implementation block
@property (assign,nonatomic) char isObservingQueuePlayer;                                //@synthesize isObservingQueuePlayer=_isObservingQueuePlayer - In the implementation block
@property (assign,getter=isAudioMuted,nonatomic) char audioMuted;                        //@synthesize audioMuted=_audioMuted - In the implementation block
@property (assign,nonatomic) int currentAudioCategory;                                   //@synthesize currentAudioCategory=_currentAudioCategory - In the implementation block
@property (assign,nonatomic) int currentAudioMode;                                       //@synthesize currentAudioMode=_currentAudioMode - In the implementation block
@property (nonatomic,retain) TUCall * callNeedingRingtone;                               //@synthesize callNeedingRingtone=_callNeedingRingtone - In the implementation block
@property (nonatomic,retain) NSDictionary * currentActivationContext;                    //@synthesize currentActivationContext=_currentActivationContext - In the implementation block
@property (nonatomic,retain) AVQueuePlayer * queuePlayer;                                //@synthesize queuePlayer=_queuePlayer - In the implementation block
@property (nonatomic,retain) NSString * currentRingtoneIdentifier;                       //@synthesize currentRingtoneIdentifier=_currentRingtoneIdentifier - In the implementation block
@property (nonatomic,retain) NSDictionary * currentVibrationPattern;                     //@synthesize currentVibrationPattern=_currentVibrationPattern - In the implementation block
@property (nonatomic,retain) AVPlayer * callRecordingPlayer;                             //@synthesize callRecordingPlayer=_callRecordingPlayer - In the implementation block
@property (nonatomic,retain) PHHoldMusicAudioPlayer * holdMusicAudioPlayer;              //@synthesize holdMusicAudioPlayer=_holdMusicAudioPlayer - In the implementation block
+(id)sharedRingtoneController;
-(void)stopRinging;
-(void)updateAudioCategory:(int)arg1 mode:(int)arg2 activationContext:(id)arg3 ;
-(void)updateAudioCategory:(int)arg1 activationContext:(id)arg2 ;
-(void)updateAudioCategory:(int)arg1 ;
-(void)playRingtoneForCall:(id)arg1 ;
-(void)beginInterruptionWithAudioCategory:(int)arg1 activationContext:(id)arg2 ;
-(void)beginInterruptionWithAudioCategory:(int)arg1 mode:(int)arg2 activationContext:(id)arg3 ;
-(void)updateActivationContext:(id)arg1 ;
-(void)handleCallStatusOrShouldPlayHoldMusicChanged:(id)arg1 ;
-(void)setPID:(int)arg1 ;
-(char)listeningForAVNotifications;
-(void)handleMediaServicesWereResetNotification:(id)arg1 ;
-(void)setListeningForAVNotifications:(char)arg1 ;
-(void)_startListeningForAVNotifications;
-(void)_stopListeningForAVNotifications;
-(void)_stopRingtone;
-(void)_stopVibration;
-(char)_currentCallNeedsInterruption;
-(int)currentAudioCategory;
-(int)currentAudioMode;
-(NSDictionary *)currentActivationContext;
-(NSString *)currentRingtoneIdentifier;
-(NSDictionary *)currentVibrationPattern;
-(void)playRingtoneWithIdentifier:(id)arg1 vibrationPattern:(id)arg2 ;
-(void)_resetInterruptionState;
-(void)_stopObservingQueuePlayer;
-(void)_startObservingQueuePlayer;
-(char)isObservingQueuePlayer;
-(void)setIsObservingQueuePlayer:(char)arg1 ;
-(void)_loadPropertiesAndStartDefaultRingtone;
-(AVPlayer *)callRecordingPlayer;
-(void)setCallRecordingPlayer:(AVPlayer *)arg1 ;
-(void)handleItemPlaybackDidEndNotification:(id)arg1 ;
-(void)_createQueuePlayerIfNecessary;
-(void)setCurrentAudioCategory:(int)arg1 ;
-(char)lastCategoryWasTTY;
-(id)_audioSessionCategoryNameForAudioCategory:(int)arg1 ;
-(void)setLastCategoryWasTTY:(char)arg1 ;
-(char)isLoggingCallAudio;
-(id)_callRecordingDisclaimerAsset;
-(void)_startCallRecordingDisclaimerPlaybackWithAsset:(id)arg1 ;
-(void)setCurrentAudioMode:(int)arg1 ;
-(id)_audioSessionModeNameForAudioMode:(int)arg1 ;
-(void)setCurrentActivationContext:(NSDictionary *)arg1 ;
-(id)_defaultRingtoneIdentifier;
-(void)setCurrentRingtoneIdentifier:(NSString *)arg1 ;
-(id)_ringtoneAssetWithIdentifier:(id)arg1 ;
-(TUCall *)callNeedingRingtone;
-(char)canPlayRingtoneAsset:(id)arg1 ;
-(void)_loadPropertiesAndStartRingtoneWithAsset:(id)arg1 identifier:(id)arg2 ;
-(void)_startRingtoneWithAsset:(id)arg1 ;
-(void)_setActivationContext:(id)arg1 ;
-(void)_updateAudioCategory:(int)arg1 ;
-(void)_updateAudioMode:(int)arg1 ;
-(void)_destroyQueuePlayer;
-(void)_stopCallRecordingDisclaimerPlayback;
-(void)setCallNeedingRingtone:(TUCall *)arg1 ;
-(id)ringtoneIdentifierForAddressBookUID:(int)arg1 ;
-(id)vibrationPatternForAddressBookUID:(int)arg1 ;
-(void)playRingtoneWithIdentifier:(id)arg1 asset:(id)arg2 vibrationPattern:(id)arg3 ;
-(void)setCurrentVibrationPattern:(NSDictionary *)arg1 ;
-(void)_startVibrationWithPattern:(id)arg1 ;
-(void)_reinterruptIfNecessary;
-(PHHoldMusicAudioPlayer *)holdMusicAudioPlayer;
-(void)setHoldMusicAudioPlayer:(PHHoldMusicAudioPlayer *)arg1 ;
-(void)updateAudioMode:(int)arg1 ;
-(void)setIsLoggingCallAudio:(char)arg1 ;
-(void)handleInterruption:(id)arg1 ;
-(void)endInterruption;
-(void)dealloc;
-(id)init;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setQueuePlayer:(AVQueuePlayer *)arg1 ;
-(AVQueuePlayer *)queuePlayer;
-(char)interrupted;
-(void)setInterrupted:(char)arg1 ;
-(char)isAudioMuted;
-(void)setAudioMuted:(char)arg1 ;
-(int)pid;
@end

