/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:24 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/InCallService.app/InCallService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@interface PHStarkGenericViewController : UIViewController {

	char _viewIsInAppearedState;
	char _respondsToEventsWhileInCall;

}

@property (readonly) char viewIsInAppearedState;                  //@synthesize viewIsInAppearedState=_viewIsInAppearedState - In the implementation block
@property (assign) char respondsToEventsWhileInCall;              //@synthesize respondsToEventsWhileInCall=_respondsToEventsWhileInCall - In the implementation block
-(char)shouldRespondToHardwareControlEvent;
-(void)setRespondsToEventsWhileInCall:(char)arg1 ;
-(char)respondsToEventsWhileInCall;
-(char)viewIsInAppearedState;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)hardwareControlEventNotification:(id)arg1 ;
@end

