/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:41 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileNotes/ICNoteBaseActivityItemSource.h>
#import <UIKit/UIActivityItemSource.h>

@protocol ICAirDropDocument;
@class NSString;

@interface ICAirDropNoteActivityItemSource : ICNoteBaseActivityItemSource <UIActivityItemSource> {

	id<ICAirDropDocument> _airDropDocument;
	id _item;

}

@property (nonatomic,retain) id<ICAirDropDocument> airDropDocument;              //@synthesize airDropDocument=_airDropDocument - In the implementation block
@property (nonatomic,retain) id item;                                            //@synthesize item=_item - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setAirDropDocument:(id<ICAirDropDocument>)arg1 ;
-(id<ICAirDropDocument>)airDropDocument;
-(id)initWithTitle:(id)arg1 airDropDocument:(id)arg2 ;
-(id)item;
-(void)setItem:(id)arg1 ;
-(id)activityViewControllerPlaceholderItem:(id)arg1 ;
-(id)activityViewController:(id)arg1 itemForActivityType:(id)arg2 ;
-(id)activityViewController:(id)arg1 dataTypeIdentifierForActivityType:(id)arg2 ;
@end

