/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:40 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <libobjc.A.dylib/QLPreviewControllerDataSource.h>
#import <libobjc.A.dylib/QLPreviewControllerDelegate.h>
#import <MobileNotes/ICAttachmentPresentationDelegate.h>
#import <MobileNotes/ICImageAttachmentPresentationDelegate.h>

@class ICAttachment, UIView, UIViewController, UIBarButtonItem, NSString;

@interface ICAttachmentPresenter : NSObject <QLPreviewControllerDataSource, QLPreviewControllerDelegate, ICAttachmentPresentationDelegate, ICImageAttachmentPresentationDelegate> {

	char _showGoToNote;
	char _editable;
	ICAttachment* _attachment;
	UIView* _viewToPresentFrom;
	UIViewController* _presentedViewController;
	UIViewController* _presentingViewController;
	UIBarButtonItem* _goToNoteButton;

}

@property (retain) ICAttachment * attachment;                                //@synthesize attachment=_attachment - In the implementation block
@property (retain) UIView * viewToPresentFrom;                               //@synthesize viewToPresentFrom=_viewToPresentFrom - In the implementation block
@property (assign) char showGoToNote;                                        //@synthesize showGoToNote=_showGoToNote - In the implementation block
@property (getter=isEditable) char editable;                                 //@synthesize editable=_editable - In the implementation block
@property (retain) UIViewController * presentedViewController;               //@synthesize presentedViewController=_presentedViewController - In the implementation block
@property (retain) UIViewController * presentingViewController;              //@synthesize presentingViewController=_presentingViewController - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * goToNoteButton;               //@synthesize goToNoteButton=_goToNoteButton - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)presentAttachment:(id)arg1 fromView:(id)arg2 showGoToNote:(char)arg3 ;
+(char)presentAttachment:(id)arg1 fromView:(id)arg2 showGoToNote:(char)arg3 editable:(char)arg4 presentingViewController:(id)arg5 ;
+(id)previewViewControllerForAttachment:(id)arg1 fromView:(id)arg2 isFromAttachmentBrowser:(char)arg3 ;
-(id)previewMenuItemsForAttachment;
-(void)goToNote:(id)arg1 ;
-(UIBarButtonItem *)goToNoteButton;
-(void)setGoToNoteButton:(UIBarButtonItem *)arg1 ;
-(void)setViewToPresentFrom:(UIView *)arg1 ;
-(void)setShowGoToNote:(char)arg1 ;
-(void)presentAttachment;
-(void)presentImage;
-(void)presentMovie;
-(void)presentURL;
-(void)presentDrawing;
-(void)presentQuickLook;
-(void)attachmentWillBeDeletedNotification:(id)arg1 ;
-(char)showGoToNote;
-(void)presentAttachmentViewController:(id)arg1 ;
-(UIView *)viewToPresentFrom;
-(id)viewToPresentFromForQuickLook;
-(UIView*)viewToPresentAttachmentFrom;
-(void)attachmentViewControllerDidDismiss:(id)arg1 ;
-(void)dealloc;
-(char)prefersStatusBarHidden;
-(UIViewController *)presentingViewController;
-(void)openURL:(id)arg1 ;
-(char)isEditable;
-(UIImage*)image;
-(UIViewController *)presentedViewController;
-(void)setPresentingViewController:(UIViewController *)arg1 ;
-(void)setEditable:(char)arg1 ;
-(void)dismiss:(id)arg1 ;
-(id)initWithAttachment:(id)arg1 ;
-(CGRect)previewController:(id)arg1 frameForPreviewItem:(id)arg2 inSourceView:(id*)arg3 ;
-(void)previewControllerDidDismiss:(id)arg1 ;
-(id)previewController:(id)arg1 transitionImageForPreviewItem:(id)arg2 contentRect:(CGRect*)arg3 ;
-(int)numberOfPreviewItemsInPreviewController:(id)arg1 ;
-(id)previewController:(id)arg1 previewItemAtIndex:(int)arg2 ;
-(void)setAttachment:(ICAttachment *)arg1 ;
-(ICAttachment *)attachment;
-(void)setPresentedViewController:(UIViewController *)arg1 ;
@end

