/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:41 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <UIKit/UIView.h>

@class NSArray, UILabel, UIImageView;

@interface ICFolderSelectorPaletteView : UIView {

	NSArray* _notes;
	UILabel* _headingLabel;
	UILabel* _subheadingLabel;
	UIImageView* _imageView;

}

@property (nonatomic,retain) NSArray * notes;              //@synthesize notes=_notes - In the implementation block
@property (retain) UILabel * headingLabel;                 //@synthesize headingLabel=_headingLabel - In the implementation block
@property (retain) UILabel * subheadingLabel;              //@synthesize subheadingLabel=_subheadingLabel - In the implementation block
@property (retain) UIImageView * imageView;                //@synthesize imageView=_imageView - In the implementation block
-(void)updateImageAndLabels;
-(id)previewImageForNotes:(id)arg1 ;
-(UILabel *)headingLabel;
-(id)headingStringForNotes:(id)arg1 ;
-(UILabel *)subheadingLabel;
-(id)subheadingStringForNotes:(id)arg1 ;
-(void)setHeadingLabel:(UILabel *)arg1 ;
-(void)setSubheadingLabel:(UILabel *)arg1 ;
-(NSArray *)notes;
-(void)setNotes:(NSArray *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)init;
-(void)setFrame:(CGRect)arg1 ;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(id)initFromNib;
@end

