/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:41 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface ICMutableBool : NSObject {

	char _value;

}

@property (assign,nonatomic) char value;              //@synthesize value=_value - In the implementation block
-(char)value;
-(void)setValue:(char)arg1 ;
@end

