/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:42 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <CoreImage/CIDetector.h>

@interface ICSalienceDetector : CIDetector {

	float _blurMultiplier1;
	float _blurMultiplier2;
	float _contrast;
	float _brightness;

}

@property (assign) float blurMultiplier1;              //@synthesize blurMultiplier1=_blurMultiplier1 - In the implementation block
@property (assign) float blurMultiplier2;              //@synthesize blurMultiplier2=_blurMultiplier2 - In the implementation block
@property (assign) float contrast;                     //@synthesize contrast=_contrast - In the implementation block
@property (assign) float brightness;                   //@synthesize brightness=_brightness - In the implementation block
+(CGRect)boundingRectFromEdgeFeatures:(id)arg1 ;
+(UIImage*)imageByEdgeFilteringImage:(UIImage*)arg1 ;
+(id)CIImageByResizingImage:(id)arg1 withScale:(float)arg2 ;
+(id)CIImageFromImage:(UIImage*)arg1 ;
+(UIImage*)imageFromCIImage:(id)arg1 ;
+(id)filterForNormalizingAlpha;
+(id)arrayOfPointsWithWidth:(unsigned)arg1 height:(unsigned)arg2 ;
+(id)CIImageByFilteringImageLineOverlay:(id)arg1 ;
+(id)CIImageByFilteringImageSobel:(id)arg1 ;
+(id)CIImageByFilteringImageCustom:(id)arg1 ;
-(UIImage*)imageByEdgeFilteringImage:(UIImage*)arg1 ;
-(void)setBlurMultiplier1:(float)arg1 ;
-(void)setBlurMultiplier2:(float)arg1 ;
-(id)CIImageByFilteringImage:(id)arg1 ;
-(id)featuresInImageNaive:(id)arg1 ;
-(UIImage*)imageByEdgeFilteringImage:(UIImage*)arg1 initialScale:(float)arg2 ;
-(id)CIImageByFilteringImageGaussian:(id)arg1 ;
-(float)blurMultiplier1;
-(float)blurMultiplier2;
-(id)featuresInImage:(id)arg1 options:(id)arg2 ;
-(id)init;
-(void)setContrast:(float)arg1 ;
-(void)setBrightness:(float)arg1 ;
-(float)brightness;
-(float)contrast;
-(id)featuresInImage:(id)arg1 ;
@end

