/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:43 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NotesDisplayControllerDelegate <NSObject>
@required
-(void)noteDisplayController:(id)arg1 deleteNote:(id)arg2 actionOrigin:(int)arg3;
-(void)noteDisplayController:(id)arg1 beginDisplayingNote:(id)arg2 animated:(char)arg3;
-(void)noteDisplayController:(id)arg1 endDisplayingNote:(id)arg2 animated:(char)arg3;
-(void)noteDisplayController:(id)arg1 noteWasDeletedFromSearchResult:(id)arg2;
-(void)noteDisplayController:(id)arg1 beginEditingNote:(id)arg2 animated:(char)arg3;

@end

