/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:42 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <UIKit/UIInputView.h>

@class UILabel, UISegmentedControl, UISearchBar, UIBarButtonItem;

@interface NotesFindInputView : UIInputView {

	UILabel* _resultsLabel;
	UISegmentedControl* _nextPreviousControl;
	UISearchBar* _searchBar;
	UIBarButtonItem* _controlBarButtonItem;
	UIBarButtonItem* _labelBarButtonItem;
	UIBarButtonItem* _doneBarButtonItem;
	UIBarButtonItem* _searchBarButtonItem;
	UIBarButtonItem* _leftFixedSpaceBarButtonItem;

}

@property (retain) UISearchBar * searchBar;              //@synthesize searchBar=_searchBar - In the implementation block
+(id)toolbarWithItems:(id)arg1 ;
-(void)setSegmentedControlTarget:(id)arg1 action:(SEL)arg2 ;
-(void)setDoneButtonTarget:(id)arg1 action:(SEL)arg2 ;
-(void)setSegmentedControlEnabled:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(UISearchBar *)searchBar;
-(void)setSearchBar:(UISearchBar *)arg1 ;
-(void)didEndSplitTransition;
-(void)setLabelText:(id)arg1 ;
@end

