/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:41 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIWebFindOnPageHighlighterDelegate <NSObject>
@optional
-(void)findOnPageHighlighterDidHighlightMatch:(id)arg1;
-(void)findOnPageHighlighterSearchDidBegin:(id)arg1;
-(void)findOnPageHighlighterSearchDidTimeOut:(id)arg1;
-(void)findOnPageHighlighterSearchWasCancelled:(id)arg1;
-(void)findOnPageHighlighterSearchLimitHit:(id)arg1;
-(void)findOnPageHighlighterSearchDidFinish:(id)arg1;
-(void)findOnPageHighlighter:(id)arg1 hasPartialSearchResults:(id)arg2;

@end

