/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:34 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MessagesViewService.app/MessagesViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface MVSAppDelegate : NSObject
-(char)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
@end

