/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:58 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Bridge/COSLinkCell.h>

@class COSApplicationTypeMixin;

@interface COSApplicationLinkCell : COSLinkCell {

	COSApplicationTypeMixin* _application;

}

@property (nonatomic,readonly) COSApplicationTypeMixin * application;              //@synthesize application=_application - In the implementation block
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3 ;
-(void)layoutSubviews;
-(COSApplicationTypeMixin *)application;
@end

