/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:59 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Bridge/COSAppleIDLinkerDelegate.h>

@protocol COSAppleIDAuthControllerDelegate, OS_dispatch_source;
@class ACAccountStore, ACAccount, NSString, NSObject, NRDevice, AKAnisetteData, AKAppleIDAuthenticationController, COSAppleIDLinker;

@interface COSAppleIDAuthController : NSObject <COSAppleIDLinkerDelegate> {

	char _didComplete;
	char _hasStartedFallbackFlow;
	ACAccountStore* _accountStore;
	ACAccount* _account;
	NSString* _password;
	id<COSAppleIDAuthControllerDelegate> _delegate;
	NSObject*<OS_dispatch_source> _timerSource;
	ACAccount* _idmsAccount;
	NRDevice* _watchDevice;
	AKAnisetteData* _phoneAnisetteData;
	AKAppleIDAuthenticationController* _authController;
	AKAnisetteData* _watchAnisetteData;
	NSString* _watchClientInfo;
	NSString* _watchUDID;
	COSAppleIDLinker* _appleIDLinker;
	double _timeout;

}

@property (nonatomic,retain) ACAccountStore * accountStore;                                     //@synthesize accountStore=_accountStore - In the implementation block
@property (nonatomic,retain) ACAccount * account;                                               //@synthesize account=_account - In the implementation block
@property (nonatomic,retain) NSString * password;                                               //@synthesize password=_password - In the implementation block
@property (assign,nonatomic) double timeout;                                                    //@synthesize timeout=_timeout - In the implementation block
@property (assign,nonatomic,__weak) id<COSAppleIDAuthControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> timerSource;                         //@synthesize timerSource=_timerSource - In the implementation block
@property (assign,nonatomic) char didComplete;                                                  //@synthesize didComplete=_didComplete - In the implementation block
@property (nonatomic,retain) ACAccount * idmsAccount;                                           //@synthesize idmsAccount=_idmsAccount - In the implementation block
@property (nonatomic,retain) NRDevice * watchDevice;                                            //@synthesize watchDevice=_watchDevice - In the implementation block
@property (nonatomic,retain) AKAnisetteData * phoneAnisetteData;                                //@synthesize phoneAnisetteData=_phoneAnisetteData - In the implementation block
@property (assign,nonatomic) char hasStartedFallbackFlow;                                       //@synthesize hasStartedFallbackFlow=_hasStartedFallbackFlow - In the implementation block
@property (nonatomic,retain) AKAppleIDAuthenticationController * authController;                //@synthesize authController=_authController - In the implementation block
@property (nonatomic,retain) AKAnisetteData * watchAnisetteData;                                //@synthesize watchAnisetteData=_watchAnisetteData - In the implementation block
@property (nonatomic,retain) NSString * watchClientInfo;                                        //@synthesize watchClientInfo=_watchClientInfo - In the implementation block
@property (nonatomic,retain) NSString * watchUDID;                                              //@synthesize watchUDID=_watchUDID - In the implementation block
@property (nonatomic,retain) COSAppleIDLinker * appleIDLinker;                                  //@synthesize appleIDLinker=_appleIDLinker - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)shouldAttemptPasswordLessSignInForAccount:(id)arg1 inAccountStore:(id)arg2 ;
+(char)pairedWatchSupportsAuthKitBasedSignIn;
+(id)lookupIDMSAccountWithAccountStore:(id)arg1 matchingAccount:(id)arg2 ;
+(void)saveVerifiedRawPassword:(id)arg1 forAccountIdentifier:(id)arg2 withCompletionHandler:(/*^block*/id)arg3 ;
-(id)initWithAccountStore:(id)arg1 account:(id)arg2 timeout:(double)arg3 ;
-(void)startSigningInWithPassword:(id)arg1 ;
-(void)startSigningInWithoutPassword;
-(void)startLegacySignInWithPassword:(id)arg1 ;
-(AKAppleIDAuthenticationController *)authController;
-(void)setAuthController:(AKAppleIDAuthenticationController *)arg1 ;
-(void)appleIDLinker:(id)arg1 didFinishWithSuccess:(char)arg2 error:(id)arg3 ;
-(id)viewControllerToPresentSecondFactorUIForAppleIDLinker:(id)arg1 ;
-(void)appleIDLinkerWillStartSecondFactorAuthentication:(id)arg1 ;
-(void)appleIDLinkerDidFinishSecondFactorAuthentication:(id)arg1 ;
-(void)cancelSignInTimer;
-(void)startSignInTimer;
-(void)attemptMagicSignIn;
-(void)fetchAnisetteDataForPhone;
-(void)signInTimerFired;
-(void)reportSignInCompletionWithSuccess:(char)arg1 error:(id)arg2 ;
-(void)fetchedAnisetteDataForPhone:(id)arg1 error:(id)arg2 ;
-(void)saveAccountToPairedDeviceWithOptions:(id)arg1 ;
-(void)savedAccountToPairedDeviceWithSuccess:(char)arg1 error:(id)arg2 ;
-(void)performProxiedAuthentication;
-(id)proxiedWatchDevice;
-(id)httpHeadersForRemoteAuthUI;
-(void)authenticatedWithResults:(id)arg1 error:(id)arg2 ;
-(void)saveAccountToPairedDeviceWithRawPassword:(id)arg1 ;
-(char)didComplete;
-(void)setDidComplete:(char)arg1 ;
-(ACAccount *)idmsAccount;
-(void)setIdmsAccount:(ACAccount *)arg1 ;
-(NRDevice *)watchDevice;
-(void)setWatchDevice:(NRDevice *)arg1 ;
-(AKAnisetteData *)phoneAnisetteData;
-(void)setPhoneAnisetteData:(AKAnisetteData *)arg1 ;
-(char)hasStartedFallbackFlow;
-(void)setHasStartedFallbackFlow:(char)arg1 ;
-(AKAnisetteData *)watchAnisetteData;
-(void)setWatchAnisetteData:(AKAnisetteData *)arg1 ;
-(NSString *)watchClientInfo;
-(void)setWatchClientInfo:(NSString *)arg1 ;
-(NSString *)watchUDID;
-(void)setWatchUDID:(NSString *)arg1 ;
-(COSAppleIDLinker *)appleIDLinker;
-(void)setAppleIDLinker:(COSAppleIDLinker *)arg1 ;
-(void)setAccountStore:(ACAccountStore *)arg1 ;
-(NSString *)password;
-(void)setPassword:(NSString *)arg1 ;
-(ACAccountStore *)accountStore;
-(double)timeout;
-(void)setDelegate:(id<COSAppleIDAuthControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<COSAppleIDAuthControllerDelegate>)delegate;
-(void)setTimeout:(double)arg1 ;
-(NSObject*<OS_dispatch_source>)timerSource;
-(void)setTimerSource:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)setAccount:(ACAccount *)arg1 ;
-(ACAccount *)account;
@end

