/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:59 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSRootController.h>

@protocol COSBuddyNavigationControllerDelegate;
@interface COSBuddyNavigationController : PSRootController {

	id<COSBuddyNavigationControllerDelegate> _buddyNavDelegate;

}

@property (assign,nonatomic) id<COSBuddyNavigationControllerDelegate> buddyNavDelegate;              //@synthesize buddyNavDelegate=_buddyNavDelegate - In the implementation block
-(void)setBuddyNavDelegate:(id<COSBuddyNavigationControllerDelegate>)arg1 ;
-(id<COSBuddyNavigationControllerDelegate>)buddyNavDelegate;
-(id)popViewControllerAnimated:(char)arg1 ;
-(unsigned)supportedInterfaceOrientations;
-(char)_usesTransitionController;
@end

