/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:58 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSSetupController.h>

@class NSString;

@interface COSInternationalLanguageSetupController : PSSetupController {

	NSString* _languageToSet;

}

@property (nonatomic,copy) NSString * languageToSet;              //@synthesize languageToSet=_languageToSet - In the implementation block
-(void)setLanguageToSet:(NSString *)arg1 ;
-(NSString *)languageToSet;
-(char)useOfficialLanguages;
-(int)preferredStatusBarStyle;
-(void)commit;
-(void)setupController;
-(void)setLanguage:(id)arg1 specifier:(id)arg2 ;
@end

