/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:59 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>

@class NRPairedDeviceRegistry, NRDevice;

@interface COSPairingController : PSListController {

	char _allowsMarkAsMissing;
	NRPairedDeviceRegistry* _nanoRegistry;
	NRDevice* _device;

}

@property (nonatomic,retain) NRPairedDeviceRegistry * nanoRegistry;              //@synthesize nanoRegistry=_nanoRegistry - In the implementation block
@property (nonatomic,retain) NRDevice * device;                                  //@synthesize device=_device - In the implementation block
@property (assign,nonatomic) char allowsMarkAsMissing;                           //@synthesize allowsMarkAsMissing=_allowsMarkAsMissing - In the implementation block
-(void)nanoRegistryStatusChanged:(id)arg1 ;
-(void)updateStashedDevice;
-(void)confirmUnpairingMissing;
-(void)confirmUnpairing;
-(void)confirmedUnpairMissing;
-(void)confirmedUnpairAndMarkAsMissing:(char)arg1 ;
-(void)confirmedUnpair;
-(void)enableDisableUnpairButton:(unsigned)arg1 ;
-(NRPairedDeviceRegistry *)nanoRegistry;
-(void)setNanoRegistry:(NRPairedDeviceRegistry *)arg1 ;
-(char)allowsMarkAsMissing;
-(void)setAllowsMarkAsMissing:(char)arg1 ;
-(void)_applicationResumed:(id)arg1 ;
-(id)specifiers;
-(void)dealloc;
-(id)init;
-(void)viewWillAppear:(char)arg1 ;
-(NRDevice *)device;
-(void)setDevice:(NRDevice *)arg1 ;
@end

