/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:58 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSAppListController.h>
#import <libobjc.A.dylib/SPDeviceConnectionDelegate.h>
#import <libobjc.A.dylib/MCProfileConnectionObserver.h>

@class BPSAppGlanceManager, PSSpecifier, NSString;

@interface COSSockPuppetAppListController : PSAppListController <SPDeviceConnectionDelegate, MCProfileConnectionObserver> {

	BPSAppGlanceManager* _manager;
	PSSpecifier* _glanceSpecifier;

}

@property (nonatomic,retain) BPSAppGlanceManager * manager;              //@synthesize manager=_manager - In the implementation block
@property (nonatomic,retain) PSSpecifier * glanceSpecifier;              //@synthesize glanceSpecifier=_glanceSpecifier - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)refreshGlanceSpecifierEnableStateAndReloadSpecifier:(char)arg1 ;
-(void)launchTestFlight:(id)arg1 ;
-(void)setPuppetAppShows:(id)arg1 specifier:(id)arg2 ;
-(id)puppetAppShows:(id)arg1 ;
-(void)restrictShowOnWatchSpecifierIfNecessary:(id)arg1 ;
-(void)_resetAfterSockPuppetResponseWithState:(int)arg1 ;
-(PSSpecifier *)glanceSpecifier;
-(void)setGlanceSpecifier:(PSSpecifier *)arg1 ;
-(void)setManager:(BPSAppGlanceManager *)arg1 ;
-(BPSAppGlanceManager *)manager;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2 ;
-(id)specifiers;
-(void)dealloc;
-(id)init;
-(void)viewWillAppear:(char)arg1 ;
-(void)updateInstallStateForApplication:(id)arg1 installState:(int)arg2 ;
-(void)setPreferenceValue:(id)arg1 specifier:(id)arg2 ;
-(id)systemPolicy;
@end

