/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:07 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface RingViewFactory : NSObject
+(id)sharedRingsVC;
+(id)workoutRingWithPercent:(float)arg1 colors:(id)arg2 diameter:(float)arg3 thickness:(float)arg4 ;
@end

