/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:07 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Fitness/Fitness-Structs.h>
#import <UIKit/UITableViewCell.h>

@class UILabel, UIView;

@interface SplitRowCell : UITableViewCell {

	UILabel* _unitLabel;
	UILabel* _paceLabel;
	UIView* _topBorder;
	float _additionalBottomMargin;

}

@property (assign,nonatomic) float additionalBottomMargin;              //@synthesize additionalBottomMargin=_additionalBottomMargin - In the implementation block
+(id)lengthFormatter;
-(id)initWithUnit:(id)arg1 count:(int)arg2 split:(id)arg3 useCyclingFormat:(char)arg4 ;
-(float)additionalBottomMargin;
-(void)setAdditionalBottomMargin:(float)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

