/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:07 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIApplicationTestingDelegate <UIApplicationDelegate>
@optional
-(char)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;

@end

