/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:04 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FieldTest.app/FieldTest
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FieldTest/FieldTestModelNode.h>

@class NSArray;

@interface FieldTestModelTreeNode : FieldTestModelNode {

	NSArray* _childNodes;

}
-(id)initWithName:(id)arg1 withChildren:(id)arg2 ;
-(void)dealloc;
-(id)childNodes;
@end

