/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:04 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class ACMInitialToken, NSString;

@interface ACMServiceTicket : NSObject {

	ACMInitialToken* _initialToken;
	id _publicKey;
	id _deviceIdentity;

}

@property (nonatomic,readonly) ACMInitialToken * initialToken;              //@synthesize initialToken=_initialToken - In the implementation block
@property (retain) id publicKey;                                            //@synthesize publicKey=_publicKey - In the implementation block
@property (retain) id deviceIdentity;                                       //@synthesize deviceIdentity=_deviceIdentity - In the implementation block
@property (nonatomic,readonly) NSString * tokenString; 
+(id)serviceTicketWithRequest:(id)arg1 ssoToken:(id)arg2 initialTokenClass:(Class)arg3 ;
-(void)dealloc;
-(void)setPublicKey:(id)arg1 ;
-(id)publicKey;
-(NSString *)tokenString;
-(ACMInitialToken *)initialToken;
-(void)setDeviceIdentity:(id)arg1 ;
-(id)deviceIdentity;
@end

