/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:03 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class FBAQuestionChoice;

@interface FBAChoiceCell : UITableViewCell {

	FBAQuestionChoice* _choice;

}

@property (assign,nonatomic,__weak) FBAQuestionChoice * choice;              //@synthesize choice=_choice - In the implementation block
-(void)setChoice:(FBAQuestionChoice *)arg1 ;
-(FBAQuestionChoice *)choice;
-(void)updateWithChoice:(id)arg1 ;
-(void)evaluateSelectionWithValue:(id)arg1 ;
-(void)evaluateSelectionWithValues:(id)arg1 ;
@end

