/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:03 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSNumber, NSMutableArray, NSURL;

@interface FBAURLAction : NSObject {

	NSString* _action;
	NSNumber* _projectID;
	NSString* _bundleID;
	NSString* _currentBuild;
	NSMutableArray* _attachments;
	NSURL* _url;
	NSNumber* _entityID;
	NSString* _entityName;

}

@property (retain) NSString * action;                            //@synthesize action=_action - In the implementation block
@property (retain) NSNumber * projectID;                         //@synthesize projectID=_projectID - In the implementation block
@property (retain) NSString * bundleID;                          //@synthesize bundleID=_bundleID - In the implementation block
@property (retain) NSString * currentBuild;                      //@synthesize currentBuild=_currentBuild - In the implementation block
@property (retain) NSMutableArray * attachments;                 //@synthesize attachments=_attachments - In the implementation block
@property (nonatomic,retain) NSURL * url;                        //@synthesize url=_url - In the implementation block
@property (nonatomic,retain) NSNumber * entityID;                //@synthesize entityID=_entityID - In the implementation block
@property (nonatomic,retain) NSString * entityName;              //@synthesize entityName=_entityName - In the implementation block
+(char)willOpenForApplication:(id)arg1 ;
+(char)validateURL:(id)arg1 ;
+(id)actionWithURL:(id)arg1 ;
+(id)mappingForBundleID:(id)arg1 ;
+(id)urlStringForAction:(id)arg1 entityID:(id)arg2 ;
+(id)fbaBundleIdentifier;
-(id)queryItemsForURL:(id)arg1 ;
-(NSNumber *)projectID;
-(void)setProjectID:(NSNumber *)arg1 ;
-(NSString *)currentBuild;
-(void)setCurrentBuild:(NSString *)arg1 ;
-(void)setEntityID:(NSNumber *)arg1 ;
-(NSNumber *)entityID;
-(NSString *)bundleID;
-(id)description;
-(NSURL *)url;
-(NSString *)action;
-(void)setAction:(NSString *)arg1 ;
-(void)setUrl:(NSURL *)arg1 ;
-(id)initWithURL:(id)arg1 ;
-(NSMutableArray *)attachments;
-(void)setAttachments:(NSMutableArray *)arg1 ;
-(void)setEntityName:(NSString *)arg1 ;
-(void)setBundleID:(NSString *)arg1 ;
-(NSString *)entityName;
@end

