/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIInputView.h>
#import <UIKit/UISearchBarDelegate.h>

@protocol FindOnPageToolbarDelegate;
@class UIToolbar, UIBarButtonItem, UISearchBar, NSArray, NSTimer, UILabel, NSString, UITextField;

@interface FindOnPageToolbar : UIInputView <UISearchBarDelegate> {

	UIToolbar* _toolbar;
	UIBarButtonItem* _previousButtonItem;
	UIBarButtonItem* _nextButtonItem;
	UISearchBar* _inputBar;
	UIBarButtonItem* _inputFieldBarButtonItem;
	UIBarButtonItem* _doneBarButtonItem;
	NSArray* _narrowToolbarItems;
	NSArray* _standardToolbarItems;
	id<FindOnPageToolbarDelegate> _findDelegate;
	NSTimer* _textChangedUpdateTimer;
	UILabel* _inFieldMatchLabel;
	UILabel* _matchLabel;
	char _editing;
	char _usesNarrowLayout;
	NSString* _searchText;

}

@property (nonatomic,readonly) UITextField * inputField; 
@property (nonatomic,copy) NSString * searchText;                     //@synthesize searchText=_searchText - In the implementation block
@property (assign,nonatomic) char usesNarrowLayout;                   //@synthesize usesNarrowLayout=_usesNarrowLayout - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)updateFindOnPageDelegate;
-(UITextField *)inputField;
-(void)previous:(id)arg1 ;
-(void)_initializeToolbarItems;
-(float)_widthOfAllToolbarItemsExceptInputField;
-(char)_updateEditing:(char)arg1 ;
-(void)_doUpdateSearchText;
-(void)next:(id)arg1 ;
-(void)setSearchText:(NSString *)arg1 ;
-(void)setUsesNarrowLayout:(char)arg1 ;
-(char)usesNarrowLayout;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)intrinsicContentSize;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2 ;
-(char)searchBarShouldBeginEditing:(id)arg1 ;
-(void)searchBarTextDidBeginEditing:(id)arg1 ;
-(void)searchBarTextDidEndEditing:(id)arg1 ;
-(void)searchBarSearchButtonClicked:(id)arg1 ;
-(NSString *)searchText;
-(void)dismiss:(id)arg1 ;
-(CGSize)leftContentViewSize;
-(CGSize)rightContentViewSize;
-(void)_orientationDidChange:(id)arg1 ;
-(void)updateUI;
-(void)_done;
@end

