/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, UIImageView;

@interface QLDocumentInfoView : UIView {

	UILabel* _documentNameLabel;
	UILabel* _documentSizeLabel;
	UIImageView* _iconImageView;

}

@property (nonatomic,retain) UILabel * documentNameLabel;              //@synthesize documentNameLabel=_documentNameLabel - In the implementation block
@property (nonatomic,retain) UILabel * documentSizeLabel;              //@synthesize documentSizeLabel=_documentSizeLabel - In the implementation block
@property (nonatomic,retain) UIImageView * iconImageView;              //@synthesize iconImageView=_iconImageView - In the implementation block
-(void)updateWithQuickLookDocument:(id)arg1 ;
-(id)_iconImageForDocumentProxy:(id)arg1 ;
-(UILabel *)documentNameLabel;
-(void)setDocumentNameLabel:(UILabel *)arg1 ;
-(UILabel *)documentSizeLabel;
-(void)setDocumentSizeLabel:(UILabel *)arg1 ;
-(UIImageView *)iconImageView;
-(void)setIconImageView:(UIImageView *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
@end

