/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:13:01 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Stocks.app/Stocks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Stocks/Stocks-Structs.h>
#import <UIKit/UIView.h>
#import <Stocks/StockUpdateObserver.h>

@protocol StocksStatusViewDelegate;
@class UIButton, UIPageControl, UILabel, Stock, NSString;

@interface StocksStatusView : UIView <StockUpdateObserver> {

	UIButton* _infoButton;
	UIButton* _viewStockButton;
	UIPageControl* _pageControl;
	UILabel* _statusLabel;
	Stock* _stock;
	id<StocksStatusViewDelegate> _delegate;
	float _centeringRatio;

}

@property (nonatomic,retain) Stock * stock;                                             //@synthesize stock=_stock - In the implementation block
@property (assign,nonatomic,__weak) id<StocksStatusViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) int numberOfPages; 
@property (assign,nonatomic) float centeringRatio;                                      //@synthesize centeringRatio=_centeringRatio - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setCenteringRatio:(float)arg1 ;
-(void)_infoButtonPressed;
-(void)_viewStockButtonPressed;
-(void)quotesUpdated;
-(float)centeringRatio;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<StocksStatusViewDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id<StocksStatusViewDelegate>)delegate;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)setNumberOfPages:(int)arg1 ;
-(void)setCurrentPage:(int)arg1 ;
-(int)numberOfPages;
-(Stock *)stock;
-(void)setStock:(Stock *)arg1 ;
-(void)stockUpdateManager:(id)arg1 didUpdateStocks:(id)arg2 updates:(int)arg3 ;
@end

