/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:13:01 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Stocks.app/Stocks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Stocks/Stocks-Structs.h>
#import <UIKit/UIView.h>
#import <Stocks/ChartUpdaterDelegate.h>
#import <Stocks/ChartIntervalButtonRowDelegate.h>
#import <Stocks/StockGraphViewContainer.h>
#import <Stocks/StockUpdateObserver.h>

@class LoadingLabel, ChartUpdater, ChartIntervalButtonRow, Stock, NSMutableArray, DashedLineView, UILabel, ChartTitleLabel, ChartHUDView, UIView, NSMutableDictionary, StocksViewController, StockChartData, NSError, StockChartDisplayMode, NSArray, NSString;

@interface StockChartView : UIView <ChartUpdaterDelegate, ChartIntervalButtonRowDelegate, StockGraphViewContainer, StockUpdateObserver> {

	LoadingLabel* _loadingLabel;
	ChartUpdater* _chartUpdater;
	ChartIntervalButtonRow* _intervalButtonRow;
	Stock* _stock;
	int _selectedInterval;
	NSMutableArray* _axisViews;
	NSMutableArray* _xLabelViews;
	NSMutableArray* _yLabelViews;
	DashedLineView* _previousCloseLine;
	UILabel* _previousCloseLabel;
	ChartTitleLabel* _titleView;
	ChartHUDView* _HUDView;
	char _animating;
	char _layoutPending;
	UIView* _chartTopKeyline;
	UIView* _chartBottomKeyline;
	UIView* _xAxisKeyline;
	NSMutableArray* _displayModes;
	NSMutableDictionary* _graphViews;
	char _drawsBottomLine;
	StocksViewController* _controller;
	StockChartData* _chartData;
	NSError* _error;
	StockChartDisplayMode* _currentDisplayMode;

}

@property (assign,nonatomic,__weak) StocksViewController * controller;                //@synthesize controller=_controller - In the implementation block
@property (nonatomic,retain) Stock * stock;                                           //@synthesize stock=_stock - In the implementation block
@property (nonatomic,retain) StockChartData * chartData;                              //@synthesize chartData=_chartData - In the implementation block
@property (nonatomic,retain) NSError * error;                                         //@synthesize error=_error - In the implementation block
@property (nonatomic,retain) StockChartDisplayMode * currentDisplayMode;              //@synthesize currentDisplayMode=_currentDisplayMode - In the implementation block
@property (nonatomic,readonly) NSArray * alternateDisplayModes; 
@property (assign,nonatomic) char drawsBottomLine;                                    //@synthesize drawsBottomLine=_drawsBottomLine - In the implementation block
@property (assign,nonatomic) int selectedInterval; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)allCharts;
+(CGGradientRef)LineBackgroundGradient;
+(char)anyChartLoading;
+(void)initialize;
-(void)createYLabelsForMode:(id)arg1 ;
-(void)addDisplayMode:(id)arg1 ;
-(void)setCurrentDisplayMode:(StockChartDisplayMode *)arg1 ;
-(void)setSelectedInterval:(int)arg1 ;
-(void)_prepareYAxisLabelsAndPositionsForDisplayMode:(id)arg1 ;
-(void)setMaxChartInterval:(int)arg1 ;
-(id)graphViewForMode:(id)arg1 ;
-(void)enumerateGraphsAndDisplayModesUsingBlock:(/*^block*/id)arg1 ;
-(id)currentGraphView;
-(void)_layoutTopLabelsHidden:(char)arg1 ;
-(void)hideLabelsAxesAndGraphs;
-(void)_setShowingLoadingStatus:(char)arg1 ;
-(void)layoutGraphViews;
-(void)_layoutIntervalButtonRow;
-(char)shouldShowLoadingStatus;
-(void)_layoutVolumeSeparatorLineForGraphRect:(CGRect)arg1 ;
-(void)_layoutYLabels;
-(void)_layoutAxesAndXLabels;
-(void)layoutPreviousClose;
-(char)drawsBottomLine;
-(char)isCurrentChart;
-(void)renderGraphDataIfNeeded;
-(void)updateHUDView;
-(void)renderGraphDataIfNeededForMode:(id)arg1 ;
-(void)setLabelsAndAxesAlpha:(float)arg1 ;
-(void)setShowingHUD:(char)arg1 ;
-(void)layoutLoadingStatus;
-(int)selectedInterval;
-(id)initWithStock:(id)arg1 initialDisplayMode:(id)arg2 ;
-(void)setDrawsBottomLine:(char)arg1 ;
-(NSArray *)alternateDisplayModes;
-(id)chartUpdater;
-(void)reloadDataIfStale;
-(id)HUDView;
-(id)intervalButtonRow;
-(double)_evennessOfValue:(double)arg1 inRange:(double)arg2 ;
-(void)prepareForTransitionToDisplayMode:(id)arg1 ;
-(void)animateTransitionToDisplayMode:(id)arg1 ;
-(void)didTransitionToDisplayMode:(id)arg1 ;
-(void)_layoutSubviews;
-(NSError *)error;
-(void)setNeedsLayout;
-(void)reloadData;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(NSString *)description;
-(void)layoutIfNeeded;
-(void)forceLayout;
-(char)isLoading;
-(StocksViewController *)controller;
-(void)setController:(StocksViewController *)arg1 ;
-(void)setError:(NSError *)arg1 ;
-(StockChartData *)chartData;
-(void)setChartData:(StockChartData *)arg1 ;
-(void)resetLocale;
-(void)clearData;
-(void)_prepareXAxisLabelsAndPositions;
-(void)_setHourLabels;
-(void)_setDayLabelsWithInterval:(unsigned)arg1 realTimePositions:(char)arg2 ;
-(void)_setMonthAndYearLabels;
-(CGRect)lineGraphFrame;
-(StockChartDisplayMode *)currentDisplayMode;
-(CGRect)graphViewFrameForMode:(id)arg1 ;
-(float)lineGraphBottomPadding;
-(float)widestYLabelWidthForMode:(id)arg1 ;
-(void)stockGraphViewReadyForDisplay:(id)arg1 ;
-(Stock *)stock;
-(void)setStock:(Stock *)arg1 ;
-(char)hadError;
-(void)chartUpdater:(id)arg1 didReceiveStockChartData:(id)arg2 ;
-(void)chartUpdater:(id)arg1 didFailWithError:(id)arg2 ;
@end

