/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:47 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileSlideShow.app/MobileSlideShow
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PLRootLibraryNavigationController;
#import <MobileSlideShow/MobileSlideShow-Structs.h>
@class NSURL;

@interface PhotosURLNavigationRequest : NSObject {

	/*^block*/id _navigationCompletionHandler;
	NSURL* _destinationURL;
	id<PLRootLibraryNavigationController> _rootController;
	int _state;

}

@property (nonatomic,copy,readonly) NSURL * destinationURL;                                              //@synthesize destinationURL=_destinationURL - In the implementation block
@property (nonatomic,retain,readonly) id<PLRootLibraryNavigationController> rootController;              //@synthesize rootController=_rootController - In the implementation block
@property (assign,nonatomic) int state;                                                                  //@synthesize state=_state - In the implementation block
-(id)initWithDestinationURL:(id)arg1 rootController:(id)arg2 ;
-(void)cancelPendingNavigation;
-(void)navigateAllowingRetry:(char)arg1 completion:(/*^block*/id)arg2 ;
-(id)_uuidFromURLParams:(id)arg1 prefix:(id)arg2 ;
-(NSObject*)_albumForKnownName:(id)arg1 orUUID:(id)arg2 requestIsValid:(char*)arg3 ;
-(void)_schedulePendingNavigation;
-(void)_finishNavigationSuccessfully:(char)arg1 ;
-(void)_navigateAllowingRetry:(char)arg1 ;
-(void)_contextDidFinishMerge:(id)arg1 ;
-(void)_processPendingNavigation;
-(NSURL *)destinationURL;
-(void)dealloc;
-(int)state;
-(void)setState:(int)arg1 ;
-(id<PLRootLibraryNavigationController>)rootController;
@end

