/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:47 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileSlideShow.app/MobileSlideShow
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileSlideShow/MobileSlideShow-Structs.h>
#import <PhotoLibrary/PLPhotosApplication.h>
#import <UIKit/UITabBarControllerDelegate.h>

@class PhotosAppSpec, TabbedLibraryViewController, PhotosURLNavigationRequest, WImportViewController, NSMutableArray, NSTimer, UIAlertView, NSString;

@interface PhotosApplication : PLPhotosApplication <UITabBarControllerDelegate> {

	PhotosAppSpec* _spec;
	TabbedLibraryViewController* _tabbedLibraryViewController;
	PhotosURLNavigationRequest* _pendingNavigationRequest;
	WImportViewController* _importController;
	NSMutableArray* _importDeviceQueue;
	NSTimer* _imageCaptureDeviceCheckTimer;
	UIAlertView* _phoneFailureAlertView;
	char _pendingPromptCheck;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_importDeviceAdded:(id)arg1 ;
-(void)_importDeviceRemoved:(id)arg1 ;
-(void)_startupImageCapture;
-(void)_beginiPhotoMigration;
-(void)_showCPLOptimizeStoragePromptIfNecessary;
-(void)_showCloudPhotoLibraryExitPromptIfNecessary;
-(void)_showCPLOverQuotaPromptIfNecessary;
-(void)_showSyncReminderPromptIfNecessary;
-(void)_showCloudPhotoLibraryWelcomeIfNeccesary;
-(void)_showNetworkPromptIfNecessary;
-(void)_dequeueNextImportDevice;
-(void)_imageCaptureDeviceCheckTimerFired:(id)arg1 ;
-(void)handleImportCompleteAlertResponse:(CFUserNotificationRef)arg1 flags:(unsigned long)arg2 ;
-(char)isShowingAppUI;
-(void)dealloc;
-(id)init;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(void)_application:(id)arg1 handleSiriTask:(id)arg2 ;
-(id)rootViewController;
-(void)applicationOpenURL:(id)arg1 ;
-(void)prepareForDefaultImageSnapshotForScreen:(id)arg1 ;
-(char)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(/*^block*/id)arg3 ;
-(char)application:(id)arg1 willContinueUserActivityWithType:(id)arg2 ;
-(void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)tabBarController:(id)arg1 didSelectViewController:(id)arg2 ;
-(char)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2 ;
-(void)setupAppUI:(char)arg1 ;
-(void)sharedFinishedLaunching:(char)arg1 ;
-(void)_displayAndRemovePhoneInvitationFailures;
@end

