/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:10 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol WDChartRendererDataSource <NSObject>
@required
-(id)dataUnit;
-(id)unitController;
-(char)dataForChartRendererIsFinishedLoading:(id)arg1;
-(void)adjustChartBoundsWithMin:(double)arg1 max:(double)arg2 minOut:(double*)arg3 maxOut:(double*)arg4 decimalPrecision:(int*)arg5;
-(unsigned)numberOfSeriesInChartRenderer:(id)arg1;
-(id)chartRenderer:(id)arg1 seriesAtIndex:(unsigned)arg2;
-(unsigned)chartRenderer:(id)arg1 numberOfDataPointsForSeriesAtIndex:(unsigned)arg2;
-(id)chartRenderer:(id)arg1 dataPointAtIndex:(unsigned)arg2 forSeriesAtIndex:(unsigned)arg3;

@end

