/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:10 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <UIKit/UITableViewCell.h>

@class UILabel, UIImageView, NSString, UIImage;

@interface WDDataTableViewCell : UITableViewCell {

	UILabel* _displayLabel;
	UILabel* _dateLabel;
	UIImageView* _iconImageView;
	NSString* _displayValue;
	NSString* _dateString;
	UIImage* _icon;
	UIEdgeInsets _marginInsets;

}

@property (assign,nonatomic) UIEdgeInsets marginInsets;              //@synthesize marginInsets=_marginInsets - In the implementation block
@property (nonatomic,retain) NSString * displayValue;                //@synthesize displayValue=_displayValue - In the implementation block
@property (nonatomic,retain) NSString * dateString;                  //@synthesize dateString=_dateString - In the implementation block
@property (nonatomic,retain) UIImage * icon;                         //@synthesize icon=_icon - In the implementation block
-(void)setDisplayValue:(NSString *)arg1 ;
-(NSString *)displayValue;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)setIcon:(UIImage *)arg1 ;
-(UIImage *)icon;
-(UIEdgeInsets)marginInsets;
-(void)setMarginInsets:(UIEdgeInsets)arg1 ;
-(void)setDateString:(NSString *)arg1 ;
-(NSString *)dateString;
-(void)_setupUI;
@end

