/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:10 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <Health/WDStackedValueSeries.h>

@class UIColor;

@interface WDStackedHorizontalLineSeries : WDStackedValueSeries {

	UIColor* _fillColor;
	float _lineWidth;

}

@property (nonatomic,retain) UIColor * fillColor;              //@synthesize fillColor=_fillColor - In the implementation block
@property (assign,nonatomic) float lineWidth;                  //@synthesize lineWidth=_lineWidth - In the implementation block
-(void)renderFillInContext:(CGContextRef)arg1 ;
-(void)_renderPoints:(id)arg1 withYLocation:(float)arg2 context:(CGContextRef)arg3 ;
-(id)createChartPointsByValueFromDataSet;
-(id)copyWithZone:(NSZone*)arg1 ;
-(float)lineWidth;
-(void)setLineWidth:(float)arg1 ;
-(void)setFillColor:(UIColor *)arg1 ;
-(UIColor *)fillColor;
@end

