/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:10 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITabBarController.h>
#import <libobjc.A.dylib/MFMailComposeViewControllerDelegate.h>

@protocol OS_dispatch_queue;
@class NSObject, MFMailComposeViewController, WDExportManager, NSArray, NSString;

@interface WDTabBarController : UITabBarController <MFMailComposeViewControllerDelegate> {

	NSObject*<OS_dispatch_queue> _exportQueue;
	unsigned _backgroundTask;
	MFMailComposeViewController* _mailComposeVC;
	WDExportManager* _exportManager;
	NSArray* _controlsToDisable;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithControllerManager:(id)arg1 ;
-(void)verifyExport;
-(void)setControlsToDisableDuringExport:(id)arg1 ;
-(void)_presentAlertControllerMessage:(id)arg1 addExportButton:(char)arg2 ;
-(void)_sendExportEmail;
-(unsigned)supportedInterfaceOrientations;
-(char)shouldAutorotate;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3 ;
@end

