/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:11 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface WDUserActivityManager : NSObject
+(id)activityWithTitle:(id)arg1 keywords:(id)arg2 tab:(id)arg3 isCalendar:(char)arg4 category:(id)arg5 dataUnit:(id)arg6 ;
@end

