/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:10 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class HKHealthStore;

@interface WDUserDefaults : NSObject {

	HKHealthStore* _healthStore;

}

@property (nonatomic,retain) HKHealthStore * healthStore;              //@synthesize healthStore=_healthStore - In the implementation block
+(id)sharedDefaults;
-(void)setValue:(id)arg1 forKey:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)valueForKey:(id)arg1 callback:(/*^block*/id)arg2 ;
-(HKHealthStore *)healthStore;
-(void)setHealthStore:(HKHealthStore *)arg1 ;
-(id)init;
@end

