/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:05 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol AddLabelViewControllerDelegate <NSObject>
@required
-(void)addLabelViewControllerDidCancel:(id)arg1;
-(void)addLabelViewControllerDidComplete:(id)arg1;

@end

