/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:05 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FindMyFriends/FindMyFriends-Structs.h>
#import <FindMyFriends/MFMailComposeViewControllerDelegate.h>
#import <libobjc.A.dylib/CLLocationManagerDelegate.h>
#import <UIKit/UIApplicationDelegate.h>
#import <FindMyFriends/FMAPSDelegate.h>

@protocol OS_dispatch_queue;
@class UIWindow, UIStoryboard, ServerInteractionController, UserAccountStore, FMFAccount, StoreController, ModelUpdateController, FMFAddressBookController, BackgroundLocateController, MyLocationController, ActionURLManager, CoreDataManager, FMFConsciousnessManager, FMFInitCommandManager, FMNetworkMonitor, FMFClientLocation, FMDistanceCalculator, NSDictionary, MKMapCamera, FMFSplitViewController, CLLocationManager, NSString, NSArray, FMAPSHandler, NSObject;

@interface FMFAppDelegate : NSObject <MFMailComposeViewControllerDelegate, CLLocationManagerDelegate, UIApplicationDelegate, FMAPSDelegate> {

	char _isAppRestricted;
	char _sessionExpiredWhileAppActive;
	char _didUserAuthenticateUnlocked;
	char _shouldSkipNextOpenURL;
	char _locationManagerFailure;
	char _watchingCLLocation;
	char _watchingCLLocationInBackground;
	char _smlLocServiceStatus;
	char _globalLocServiceStatus;
	char _applicationWasInitialized;
	char _allowedToShowSMLOffAlert;
	char _loadedMainApplication;
	UIWindow* _window;
	UIStoryboard* _storyboard;
	ServerInteractionController* _serverInteractionController;
	UserAccountStore* _userAccountStore;
	FMFAccount* _account;
	StoreController* _storeController;
	ModelUpdateController* _modelUpdateController;
	FMFAddressBookController* _abController;
	BackgroundLocateController* _backgroundLocateController;
	MyLocationController* _myLocationController;
	ActionURLManager* _actionURLManager;
	CoreDataManager* _coreDataManager;
	FMFConsciousnessManager* _consciousnessManager;
	FMFInitCommandManager* _fmfInitCommandManager;
	FMNetworkMonitor* _internetReachability;
	FMFClientLocation* _currentLocation;
	FMDistanceCalculator* _distanceCalculator;
	NSDictionary* _remoteNotificationAlertDict;
	MKMapCamera* _lastCamera;
	FMFSplitViewController* _splitView;
	CLLocationManager* _locationManager;
	NSString* _apsToken;
	id _reachabilityNotificationToken;
	NSArray* _pushMessages;
	FMAPSHandler* _apsHandler;
	NSObject*<OS_dispatch_queue> _launchQueue;
	double _lastUserActivity;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) UIWindow * window;                                                      //@synthesize window=_window - In the implementation block
@property (nonatomic,retain) UIStoryboard * storyboard;                                              //@synthesize storyboard=_storyboard - In the implementation block
@property (nonatomic,retain) ServerInteractionController * serverInteractionController;              //@synthesize serverInteractionController=_serverInteractionController - In the implementation block
@property (nonatomic,retain) UserAccountStore * userAccountStore;                                    //@synthesize userAccountStore=_userAccountStore - In the implementation block
@property (nonatomic,retain) FMFAccount * account;                                                   //@synthesize account=_account - In the implementation block
@property (nonatomic,retain) StoreController * storeController;                                      //@synthesize storeController=_storeController - In the implementation block
@property (nonatomic,retain) ModelUpdateController * modelUpdateController;                          //@synthesize modelUpdateController=_modelUpdateController - In the implementation block
@property (nonatomic,retain) FMFAddressBookController * abController;                                //@synthesize abController=_abController - In the implementation block
@property (nonatomic,retain) BackgroundLocateController * backgroundLocateController;                //@synthesize backgroundLocateController=_backgroundLocateController - In the implementation block
@property (nonatomic,retain) MyLocationController * myLocationController;                            //@synthesize myLocationController=_myLocationController - In the implementation block
@property (nonatomic,retain) ActionURLManager * actionURLManager;                                    //@synthesize actionURLManager=_actionURLManager - In the implementation block
@property (nonatomic,retain) CoreDataManager * coreDataManager;                                      //@synthesize coreDataManager=_coreDataManager - In the implementation block
@property (nonatomic,retain) FMFConsciousnessManager * consciousnessManager;                         //@synthesize consciousnessManager=_consciousnessManager - In the implementation block
@property (nonatomic,retain) FMFInitCommandManager * fmfInitCommandManager;                          //@synthesize fmfInitCommandManager=_fmfInitCommandManager - In the implementation block
@property (nonatomic,retain) FMNetworkMonitor * internetReachability;                                //@synthesize internetReachability=_internetReachability - In the implementation block
@property (nonatomic,readonly) char isSignedIn; 
@property (assign,nonatomic) char isAppRestricted;                                                   //@synthesize isAppRestricted=_isAppRestricted - In the implementation block
@property (nonatomic,readonly) char isLocationServicesDisabled; 
@property (nonatomic,retain) FMFClientLocation * currentLocation;                                    //@synthesize currentLocation=_currentLocation - In the implementation block
@property (nonatomic,retain) FMDistanceCalculator * distanceCalculator;                              //@synthesize distanceCalculator=_distanceCalculator - In the implementation block
@property (nonatomic,readonly) char hideLocationNotAvailable; 
@property (nonatomic,retain) NSDictionary * remoteNotificationAlertDict;                             //@synthesize remoteNotificationAlertDict=_remoteNotificationAlertDict - In the implementation block
@property (assign,nonatomic) double lastUserActivity;                                                //@synthesize lastUserActivity=_lastUserActivity - In the implementation block
@property (assign,nonatomic) char sessionExpiredWhileAppActive;                                      //@synthesize sessionExpiredWhileAppActive=_sessionExpiredWhileAppActive - In the implementation block
@property (assign,nonatomic) char forcedAuthPending; 
@property (assign,nonatomic) char didUserAuthenticateUnlocked;                                       //@synthesize didUserAuthenticateUnlocked=_didUserAuthenticateUnlocked - In the implementation block
@property (nonatomic,retain) MKMapCamera * lastCamera;                                               //@synthesize lastCamera=_lastCamera - In the implementation block
@property (nonatomic,retain) FMFSplitViewController * splitView;                                     //@synthesize splitView=_splitView - In the implementation block
@property (nonatomic,retain) CLLocationManager * locationManager;                                    //@synthesize locationManager=_locationManager - In the implementation block
@property (nonatomic,retain) NSString * apsToken;                                                    //@synthesize apsToken=_apsToken - In the implementation block
@property (assign,nonatomic) char shouldSkipNextOpenURL;                                             //@synthesize shouldSkipNextOpenURL=_shouldSkipNextOpenURL - In the implementation block
@property (assign,nonatomic) char locationManagerFailure;                                            //@synthesize locationManagerFailure=_locationManagerFailure - In the implementation block
@property (nonatomic,retain) id reachabilityNotificationToken;                                       //@synthesize reachabilityNotificationToken=_reachabilityNotificationToken - In the implementation block
@property (assign,nonatomic) char watchingCLLocation;                                                //@synthesize watchingCLLocation=_watchingCLLocation - In the implementation block
@property (assign,nonatomic) char watchingCLLocationInBackground;                                    //@synthesize watchingCLLocationInBackground=_watchingCLLocationInBackground - In the implementation block
@property (nonatomic,retain) NSArray * pushMessages;                                                 //@synthesize pushMessages=_pushMessages - In the implementation block
@property (assign,nonatomic) char smlLocServiceStatus;                                               //@synthesize smlLocServiceStatus=_smlLocServiceStatus - In the implementation block
@property (assign,nonatomic) char globalLocServiceStatus;                                            //@synthesize globalLocServiceStatus=_globalLocServiceStatus - In the implementation block
@property (assign,nonatomic) char applicationWasInitialized;                                         //@synthesize applicationWasInitialized=_applicationWasInitialized - In the implementation block
@property (assign,nonatomic) char allowedToShowSMLOffAlert;                                          //@synthesize allowedToShowSMLOffAlert=_allowedToShowSMLOffAlert - In the implementation block
@property (nonatomic,retain) FMAPSHandler * apsHandler;                                              //@synthesize apsHandler=_apsHandler - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> launchQueue;                               //@synthesize launchQueue=_launchQueue - In the implementation block
@property (assign,nonatomic) char loadedMainApplication;                                             //@synthesize loadedMainApplication=_loadedMainApplication - In the implementation block
+(id)sharedInstance;
-(FMFConsciousnessManager *)consciousnessManager;
-(void)accountDetailsDidLoad;
-(StoreController *)storeController;
-(UserAccountStore *)userAccountStore;
-(CoreDataManager *)coreDataManager;
-(FMDistanceCalculator *)distanceCalculator;
-(char)isLocationServicesDisabled;
-(ModelUpdateController *)modelUpdateController;
-(MyLocationController *)myLocationController;
-(void)showServerAlert:(id)arg1 ;
-(void)setSessionExpiredWhileAppActive:(char)arg1 ;
-(void)setSplitView:(FMFSplitViewController *)arg1 ;
-(char)isSignedIn;
-(void)setDidUserAuthenticateUnlocked:(char)arg1 ;
-(void)requestLocationManagerPermission;
-(void)resumeModelUpdates;
-(void)sendMyLocation:(id)arg1 ;
-(char)isCompactHeight;
-(FMFAddressBookController *)abController;
-(void)addressBookPreferencesDidChange:(id)arg1 ;
-(void)iCloudAccountChanged:(id)arg1 ;
-(void)showSMLOffAlert;
-(void)_testForFirstUnlock;
-(void)loadMainApplication:(id)arg1 ;
-(void)loadCalabash;
-(void)initialLaunchProcessing;
-(void)migrateFromVersion:(double)arg1 toVersion:(double)arg2 ;
-(void)setConsciousnessManager:(FMFConsciousnessManager *)arg1 ;
-(char)forcedAuthPending;
-(void)setForcedAuthPending:(char)arg1 ;
-(void)setUserAccountStore:(UserAccountStore *)arg1 ;
-(void)setStoreController:(StoreController *)arg1 ;
-(void)setModelUpdateController:(ModelUpdateController *)arg1 ;
-(void)setAbController:(FMFAddressBookController *)arg1 ;
-(void)setMyLocationController:(MyLocationController *)arg1 ;
-(void)setActionURLManager:(ActionURLManager *)arg1 ;
-(void)setCoreDataManager:(CoreDataManager *)arg1 ;
-(void)setFmfInitCommandManager:(FMFInitCommandManager *)arg1 ;
-(void)setDistanceCalculator:(FMDistanceCalculator *)arg1 ;
-(void)alertRequested:(id)arg1 ;
-(void)refreshRestrictionsState;
-(void)setShouldSkipNextOpenURL:(char)arg1 ;
-(ActionURLManager *)actionURLManager;
-(void)_handleRemoteNotification:(id)arg1 ;
-(void)backgroundAppUpdateCriteriaDidChange;
-(void)setLoadedMainApplication:(char)arg1 ;
-(char)loadedMainApplication;
-(void)validateApplicationState;
-(void)showNotSharingAlertIfRequired;
-(void)setAllowedToShowSMLOffAlert:(char)arg1 ;
-(void)userIsActive;
-(void)setApplicationWasInitialized:(char)arg1 ;
-(void)saveMapRect;
-(char)shouldSkipNextOpenURL;
-(void)offerLocationForExpiry:(unsigned)arg1 withData:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(char)applicationWasInitialized;
-(char)isAppRestricted;
-(void)setIsAppRestricted:(char)arg1 ;
-(char)locationManagerFailure;
-(void)setLocationManagerFailure:(char)arg1 ;
-(char)watchingCLLocation;
-(void)setWatchingCLLocation:(char)arg1 ;
-(char)watchingCLLocationInBackground;
-(void)showHideSetupiCloud;
-(char)globalLocServiceStatus;
-(char)smlLocServiceStatus;
-(char)allowedToShowSMLOffAlert;
-(void)setSmlLocServiceStatus:(char)arg1 ;
-(void)setGlobalLocServiceStatus:(char)arg1 ;
-(void)setApsToken:(NSString *)arg1 ;
-(void)setApsHandler:(FMAPSHandler *)arg1 ;
-(FMAPSHandler *)apsHandler;
-(char)_isRemoteNotificationsEnabledForTheApp;
-(double)lastUserActivity;
-(void)setLastUserActivity:(double)arg1 ;
-(void)_appReceivedTap:(id)arg1 ;
-(void)_checkReachability;
-(void)setReachabilityNotificationToken:(id)arg1 ;
-(id)reachabilityNotificationToken;
-(char)_isBAROff;
-(char)isSMLLocationServicesOn;
-(char)hideLocationNotAvailable;
-(void)resetLocationManagerFailure;
-(void)startWatchingCLLocation;
-(void)stopWatchingCLLocation;
-(void)disableBackgroundLocationUpdates;
-(char)isGlobalLocationServicesOn;
-(void)startListeningForFMFTaps;
-(void)stopListeningForFMFTaps;
-(id)tapContext;
-(void)suspendModelUpdates;
-(void)bringAppToFreshLaunchState;
-(char)isMeDeviceBAROff;
-(char)isInLocationHiddenState;
-(char)isPaneUp;
-(void)setLastCamera:(MKMapCamera *)arg1 ;
-(void)setStoryboard:(UIStoryboard *)arg1 ;
-(BackgroundLocateController *)backgroundLocateController;
-(void)setBackgroundLocateController:(BackgroundLocateController *)arg1 ;
-(FMFInitCommandManager *)fmfInitCommandManager;
-(NSDictionary *)remoteNotificationAlertDict;
-(void)setRemoteNotificationAlertDict:(NSDictionary *)arg1 ;
-(char)sessionExpiredWhileAppActive;
-(char)didUserAuthenticateUnlocked;
-(MKMapCamera *)lastCamera;
-(FMFSplitViewController *)splitView;
-(void)setWatchingCLLocationInBackground:(char)arg1 ;
-(void)_createQASnapshotComplete;
-(void)_createQASnapshot;
-(void)createQASnapshot;
-(void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2 ;
-(void)locationManager:(id)arg1 didUpdateLocations:(id)arg2 ;
-(UIWindow *)window;
-(id)init;
-(char)application:(id)arg1 openURL:(id)arg2 options:(id)arg3 ;
-(void)application:(id)arg1 didChangeStatusBarFrame:(CGRect)arg2 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(unsigned)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2 ;
-(char)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(void)setWindow:(UIWindow *)arg1 ;
-(void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 ;
-(void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forRemoteNotification:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2 ;
-(void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2 ;
-(UIStoryboard *)storyboard;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3 ;
-(char)isCompactWidth;
-(NSArray *)pushMessages;
-(void)setPushMessages:(NSArray *)arg1 ;
-(ServerInteractionController *)serverInteractionController;
-(void)setServerInteractionController:(ServerInteractionController *)arg1 ;
-(void)didReceiveAPSMessage:(id)arg1 ;
-(void)didReceiveAPSToken:(id)arg1 ;
-(NSString *)apsToken;
-(void)_configureLogging;
-(void)didBecomeActive;
-(FMFClientLocation *)currentLocation;
-(void)setCurrentLocation:(FMFClientLocation *)arg1 ;
-(NSObject*<OS_dispatch_queue>)launchQueue;
-(void)setLaunchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(FMNetworkMonitor *)internetReachability;
-(void)setInternetReachability:(FMNetworkMonitor *)arg1 ;
-(CLLocationManager *)locationManager;
-(void)setLocationManager:(CLLocationManager *)arg1 ;
-(id)clientContext;
-(void)locationManager:(id)arg1 didFailWithError:(id)arg2 ;
-(void)setAccount:(FMFAccount *)arg1 ;
-(FMFAccount *)account;
-(void)_startMonitoringReachability;
-(void)_stopMonitoringReachability;
-(void)preferencesChanged:(id)arg1 ;
@end

