/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:06 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FindMyFriends/FMFEntity.h>

@class NSArray, NSString, NSNumber, FMFAccount, NSSet;

@interface FMFEvent : FMFEntity {

	NSArray* sortedFriends;

}

@property (nonatomic,retain) NSString * uid; 
@property (nonatomic,retain) NSString * name; 
@property (nonatomic,retain) NSNumber * expires; 
@property (nonatomic,retain) NSNumber * createTimestamp; 
@property (nonatomic,retain) NSString * myId; 
@property (nonatomic,retain) NSNumber * lastModifiedDate; 
@property (nonatomic,retain) NSString * organizerid; 
@property (nonatomic,retain) FMFAccount * account; 
@property (nonatomic,retain) NSSet * friends; 
@property (nonatomic,retain) NSSet * futurefriends; 
@property (nonatomic,retain) NSArray * sortedFriends; 
+(id)eventWithId:(id)arg1 ;
+(id)allLocationsForEvents;
+(id)eventNameWithFallback:(id)arg1 ;
-(id)friendsSortedByDistance:(char)arg1 ;
-(int)fmfDistanceCompare:(id)arg1 ;
-(id)friendWithId:(id)arg1 ;
-(char)anyFriendHasLocation;
-(char)hasFriendWithId:(id)arg1 ;
-(void)setSortedFriends:(NSArray *)arg1 ;
-(id)sortFriendArrayByName:(id)arg1 ;
-(id)meFriend;
-(id)allFriendSortedByName:(char)arg1 includeMe:(char)arg2 ;
-(char)hasOrganizerPermissions;
-(void)resetFriendSortCache;
-(id)allFriendsSortedIncludingFutureWithoutOrganizer;
-(id)eventExpiresDateFormatted;
-(id)eventExpiresDateFormattedLowercaseDateTime;
-(id)emailsOfAcceptedFriends;
-(id)organizerAndCountOthers;
-(id)emailsOfEventFriends;
-(char)hasMaxFriendsInEvent;
-(int)expiresOn;
-(id)prettyEventNameForWidth:(float)arg1 andFont:(id)arg2 includeFuture:(char)arg3 ;
-(NSArray *)sortedFriends;
-(id)organizer;
-(void)prepareForDeletion;
@end

