/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:05 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FindMyFriends/FindMyFriends-Structs.h>
#import <FindMyFriends/FMFPerson.h>
#import <libobjc.A.dylib/NSCopying.h>

@class FMFAccount, NSString;

@interface FMFFriendRequest : FMFPerson <NSCopying>

@property (nonatomic,retain) FMFAccount * account; 
@property (nonatomic,retain) NSString * invitationFromHandle; 
@property (nonatomic,retain) NSString * invitationSentToHandle; 
@property (nonatomic,retain) NSString * uid; 
@property (nonatomic,retain) NSString * message; 
+(id)requestWithUid:(id)arg1 ;
-(id)fallbackHandles;
-(id)abSearchKey;
-(id)locationUpdateDescriptionLabel;
-(char)isRequesterAlsoAFriendOrInvitedFriend;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)location;
-(void)prepareForDeletion;
@end

