/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:05 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FindMyFriends/FMFBaseCmd.h>

@class NSString;

@interface FMFTriggerMigrationCommand : FMFBaseCmd {

	NSString* _triggerAppleId;
	NSString* _triggerPassword;

}

@property (nonatomic,copy) NSString * triggerAppleId;               //@synthesize triggerAppleId=_triggerAppleId - In the implementation block
@property (nonatomic,copy) NSString * triggerPassword;              //@synthesize triggerPassword=_triggerPassword - In the implementation block
-(id)willSucceedNotification;
-(id)willFailNotification;
-(id)didSucceedNotification;
-(id)didFailNotification;
-(void)setTriggerAppleId:(NSString *)arg1 ;
-(void)setTriggerPassword:(NSString *)arg1 ;
-(NSString *)triggerAppleId;
-(NSString *)triggerPassword;
-(id)initWithAppleId:(id)arg1 password:(id)arg2 ;
-(id)pathSuffix;
-(id)jsonBodyDictionary;
@end

