/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:06 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol UITextFieldDelegate;
@class NSString, UITextField;

@interface MapSearchBar : UIView {

	NSString* placeholder;
	UITextField* fmfSearchField;
	id<UITextFieldDelegate> fmfSearchFieldDelegate;

}

@property (nonatomic,retain) NSString * placeholder; 
@property (nonatomic,retain) UITextField * fmfSearchField; 
@property (assign,nonatomic,__weak) id<UITextFieldDelegate> fmfSearchFieldDelegate; 
-(UITextField *)fmfSearchField;
-(void)setFmfSearchFieldDelegate:(id<UITextFieldDelegate>)arg1 ;
-(void)setFmfSearchField:(UITextField *)arg1 ;
-(id<UITextFieldDelegate>)fmfSearchFieldDelegate;
-(void)awakeFromNib;
-(void)setPlaceholder:(NSString *)arg1 ;
-(NSString *)placeholder;
@end

