/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:06 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class FMFEventFriend, FMFEvent;

@interface RequestsListener : NSObject {

	FMFEventFriend* _eventFriendForActionSheet;
	FMFEvent* _eventForActionSheet;
	/*^block*/id _doneHandler;
	/*^block*/id _cancelHandler;

}

@property (nonatomic,retain) FMFEventFriend * eventFriendForActionSheet;              //@synthesize eventFriendForActionSheet=_eventFriendForActionSheet - In the implementation block
@property (nonatomic,retain) FMFEvent * eventForActionSheet;                          //@synthesize eventForActionSheet=_eventForActionSheet - In the implementation block
@property (nonatomic,copy) id doneHandler;                                            //@synthesize doneHandler=_doneHandler - In the implementation block
@property (nonatomic,copy) id cancelHandler;                                          //@synthesize cancelHandler=_cancelHandler - In the implementation block
+(void)startListening;
-(void)askToFollowTapped:(id)arg1 ;
-(void)reorderFavorites;
-(void)acceptTapped:(id)arg1 ;
-(void)declineTapped:(id)arg1 ;
-(void)favoritesTapped:(id)arg1 ;
-(void)removeTapped:(id)arg1 ;
-(void)shareLocationTapped:(id)arg1 ;
-(void)stopSharingLocationTapped:(id)arg1 ;
-(void)respondNotNowForOfferLocation:(id)arg1 ;
-(void)respondToInvite:(id)arg1 accepted:(char)arg2 ;
-(void)deleteFromCoreData:(id)arg1 ;
-(void)showAlertForTemporaryFriendRemoval:(id)arg1 forViewController:(id)arg2 ;
-(void)displayMessageIfAlsoInEvent:(id)arg1 ;
-(void)runRemoveFriendCommand:(id)arg1 ;
-(void)deleteEventFriend:(id)arg1 ;
-(FMFEventFriend *)eventFriendForActionSheet;
-(void)setEventFriendForActionSheet:(FMFEventFriend *)arg1 ;
-(FMFEvent *)eventForActionSheet;
-(void)setEventForActionSheet:(FMFEvent *)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setCancelHandler:(id)arg1 ;
-(id)cancelHandler;
-(void)setDoneHandler:(id)arg1 ;
-(id)doneHandler;
@end

