/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:01 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Diagnostics/DAModel.h>

@class NSString, NSNumber;

@interface DAClientStatus : DAModel {

	NSString* _clientStatus;
	NSString* _currentTest;
	NSNumber* _progress;

}

@property (nonatomic,copy) NSString * clientStatus;              //@synthesize clientStatus=_clientStatus - In the implementation block
@property (nonatomic,copy) NSString * currentTest;               //@synthesize currentTest=_currentTest - In the implementation block
@property (nonatomic,retain) NSNumber * progress;                //@synthesize progress=_progress - In the implementation block
-(NSString *)clientStatus;
-(void)setClientStatus:(NSString *)arg1 ;
-(id)dictionary;
-(void)setProgress:(NSNumber *)arg1 ;
-(NSString *)currentTest;
-(NSNumber *)progress;
-(void)setCurrentTest:(NSString *)arg1 ;
@end

