/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:01 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@protocol DATermsConditionsViewControllerDelegate, DADisplayAppleWatchOnlyDelegate;
@class UITextView, DADeviceManager, NSString;

@interface DATermsConditionsViewController : UIViewController {

	id<DATermsConditionsViewControllerDelegate> _delegate;
	id<DADisplayAppleWatchOnlyDelegate> _appleWatchOnlyDelegate;
	UITextView* _termsText;
	DADeviceManager* _deviceManager;
	NSString* _secondaryConsentMessage;

}

@property (assign,nonatomic,__weak) id<DATermsConditionsViewControllerDelegate> delegate;                    //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<DADisplayAppleWatchOnlyDelegate> appleWatchOnlyDelegate;              //@synthesize appleWatchOnlyDelegate=_appleWatchOnlyDelegate - In the implementation block
@property (nonatomic,retain) UITextView * termsText;                                                         //@synthesize termsText=_termsText - In the implementation block
@property (nonatomic,retain) DADeviceManager * deviceManager;                                                //@synthesize deviceManager=_deviceManager - In the implementation block
@property (nonatomic,retain) NSString * secondaryConsentMessage;                                             //@synthesize secondaryConsentMessage=_secondaryConsentMessage - In the implementation block
-(void)setAppleWatchOnlyDelegate:(id<DADisplayAppleWatchOnlyDelegate>)arg1 ;
-(void)continueAction:(id)arg1 ;
-(id)consentMessage;
-(id<DADisplayAppleWatchOnlyDelegate>)appleWatchOnlyDelegate;
-(NSString *)secondaryConsentMessage;
-(void)setSecondaryConsentMessage:(NSString *)arg1 ;
-(void)cancelAction:(id)arg1 ;
-(void)setDelegate:(id<DATermsConditionsViewControllerDelegate>)arg1 ;
-(id<DATermsConditionsViewControllerDelegate>)delegate;
-(void)viewDidLoad;
-(void)setTermsText:(UITextView *)arg1 ;
-(UITextView *)termsText;
-(DADeviceManager *)deviceManager;
-(void)setDeviceManager:(DADeviceManager *)arg1 ;
@end

