/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:01 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class DATestOperation, DAComponentManager, NSDictionary, NSArray, NSOperationQueue;

@interface DATestManager : NSObject {

	DATestOperation* _currentTest;
	DAComponentManager* _componentManager;
	NSDictionary* _tests;
	NSArray* _ketsTests;
	NSOperationQueue* _queue;

}

@property (nonatomic,retain) DATestOperation * currentTest;                      //@synthesize currentTest=_currentTest - In the implementation block
@property (nonatomic,retain) DAComponentManager * componentManager;              //@synthesize componentManager=_componentManager - In the implementation block
@property (nonatomic,retain) NSDictionary * tests;                               //@synthesize tests=_tests - In the implementation block
@property (nonatomic,retain) NSArray * ketsTests;                                //@synthesize ketsTests=_ketsTests - In the implementation block
@property (nonatomic,retain) NSOperationQueue * queue;                           //@synthesize queue=_queue - In the implementation block
-(NSDictionary *)tests;
-(DAComponentManager *)componentManager;
-(void)setComponentManager:(DAComponentManager *)arg1 ;
-(NSArray *)ketsTests;
-(id)initWithComponentManager:(id)arg1 ;
-(char)startTest:(id)arg1 data:(id)arg2 navigationController:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)cancelTest;
-(void)setTests:(NSDictionary *)arg1 ;
-(void)setKetsTests:(NSArray *)arg1 ;
-(NSOperationQueue *)queue;
-(void)setQueue:(NSOperationQueue *)arg1 ;
-(id)init;
-(DATestOperation *)currentTest;
-(void)setCurrentTest:(DATestOperation *)arg1 ;
@end

