/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:01 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Diagnostics/Diagnostics-Structs.h>
#import <Diagnostics/DATestViewController.h>
#import <Diagnostics/DATouchAccuracyTargetDelegate.h>

@class NSArray, NSTimer, DATouchAccuracyTarget, NSMutableArray, NSString;

@interface DATouchAccuracyViewController : DATestViewController <DATouchAccuracyTargetDelegate> {

	float _blockWidth;
	float _blockHeight;
	NSArray* _positions;
	int _noInputTimeout;
	int _partialInputTimeout;
	NSTimer* _timeoutTimer;
	DATouchAccuracyTarget* _targetView;
	int _numberOfBlocks;
	unsigned _touchStatus;
	int _goodTaps;
	int _badTaps;
	NSMutableArray* _allResults;
	CGPoint _badTouchLocation;

}

@property (assign,nonatomic) float blockWidth;                                //@synthesize blockWidth=_blockWidth - In the implementation block
@property (assign,nonatomic) float blockHeight;                               //@synthesize blockHeight=_blockHeight - In the implementation block
@property (nonatomic,retain) NSArray * positions;                             //@synthesize positions=_positions - In the implementation block
@property (assign,nonatomic) int noInputTimeout;                              //@synthesize noInputTimeout=_noInputTimeout - In the implementation block
@property (assign,nonatomic) int partialInputTimeout;                         //@synthesize partialInputTimeout=_partialInputTimeout - In the implementation block
@property (nonatomic,retain) NSTimer * timeoutTimer;                          //@synthesize timeoutTimer=_timeoutTimer - In the implementation block
@property (nonatomic,retain) DATouchAccuracyTarget * targetView;              //@synthesize targetView=_targetView - In the implementation block
@property (assign,nonatomic) int numberOfBlocks;                              //@synthesize numberOfBlocks=_numberOfBlocks - In the implementation block
@property (assign,nonatomic) unsigned touchStatus;                            //@synthesize touchStatus=_touchStatus - In the implementation block
@property (assign,nonatomic) int goodTaps;                                    //@synthesize goodTaps=_goodTaps - In the implementation block
@property (assign,nonatomic) int badTaps;                                     //@synthesize badTaps=_badTaps - In the implementation block
@property (assign,nonatomic) CGPoint badTouchLocation;                        //@synthesize badTouchLocation=_badTouchLocation - In the implementation block
@property (nonatomic,retain) NSMutableArray * allResults;                     //@synthesize allResults=_allResults - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTest:(id)arg1 fullScreen:(char)arg2 ;
-(char)parameterize:(id)arg1 ;
-(NSMutableArray *)allResults;
-(void)setAllResults:(NSMutableArray *)arg1 ;
-(void)endTestWithStatusCode:(id)arg1 ;
-(void)shufflePositions;
-(void)setPositions:(NSArray *)arg1 ;
-(NSArray *)positions;
-(void)setNumberOfBlocks:(int)arg1 ;
-(int)noInputTimeout;
-(void)noInputTimedOut;
-(int)totalTaps;
-(int)numberOfBlocks;
-(void)placeNextTarget:(id)arg1 ;
-(int)goodTaps;
-(int)badTaps;
-(unsigned)touchStatus;
-(void)setTouchStatus:(unsigned)arg1 ;
-(void)setGoodTaps:(int)arg1 ;
-(void)checkForNextTarget;
-(void)setBadTouchLocation:(CGPoint)arg1 ;
-(void)endTouch;
-(void)setBadTaps:(int)arg1 ;
-(CGPoint)badTouchLocation;
-(int)partialInputTimeout;
-(void)targetBeganTap;
-(void)targetFinishedTapAtLocation:(CGPoint)arg1 ;
-(void)setNoInputTimeout:(int)arg1 ;
-(void)setPartialInputTimeout:(int)arg1 ;
-(float)blockWidth;
-(void)setBlockWidth:(float)arg1 ;
-(float)blockHeight;
-(void)setBlockHeight:(float)arg1 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)viewDidLoad;
-(void)viewDidDisappear:(char)arg1 ;
-(DATouchAccuracyTarget *)targetView;
-(void)setTargetView:(DATouchAccuracyTarget *)arg1 ;
-(void)setTimeoutTimer:(NSTimer *)arg1 ;
-(NSTimer *)timeoutTimer;
-(void)timedOut;
-(void)setupView;
@end

