/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:58 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Setup/BuddyLandingPageController.h>

@interface BuddyFinishedController : BuddyLandingPageController
-(void)loadActualView;
-(void)viewDidAppear:(char)arg1 ;
@end

