/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:55 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMGridCollectionViewCell.h>

@class UIImageView, UILabel;

@interface IMGridCollectionViewDetailCell : IMGridCollectionViewCell {

	UIImageView* _currentlyPlayingIcon;
	UILabel* _detailText;

}

@property (nonatomic,retain) UILabel * detailText;                              //@synthesize detailText=_detailText - In the implementation block
@property (nonatomic,readonly) UIImageView * currentlyPlayingIcon;              //@synthesize currentlyPlayingIcon=_currentlyPlayingIcon - In the implementation block
@property (assign,nonatomic) char isCurrentlyPlaying; 
-(void)setEnlargedSelectedState:(char)arg1 ;
-(CGRect)titleRectForBounds:(CGRect)arg1 ;
-(id)nowPlayingListItemIcon;
-(id)nowPlayingListItemIconSelected;
-(UIImageView *)currentlyPlayingIcon;
-(CGRect)detailRectForBounds:(CGRect)arg1 ;
-(void)setIsCurrentlyPlaying:(char)arg1 ;
-(char)isCurrentlyPlaying;
-(void)setDetailText:(UILabel *)arg1 ;
-(UILabel *)detailText;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)prepareForReuse;
@end

