/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:56 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UILabel.h>

@interface IMLabel : UILabel {

	UIOffset _offset;

}

@property (assign,nonatomic) UIOffset offset;              //@synthesize offset=_offset - In the implementation block
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setOffset:(UIOffset)arg1 ;
-(UIOffset)offset;
-(void)drawTextInRect:(CGRect)arg1 ;
@end

