/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:50 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIActivityIndicatorView.h>

@interface MTActivityIndicatorView : UIActivityIndicatorView {

	int _style;

}

@property (assign,nonatomic) int style;              //@synthesize style=_style - In the implementation block
-(id)initWithStyle:(int)arg1 ;
-(int)style;
-(void)tintColorDidChange;
-(void)setStyle:(int)arg1 ;
-(id)initWithActivityIndicatorStyle:(int)arg1 ;
@end

