/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:53 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/MTEpisodeListViewController.h>

@class NSMutableOrderedSet, NSString;

@interface MTBasePlaylistEpisodeListViewController : MTEpisodeListViewController {

	NSMutableOrderedSet* _items;
	char _editable;
	NSString* _playlistUuid;
	NSString* _settingsUuid;

}

@property (nonatomic,retain) NSString * playlistUuid;                      //@synthesize playlistUuid=_playlistUuid - In the implementation block
@property (nonatomic,retain) NSString * settingsUuid;                      //@synthesize settingsUuid=_settingsUuid - In the implementation block
@property (assign,getter=isEditable,nonatomic) char editable;              //@synthesize editable=_editable - In the implementation block
-(id)metricsName;
-(void)playEpisodeAtIndexPath:(id)arg1 ;
-(void)markSelectedItems:(char)arg1 ;
-(void)markSelectedItemsAsSaved:(char)arg1 ;
-(void)setSettingsUuid:(NSString *)arg1 ;
-(void)setPlaylistUuid:(NSString *)arg1 ;
-(void)removeSelectedItems:(id)arg1 ;
-(NSString *)playlistUuid;
-(id)metricDataSource;
-(void)_loadItems;
-(void)markEpisodesAtIndexPaths:(id)arg1 asSaved:(char)arg2 ;
-(unsigned)indexOfUuid:(id)arg1 ;
-(void)updateTableWithEpisodes:(id)arg1 originalItems:(id)arg2 animated:(char)arg3 section:(int)arg4 ;
-(NSString *)settingsUuid;
-(void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned)arg4 newIndexPath:(id)arg5 ;
-(void)controllerDidChangeContent:(id)arg1 ;
-(id)objectAtIndexPath:(id)arg1 ;
-(id)indexPathForObject:(id)arg1 ;
-(void)reloadData;
-(void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(int)arg3 ;
-(int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(char)isEditable;
-(id)items;
-(void)setEditable:(char)arg1 ;
-(id)initWithPlaylist:(id)arg1 ;
-(id)initWithPredicate:(id)arg1 ;
@end

