/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:50 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/MTSingleton.h>

@class NSCache;

@interface MTEpisodeCollectionViewCellHeightCache : MTSingleton {

	NSCache* _cachedHeights;

}
-(void)sizeCategoryChanged:(id)arg1 ;
-(id)_keyForWidth:(float)arg1 style:(unsigned)arg2 ;
-(float)cachedHeightForWidth:(float)arg1 style:(unsigned)arg2 ;
-(void)addCachedHeight:(float)arg1 forWidth:(float)arg2 style:(unsigned)arg3 ;
-(void)dealloc;
-(id)init;
@end

