/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:50 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMMediaRemoteController.h>

@interface MTMediaRemoteController : IMMediaRemoteController
-(int)remoteSetPlaybackQueueCommand:(id)arg1 ;
-(long)findIndexOfCommand:(unsigned)arg1 inArray:(CFArrayRef)arg2 ;
-(int)remotePlay:(id)arg1 ;
-(id)initWithPlayer:(id)arg1 ;
-(void)dealloc;
-(CFArrayRef)copySupportedCommands;
@end

