/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:51 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/MusicTabBarController.h>
#import <Podcasts/MTStoreTabControllerSizeDelegate.h>
#import <Podcasts/MTTabBarLastSelectionProtocol.h>

@class UIViewController, UIButton, NSString;

@interface MTMusicTabController : MusicTabBarController <MTStoreTabControllerSizeDelegate, MTTabBarLastSelectionProtocol> {

	UIViewController* _lastSelectedViewController;
	UIButton* _nowPlayingButton;

}

@property (assign,nonatomic,__weak) UIViewController * lastSelectedViewController;              //@synthesize lastSelectedViewController=_lastSelectedViewController - In the implementation block
@property (nonatomic,retain) UIButton * nowPlayingButton;                                       //@synthesize nowPlayingButton=_nowPlayingButton - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)_shouldForwardViewWillTransitionToSize;
-(id)metricsName;
-(void)switchToLastSelectedViewController;
-(void)setLastSelectedViewController:(UIViewController *)arg1 ;
-(UIViewController *)lastSelectedViewController;
-(void)setNowPlayingButton:(UIButton *)arg1 ;
-(id)init;
-(void)traitCollectionDidChange:(id)arg1 ;
-(int)preferredStatusBarStyle;
-(unsigned)supportedInterfaceOrientations;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)setSelectedViewController:(id)arg1 ;
-(UIButton *)nowPlayingButton;
@end

