/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:52 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/MTEpisodeListViewController.h>

@class NSMutableSet, UIButton, UIBarButtonItem, NSSet;

@interface MTOTGAddEpisodeViewController : MTEpisodeListViewController {

	NSMutableSet* _selectedUuids;
	UIButton* _selectAllButton;
	UIButton* _selectNoneButton;
	UIBarButtonItem* _doneItem;
	UIBarButtonItem* _selectAllButtonItem;
	UIBarButtonItem* _selectNoneButtonItem;
	NSSet* _existingUuids;

}

@property (nonatomic,copy) NSSet * selectedUuids; 
@property (nonatomic,copy) NSSet * existingUuids;                                                    //@synthesize existingUuids=_existingUuids - In the implementation block
@property (assign,nonatomic,__weak) id<MTOTGEpisodeAddViewControllerDelegate> delegate; 
-(id)newCellInstanceWithReuseIdentifier:(id)arg1 ;
-(void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3 ;
-(id)emptyListMessage;
-(id)toolbarButtonItems;
-(void)setExistingUuids:(NSSet *)arg1 ;
-(void)setSelectedUuids:(NSSet *)arg1 ;
-(NSSet *)selectedUuids;
-(void)selectNone:(id)arg1 ;
-(id)selectAllButton;
-(id)selectNoneButton;
-(id)selectAllButtonItem;
-(id)selectNoneButtonItem;
-(id)doneItem;
-(NSSet *)existingUuids;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(char)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)selectAll:(id)arg1 ;
-(void)updateButtons;
-(void)done:(id)arg1 ;
-(id)rightButtonItems;
@end

