/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:52 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/MTBasePlaylistEpisodeListViewController.h>
#import <Podcasts/MTSourceListDelegate.h>
#import <Podcasts/MTOTGEpisodeAddViewControllerDelegate.h>

@class MTOTGPlaylistDetailListAddButton, UIButton, UIBarButtonItem, MTOTGAddPodcastViewController, NSMutableSet, MTAllPropertyChangesQueryObserver, MTUuidQueryObserver, NSString;

@interface MTOTGPlaylistEpisodeListViewController : MTBasePlaylistEpisodeListViewController <MTSourceListDelegate, MTOTGEpisodeAddViewControllerDelegate> {

	MTOTGPlaylistDetailListAddButton* _addButton;
	UIButton* _clearButton;
	UIButton* _downloadButton;
	UIBarButtonItem* _clearButtonItem;
	UIBarButtonItem* _addButtonItem;
	MTOTGAddPodcastViewController* _addSheet;
	NSMutableSet* _addedEpisodes;
	MTAllPropertyChangesQueryObserver* _downloadedQuery;
	char _downloadButtonEnabled;
	char _downloadsAvailable;
	MTUuidQueryObserver* _queryObserver;

}

@property (assign,nonatomic) char downloadButtonEnabled;                       //@synthesize downloadButtonEnabled=_downloadButtonEnabled - In the implementation block
@property (assign,nonatomic) char downloadsAvailable;                          //@synthesize downloadsAvailable=_downloadsAvailable - In the implementation block
@property (nonatomic,retain) MTUuidQueryObserver * queryObserver;              //@synthesize queryObserver=_queryObserver - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)sourceList:(id)arg1 didSelectItemUuid:(id)arg2 atIndexPath:(id)arg3 ;
-(void)sourceList:(id)arg1 didUpdateSelectedItemUuid:(id)arg2 ;
-(void)transitionToState:(int)arg1 animated:(char)arg2 ;
-(id)emptyListMessage;
-(id)downloadButton;
-(id)toolbarButtonItems;
-(void)downloadAll:(id)arg1 ;
-(void)setQueryObserver:(MTUuidQueryObserver *)arg1 ;
-(MTUuidQueryObserver *)queryObserver;
-(void)setDownloadButtonEnabled:(char)arg1 ;
-(void)setDownloadsAvailable:(char)arg1 ;
-(void)updateDownloadButtonState;
-(char)downloadButtonEnabled;
-(char)downloadsAvailable;
-(id)addButtonItem;
-(id)clearButtonItem;
-(void)clearPlaylist;
-(void)otgEpisodeAddViewControllerPressedDone:(id)arg1 ;
-(void)otgEpisodeAddViewControllerDidChangeSelection:(id)arg1 ;
-(id)addButton;
-(void)add:(id)arg1 ;
-(char)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2 ;
-(char)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)setEditing:(char)arg1 animated:(char)arg2 ;
-(void)viewDidLoad;
-(void)done:(id)arg1 ;
-(void)clear:(id)arg1 ;
-(id)footerView;
-(id)clearButton;
-(void)cancel:(id)arg1 ;
@end

