/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:51 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UICollectionReusableView.h>

@class UIView;

@interface MTPodcastReusableHeaderView : UICollectionReusableView {

	UIView* _headerView;

}

@property (nonatomic,retain) UIView * headerView;              //@synthesize headerView=_headerView - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(UIView *)headerView;
-(void)setHeaderView:(UIView *)arg1 ;
@end

