/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:52 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/MTSetting.h>

@class MTRadioGroupDescription;

@interface MTRadioButtonSetting : MTSetting {

	MTRadioGroupDescription* _radioGroup;

}

@property (nonatomic,retain) MTRadioGroupDescription * radioGroup;              //@synthesize radioGroup=_radioGroup - In the implementation block
-(MTRadioGroupDescription *)radioGroup;
-(void)setRadioGroup:(MTRadioGroupDescription *)arg1 ;
@end

