/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:51 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <libobjc.A.dylib/RadiosPreferencesDelegate.h>

@class ITMReachability, NSHashTable, RadiosPreferences;

@interface MTReachability : NSObject <RadiosPreferencesDelegate> {

	char _airplaneModeEnabled;
	char _globalCellularEnabled;
	char _reachable;
	int _networkStatus;
	ITMReachability* _reachability;
	NSHashTable* _callbacks;
	RadiosPreferences* _radiosPreferences;

}

@property (getter=isAirplaneModeEnabled,nonatomic,readonly) char airplaneModeEnabled;                  //@synthesize airplaneModeEnabled=_airplaneModeEnabled - In the implementation block
@property (getter=isGlobalCellularEnabled,nonatomic,readonly) char globalCellularEnabled;              //@synthesize globalCellularEnabled=_globalCellularEnabled - In the implementation block
@property (assign,getter=isReachable,nonatomic) char reachable;                                        //@synthesize reachable=_reachable - In the implementation block
@property (assign,nonatomic) int networkStatus;                                                        //@synthesize networkStatus=_networkStatus - In the implementation block
@property (nonatomic,retain) ITMReachability * reachability;                                           //@synthesize reachability=_reachability - In the implementation block
@property (nonatomic,retain) NSHashTable * callbacks;                                                  //@synthesize callbacks=_callbacks - In the implementation block
@property (nonatomic,retain) RadiosPreferences * radiosPreferences;                                    //@synthesize radiosPreferences=_radiosPreferences - In the implementation block
+(id)sharedInstance;
+(id)allocWithZone:(NSZone*)arg1 ;
-(char)showInternetUnreachableDialog;
-(unsigned)reasonForNoInternet;
-(int)networkStatus;
-(id)reasonTextForNoInternet;
-(char)isGlobalCellularEnabled;
-(char)showInternetUnreachableDialogWithAcknowledmentBlock:(/*^block*/id)arg1 ;
-(void)_applicationWillForeground;
-(void)_updateAirplaneMode;
-(void)_updateGlobalCellular;
-(void)setNetworkStatus:(int)arg1 ;
-(void)_showAlertForInternetUnavailableReason:(unsigned)arg1 completion:(/*^block*/id)arg2 ;
-(void)setRadiosPreferences:(RadiosPreferences *)arg1 ;
-(NSHashTable *)callbacks;
-(void)dealloc;
-(id)init;
-(id)copy;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(void)setCallbacks:(NSHashTable *)arg1 ;
-(char)isAirplaneModeEnabled;
-(void)setReachable:(char)arg1 ;
-(void)_updateReachability;
-(ITMReachability *)reachability;
-(void)setReachability:(ITMReachability *)arg1 ;
-(void)airplaneModeChanged;
-(char)isReachable;
-(RadiosPreferences *)radiosPreferences;
@end

