/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:52 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSString, MTSettingsGroup;

@interface MTSetting : NSObject {

	char _enabled;
	NSDictionary* _userInfo;
	int _type;
	NSString* _identifier;
	id _value;
	/*^block*/id _changeHandler;
	NSString* _title;
	/*^block*/id _generator;
	MTSettingsGroup* _group;

}

@property (nonatomic,retain) NSDictionary * userInfo;                     //@synthesize userInfo=_userInfo - In the implementation block
@property (assign,nonatomic) int type;                                    //@synthesize type=_type - In the implementation block
@property (nonatomic,copy) NSString * identifier;                         //@synthesize identifier=_identifier - In the implementation block
@property (assign,nonatomic) char enabled;                                //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic,retain) id value;                                    //@synthesize value=_value - In the implementation block
@property (nonatomic,copy) id changeHandler;                              //@synthesize changeHandler=_changeHandler - In the implementation block
@property (nonatomic,copy) NSString * title;                              //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) id generator;                                  //@synthesize generator=_generator - In the implementation block
@property (assign,nonatomic,__weak) MTSettingsGroup * group;              //@synthesize group=_group - In the implementation block
+(id)optionSettingWithTitle:(id)arg1 headerTitle:(id)arg2 initialValue:(unsigned)arg3 optionDescription:(id)arg4 identifier:(id)arg5 changeHandler:(/*^block*/id)arg6 ;
+(id)radioOptionWithTitle:(id)arg1 radioGroup:(id)arg2 value:(unsigned)arg3 identifier:(id)arg4 ;
+(id)switchSettingWithTitle:(id)arg1 initialValue:(char)arg2 identifier:(id)arg3 changeHandler:(/*^block*/id)arg4 ;
+(id)buttonSettingWithTitle:(id)arg1 detailText:(id)arg2 identifier:(id)arg3 changeHandler:(/*^block*/id)arg4 ;
+(id)buttonSettingWithTitle:(id)arg1 identifier:(id)arg2 changeHandler:(/*^block*/id)arg3 ;
+(id)textSettingWithInitialValue:(id)arg1 placeholder:(id)arg2 identifier:(id)arg3 changeHandler:(/*^block*/id)arg4 ;
+(id)drilldownSettingWithTitle:(id)arg1 valueLabel:(id)arg2 identifier:(id)arg3 viewControllerGenerator:(/*^block*/id)arg4 ;
+(id)optionSettingWithTitle:(id)arg1 initialValue:(unsigned)arg2 optionDescription:(id)arg3 identifier:(id)arg4 changeHandler:(/*^block*/id)arg5 ;
-(char)enabled;
-(id)init;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)identifier;
-(void)setType:(int)arg1 ;
-(int)type;
-(NSString *)title;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(void)setEnabled:(char)arg1 ;
-(id)value;
-(void)setValue:(id)arg1 ;
-(NSDictionary *)userInfo;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setGroup:(MTSettingsGroup *)arg1 ;
-(MTSettingsGroup *)group;
-(void)setGenerator:(id)arg1 ;
-(void)setChangeHandler:(id)arg1 ;
-(id)changeHandler;
-(id)generator;
@end

