/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:50 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MPUFoundation/MPUFormattingUtilities.h>

@interface MusicFormattingUtilities : MPUFormattingUtilities
+(id)formattedStringWithSongsCount:(unsigned)arg1 ;
+(id)formattedStringWithAlbumsCount:(unsigned)arg1 songsCount:(unsigned)arg2 ;
@end

