/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:52 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/MusicJSNativeViewController.h>
#import <Podcasts/MusicJSNowPlayingViewController.h>

@protocol MusicJSNowPlayingNativeViewControllerDelegate;
@class IKJSNavigationDocument;

@interface MusicJSNowPlayingNativeViewController : MusicJSNativeViewController <MusicJSNowPlayingViewController> {

	id<MusicJSNowPlayingNativeViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MusicJSNowPlayingNativeViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) IKJSNavigationDocument * navigationDocument; 
-(void)setDelegate:(id<MusicJSNowPlayingNativeViewControllerDelegate>)arg1 ;
-(id<MusicJSNowPlayingNativeViewControllerDelegate>)delegate;
-(id)nativeViewIdentifier;
@end

