/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:52 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>
#import <Podcasts/MusicPlaybackProgressScrubbing.h>

@protocol MusicPlaybackProgressScrubberDelegate;
@class UIView, NSString;

@interface MusicMiniPlayerPlaybackProgressView : UIView <MusicPlaybackProgressScrubbing> {

	char _alwaysLive;
	double _currentTime;
	double _currentTimeSetTimeInterval;
	UIView* _minimumTrackView;
	char _needsAnimationUpdate;
	CGSize _previousKnownSize;
	float _rate;
	double _totalDuration;
	id<MusicPlaybackProgressScrubberDelegate> _scrubberDelegate;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,getter=isAlwaysLive,nonatomic) char alwaysLive; 
@property (nonatomic,readonly) int currentScrubSpeed; 
@property (assign,nonatomic,__weak) id<MusicPlaybackProgressScrubberDelegate> scrubberDelegate;              //@synthesize scrubberDelegate=_scrubberDelegate - In the implementation block
@property (nonatomic,readonly) double effectiveCurrentTime; 
@property (assign,nonatomic) float rate; 
@property (assign,getter=isScrubbingEnabled,nonatomic) char scrubbingEnabled; 
@property (assign,nonatomic) double totalDuration; 
@property (assign,nonatomic) double loadedDuration; 
-(double)loadedDuration;
-(void)setLoadedDuration:(double)arg1 ;
-(int)currentScrubSpeed;
-(void)setCurrentTime:(double)arg1 ;
-(id<MusicPlaybackProgressScrubberDelegate>)scrubberDelegate;
-(void)setScrubberDelegate:(id<MusicPlaybackProgressScrubberDelegate>)arg1 ;
-(float)rate;
-(char)_setCurrentTime:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)didMoveToWindow;
-(void)layoutSubviews;
-(void)tintColorDidChange;
-(CGRect)trackRectForBounds:(CGRect)arg1 ;
-(void)_setNeedsAnimationUpdate;
-(void)_updateAnimations;
-(double)effectiveCurrentTime;
-(float)_valueForTime:(double)arg1 ;
-(void)_layoutTrackViewsForValue:(float)arg1 ;
-(void)_removeAllTrackAnimations;
-(void)cancelScrubbing;
-(void)setAlwaysLive:(char)arg1 ;
-(char)isScrubbingEnabled;
-(void)setScrubbingEnabled:(char)arg1 ;
-(double)totalDuration;
-(void)setTotalDuration:(double)arg1 ;
-(void)setRate:(float)arg1 ;
-(char)isAlwaysLive;
-(void)_applicationWillEnterForegroundNotification:(id)arg1 ;
@end

