/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:13:04 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/WebSheet.app/WebSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <WebKitLegacy/WebDefaultPolicyDelegate.h>

@class UIWebView;

@interface WebSheetPolicyDelegate : WebDefaultPolicyDelegate {

	UIWebView* _webView;

}

@property (assign,nonatomic) UIWebView * webView;              //@synthesize webView=_webView - In the implementation block
-(UIWebView *)webView;
-(void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5 ;
-(void)webView:(id)arg1 decidePolicyForNewWindowAction:(id)arg2 request:(id)arg3 newFrameName:(id)arg4 decisionListener:(id)arg5 ;
-(void)webView:(id)arg1 decidePolicyForMIMEType:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5 ;
-(void)setWebView:(UIWebView *)arg1 ;
-(id)initWithWebView:(id)arg1 ;
@end

