/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:33 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@interface AudioSettingsTableViewCell : UITableViewCell {

	char _cellEnabled;
	float _textIndentation;
	char _checked;

}

@property (assign,nonatomic) char cellEnabled;                   //@synthesize cellEnabled=_cellEnabled - In the implementation block
@property (assign,nonatomic) float textIndentation;              //@synthesize textIndentation=_textIndentation - In the implementation block
@property (assign,nonatomic) char checked;                       //@synthesize checked=_checked - In the implementation block
-(void)setTextIndentation:(float)arg1 ;
-(float)textIndentation;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)setChecked:(char)arg1 ;
-(char)checked;
-(void)setCellEnabled:(char)arg1 ;
-(char)cellEnabled;
@end

