/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:26 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/CollectionsTableViewController.h>
#import <UIKit/UINavigationControllerDelegate.h>
#import <Maps/BookmarkViewControllerDelegate.h>

@protocol CollectionsViewControllerDelegate;
@class EditBookmarkViewController, UIBarButtonItem, MSPOngoingFetchRequest, NSMutableArray, NSIndexPath, NSString;

@interface BookmarksViewController : CollectionsTableViewController <UINavigationControllerDelegate, BookmarkViewControllerDelegate> {

	EditBookmarkViewController* _editController;
	UIBarButtonItem* _doneButtonItem;
	int _searchType;
	char _isEditingBookmark;
	id<CollectionsViewControllerDelegate> _collectionsViewControllerDelegate;
	MSPOngoingFetchRequest* _actualFavorites;
	NSMutableArray* _shownFavorites;
	NSIndexPath* _editIndexPath;

}

@property (assign,nonatomic,__weak) id<CollectionsViewControllerDelegate> collectionsViewControllerDelegate;              //@synthesize collectionsViewControllerDelegate=_collectionsViewControllerDelegate - In the implementation block
@property (assign,nonatomic) int searchType;                                                                              //@synthesize searchType=_searchType - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * doneButtonItem;                                                            //@synthesize doneButtonItem=_doneButtonItem - In the implementation block
@property (nonatomic,retain) NSIndexPath * editIndexPath;                                                                 //@synthesize editIndexPath=_editIndexPath - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)dataSourceChangedNotification;
+(id)title;
-(void)searchWithType:(int)arg1 ;
-(void)view:(id)arg1 didDisappear:(char)arg2 ;
-(void)setEditIndexPath:(NSIndexPath *)arg1 ;
-(NSIndexPath *)editIndexPath;
-(void)setCollectionsViewControllerDelegate:(id<CollectionsViewControllerDelegate>)arg1 ;
-(id<CollectionsViewControllerDelegate>)collectionsViewControllerDelegate;
-(void)_maps_backgroundCompositionStyleOverrideDidChange;
-(char)_canEditIndexPath:(id)arg1 inTableView:(id)arg2 ;
-(id)editControllerWithBookmark:(id)arg1 ;
-(void)view:(id)arg1 willDisappear:(char)arg2 ;
-(void)_handleSelectRow:(id)arg1 ;
-(void)updateBookmarkWithEditController:(id)arg1 ;
-(void)_replaceBookmark:(id)arg1 withBookmark:(id)arg2 ;
-(void)_updateEditButtonEnabled;
-(void)_removeBookmarkAtIndex:(unsigned)arg1 ;
-(void)setSearchType:(int)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(char)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(char)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(id)initWithStyle:(int)arg1 ;
-(void)setEditing:(char)arg1 animated:(char)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewWillDisappear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(UIBarButtonItem *)doneButtonItem;
-(void)setDoneButtonItem:(UIBarButtonItem *)arg1 ;
-(void)_addBookmark:(id)arg1 ;
-(int)searchType;
-(void)_moveBookmarkAtIndex:(unsigned)arg1 toIndex:(unsigned)arg2 ;
@end

