/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:27 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MapsChromeModeController, SearchResultsListViewControllerDelegateQuickActionMenuPresenterDelegate;
#import <Maps/Maps-Structs.h>
@class MainChromeViewController, SearchResultsListViewController, BrowseSplitView, UITransitionView, SearchResult, NSArray;

@interface BrowseSplitViewController : NSObject {

	MainChromeViewController* _mainChrome;
	id<MapsChromeModeController> _parentMode;
	SearchResultsListViewController* _searchResultsListViewController;
	BrowseSplitView* _splitView;
	char _hidden;
	char _showAsSidebar;
	UITransitionView* _transitionView;
	int _transitionState;
	char _isPresented;
	char _chainResults;
	id<SearchResultsListViewControllerDelegate><QuickActionMenuPresenterDelegate> _delegate;
	SearchResult* _defaultSearchResult;
	NSArray* _searchResults;

}

@property (assign,nonatomic,__weak) id<SearchResultsListViewControllerDelegate><QuickActionMenuPresenterDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) SearchResult * defaultSearchResult;                                                                         //@synthesize defaultSearchResult=_defaultSearchResult - In the implementation block
@property (nonatomic,retain) NSArray * searchResults;                                                                                    //@synthesize searchResults=_searchResults - In the implementation block
@property (assign,getter=isChainResults,nonatomic) char chainResults;                                                                    //@synthesize chainResults=_chainResults - In the implementation block
@property (nonatomic,readonly) char isPresented;                                                                                         //@synthesize isPresented=_isPresented - In the implementation block
-(char)isChainResults;
-(void)setChainResults:(char)arg1 ;
-(void)updateBlurDisabledBackgroundColor:(id)arg1 blurViewStyle:(int)arg2 transitionToBackdropStyle:(int)arg3 ;
-(void)layoutForUnobscuredBoundsChange;
-(void)presentFromMainChrome:(id)arg1 animated:(char)arg2 ;
-(float)preferredHeightForSplitView;
-(void)updateBarControlInChromeViewController;
-(char)displaysAsSidebar;
-(char)mapViewShouldReceiveTouch:(id)arg1 ;
-(SearchResult *)defaultSearchResult;
-(void)setDefaultSearchResult:(SearchResult *)arg1 ;
-(void)_dismissSplitViewAnimated:(char)arg1 ;
-(void)_presentSplitViewAnimated:(char)arg1 ;
-(UIEdgeInsets)_mapEdgeInsetsWithChromeInsets:(UIEdgeInsets)arg1 ;
-(CGRect)sidebarFrameInView:(id)arg1 ;
-(id)splitView;
-(float)_sidebarWidth;
-(id)searchResultsListViewController;
-(void)setDelegate:(id<SearchResultsListViewControllerDelegate><QuickActionMenuPresenterDelegate>)arg1 ;
-(void)dealloc;
-(void)setHidden:(char)arg1 ;
-(id)init;
-(id<SearchResultsListViewControllerDelegate><QuickActionMenuPresenterDelegate>)delegate;
-(double)durationForTransition:(int)arg1 ;
-(void)transitionViewDidStart:(id)arg1 ;
-(void)transitionViewDidComplete:(id)arg1 finished:(char)arg2 ;
-(void)layout;
-(void)dismissAnimated:(char)arg1 ;
-(char)isPresented;
-(void)setSearchResults:(NSArray *)arg1 ;
-(NSArray *)searchResults;
@end

