/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:33 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface CenteringView : UIView {

	UIView* _contentView;
	int _contentPlacement;
	/*^block*/id _testForFindingSuperviewToCenterIn;
	UIEdgeInsets _contentInset;

}

@property (nonatomic,retain) UIView * contentView;                            //@synthesize contentView=_contentView - In the implementation block
@property (assign,nonatomic) int contentPlacement;                            //@synthesize contentPlacement=_contentPlacement - In the implementation block
@property (nonatomic,copy) id testForFindingSuperviewToCenterIn;              //@synthesize testForFindingSuperviewToCenterIn=_testForFindingSuperviewToCenterIn - In the implementation block
@property (assign,nonatomic) UIEdgeInsets contentInset;                       //@synthesize contentInset=_contentInset - In the implementation block
-(CGRect)_centeringBounds;
-(int)contentPlacement;
-(CGRect)frameForView:(id)arg1 contentPlacement:(int)arg2 ;
-(void)setContentPlacement:(int)arg1 ;
-(void)setTestForFindingSuperviewToCenterIn:(id)arg1 ;
-(id)testForFindingSuperviewToCenterIn;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(UIEdgeInsets)contentInset;
-(UIView *)contentView;
-(void)setContentView:(UIView *)arg1 ;
-(void)layoutMarginsDidChange;
-(void)willRemoveSubview:(id)arg1 ;
-(void)setContentInset:(UIEdgeInsets)arg1 ;
@end

