/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:28 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>
#import <UIKit/UITextFieldDelegate.h>

@class UITextField, NSString;

@interface CustomServiceURLDebugController : UITableViewController <UITextFieldDelegate> {

	UITextField* _textField;
	NSString* _defaultsKey;
	NSString* _defaultURLString;
	/*^block*/id _callback;

}

@property (nonatomic,copy) NSString * defaultsKey;                   //@synthesize defaultsKey=_defaultsKey - In the implementation block
@property (nonatomic,copy) NSString * defaultURLString;              //@synthesize defaultURLString=_defaultURLString - In the implementation block
@property (nonatomic,copy) id callback;                              //@synthesize callback=_callback - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)defaultURLString;
-(NSString *)defaultsKey;
-(void)setDefaultsKey:(NSString *)arg1 ;
-(void)setDefaultURLString:(NSString *)arg1 ;
-(void)dealloc;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)title;
-(id)initWithStyle:(int)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 ;
-(char)textFieldShouldReturn:(id)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(id)callback;
-(void)setCallback:(id)arg1 ;
@end

