/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:27 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol DirectionsSearchViewControllerDelegate <NSObject>
@required
-(void)directionsSearchViewControllerDidRoute:(id)arg1;
-(void)directionsSearchViewControllerDidSelectRoutingApp:(id)arg1;
-(void)directionsSearchViewControllerDidCancel:(id)arg1;
-(void)directionsSearchViewController:(id)arg1 didSelectDirectionsMode:(unsigned)arg2;
-(void)directionsSearchViewControllerDidSelectFavorites:(id)arg1;
-(id)directionsSearchViewControllerTraits:(id)arg1;

@end

