/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:31 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/CalloutTabButton.h>
#import <libobjc.A.dylib/MKQuickRouteConfigurableView.h>

@class SearchResult, NSString;

@interface DirectionsCalloutButton : CalloutTabButton <MKQuickRouteConfigurableView> {

	double _expectedTravelTime;
	unsigned _transportType;
	double _earliestTransitTypeChange;
	/*^block*/id _performWhenSizedBlock;
	SearchResult* _searchResult;
	/*^block*/id _etaCompletionBlock;

}

@property (assign,nonatomic) double expectedTravelTime;                //@synthesize expectedTravelTime=_expectedTravelTime - In the implementation block
@property (assign,nonatomic) unsigned transportType;                   //@synthesize transportType=_transportType - In the implementation block
@property (nonatomic,retain) SearchResult * searchResult;              //@synthesize searchResult=_searchResult - In the implementation block
@property (copy) id etaCompletionBlock;                                //@synthesize etaCompletionBlock=_etaCompletionBlock - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setExpectedTravelTime:(double)arg1 ;
-(void)setEtaCompletionBlock:(id)arg1 ;
-(void)setExpectedTravelTime:(double)arg1 animated:(char)arg2 ;
-(id)etaCompletionBlock;
-(void)_performWhenSized:(/*^block*/id)arg1 ;
-(float)topToImageViewTopDistance;
-(id)stringFormatter;
-(double)expectedTravelTime;
-(void)quickRouteManager:(id)arg1 didUpdateETA:(id)arg2 error:(id)arg3 animated:(char)arg4 ;
-(void)_updateImage;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setTransportType:(unsigned)arg1 ;
-(unsigned)transportType;
-(void)setSearchResult:(SearchResult *)arg1 ;
-(SearchResult *)searchResult;
-(void)_contentSizeCategoryDidChange:(id)arg1 ;
@end

