/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:29 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/DirectionsManagerObserver.h>
#import <Maps/RoutePickingProvider.h>

@class RoutePickingModeController, DirectionsWaypoint, DirectionsManagerLoadingResult, NSHashTable, NSError, RoutePickingTiming, NSString;

@interface DirectionsManagerRoutePickingProvider : NSObject <DirectionsManagerObserver, RoutePickingProvider> {

	DirectionsManagerLoadingResult* _displayableRoutesResult;
	DirectionsManagerLoadingResult* _lastRequestedResult;
	NSHashTable* _lastKnownRoutesFromRouteSet;
	char _isWaitingForLoadingToStart;
	NSError* _currentError;
	RoutePickingTiming* _overrideTiming;
	RoutePickingModeController* _routePickingMode;
	DirectionsWaypoint* _startWaypoint;
	DirectionsWaypoint* _endWaypoint;
	SCD_Struct_Di18 _timepoint;

}

@property (nonatomic,retain) DirectionsWaypoint * startWaypoint;                                //@synthesize startWaypoint=_startWaypoint - In the implementation block
@property (nonatomic,retain) DirectionsWaypoint * endWaypoint;                                  //@synthesize endWaypoint=_endWaypoint - In the implementation block
@property (assign,nonatomic) SCD_Struct_Ro12 timepoint;                                         //@synthesize timepoint=_timepoint - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) RoutePickingModeController * routePickingMode;              //@synthesize routePickingMode=_routePickingMode - In the implementation block
-(void)directionsManagerDidStartLoad:(id)arg1 ;
-(void)directionsManager:(id)arg1 didLoadRoute:(id)arg2 ;
-(void)directionsManagerDidReset:(id)arg1 ;
-(void)directionsManagerDidFailToLoadMoreRoutes:(id)arg1 withError:(id)arg2 ;
-(void)directionsManagerDidAppendNewRoutesInCurrentRouteSet:(id)arg1 ;
-(void)directionsManagerDidFailToLoadInitialRoutes:(id)arg1 withError:(id)arg2 ;
-(id)latestReportAProblemRecording;
-(RoutePickingModeController *)routePickingMode;
-(unsigned)lastRequestedTransportType;
-(id)initFromDirectionsManager;
-(void)_clearResultAndNoteChangedWithError:(id)arg1 ;
-(void)_clearResultAndNoteChanged;
-(void)writeTraceToFile;
-(void)_updateResultFromDirectionsManager;
-(id)lastRequestedDisplayableRoutes;
-(id)displayableRoutes;
-(void)setRoutePickingMode:(RoutePickingModeController *)arg1 ;
-(id)lastRequestedTiming;
-(void)beginLoadingRoutesFromWaypoint:(id)arg1 toWaypoint:(id)arg2 mode:(unsigned)arg3 traits:(id)arg4 timepoint:(SCD_Struct_Ro12)arg5 sortOption:(int)arg6 routeHandle:(id)arg7 tracePlayer:(id)arg8 withFeedback:(id)arg9 withUserInfo:(id)arg10 ;
-(id)initWithOriginWaypoint:(id)arg1 destinationWaypoint:(id)arg2 ;
-(id)currentError;
-(void)setOverrideTiming:(id)arg1 ;
-(void)dealloc;
-(void)_commonInit;
-(char)isLoading;
-(SCD_Struct_Ro12)timepoint;
-(void)setTimepoint:(SCD_Struct_Ro12)arg1 ;
-(void)setEndWaypoint:(DirectionsWaypoint *)arg1 ;
-(DirectionsWaypoint *)startWaypoint;
-(DirectionsWaypoint *)endWaypoint;
-(void)setStartWaypoint:(DirectionsWaypoint *)arg1 ;
@end

