/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:26 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol GEOResourceManifestTileGroupObserver <NSObject>
@optional
-(void)resourceManifestManager:(id)arg1 didChangeActiveTileGroup:(id)arg2 fromOldTileGroup:(id)arg3;
-(void)resourceManifestManagerWillChangeActiveTileGroup:(id)arg1;
-(void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1;

@end

