/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:28 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>
#import <Maps/TopBarStyledLabelDelegate.h>

@class TopBarStyledLabel, UIView, MapsAutoLayoutContext, NSString;

@interface InlineNavigationTopBarTitleView : UIView <TopBarStyledLabelDelegate> {

	TopBarStyledLabel* _primaryLabel;
	TopBarStyledLabel* _secondaryLabel;
	TopBarStyledLabel* _tertiaryLabel;
	UIView* _centeredContainer;
	MapsAutoLayoutContext* _layoutContext;
	char _dimmed;
	char _darkUI;

}

@property (nonatomic,copy) id primaryTextProvider; 
@property (nonatomic,copy) id secondaryTextProvider; 
@property (nonatomic,copy) id tertiaryTextProvider; 
@property (assign,nonatomic) char dimmed;                           //@synthesize dimmed=_dimmed - In the implementation block
@property (assign,nonatomic) char darkUI;                           //@synthesize darkUI=_darkUI - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)requiresConstraintBasedLayout;
-(void)setDarkUI:(char)arg1 ;
-(id)secondaryTextProvider;
-(void)setPrimaryTextProvider:(id)arg1 ;
-(char)darkUI;
-(void)clearStrings;
-(id)primaryTextProvider;
-(void)setSecondaryTextProvider:(id)arg1 ;
-(void)topBarStyledLabelDidBecomeEmpty:(id)arg1 ;
-(id)_createConfiguredLabelInSuperview:(id)arg1 ;
-(void)setTertiaryTextProvider:(id)arg1 ;
-(id)_defaultAttributeCollection;
-(void)topBarStyledLabelDidBecomeNonempty:(id)arg1 ;
-(id)tertiaryTextProvider;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)didMoveToWindow;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)updateConstraints;
-(void)setDimmed:(char)arg1 ;
-(char)dimmed;
-(void)_updateAttributes;
@end

