/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:25 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableArray, NSArray;

@interface MapsDebugCheckmarkRowsGroup : NSObject {

	NSMutableArray* _heldRows;
	NSMutableArray* _weakRows;
	/*^block*/id _selectionChanged;

}

@property (nonatomic,readonly) NSArray * rows; 
@property (nonatomic,copy) id selectionChanged;              //@synthesize selectionChanged=_selectionChanged - In the implementation block
+(id)rowsGroupContainingRows:(out id*)arg1 withContent:(/*^block*/id)arg2 get:(/*^block*/id)arg3 set:(/*^block*/id)arg4 ;
-(id)_relinquishOwnershipOfHeldRows;
-(id)_initWithHeldRows;
-(void)setSelectionChanged:(id)arg1 ;
-(void)checkmarkRowWillInvalidate:(id)arg1 ;
-(id)addRowWithTitle:(id)arg1 value:(id)arg2 ;
-(void)checkmarkRowDidChangeChecked:(id)arg1 ;
-(id)init;
-(id)selectionChanged;
-(void)update;
-(NSArray *)rows;
-(void)addRow:(id)arg1 ;
@end

