/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:26 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UISegmentedControl.h>

@class NSSet, NSArray;

@interface MapViewModeSelector : UISegmentedControl {

	char _lastLayoutWidthFits;
	NSSet* _disallowedViewModes;
	NSArray* _orderedViewModes;
	float _lastLayoutWidth;

}

@property (assign,nonatomic) int selectedViewMode; 
@property (nonatomic,copy) NSSet * disallowedViewModes;               //@synthesize disallowedViewModes=_disallowedViewModes - In the implementation block
@property (nonatomic,retain) NSArray * orderedViewModes;              //@synthesize orderedViewModes=_orderedViewModes - In the implementation block
@property (assign,nonatomic) float lastLayoutWidth;                   //@synthesize lastLayoutWidth=_lastLayoutWidth - In the implementation block
@property (assign,nonatomic) char lastLayoutWidthFits;                //@synthesize lastLayoutWidthFits=_lastLayoutWidthFits - In the implementation block
-(char)updateSegmentsIfNeededToFitWidth:(float)arg1 ;
-(float)lastLayoutWidth;
-(void)setLastLayoutWidth:(float)arg1 ;
-(int)selectedViewMode;
-(void)setLastLayoutWidthFits:(char)arg1 ;
-(void)setDisallowedViewModes:(NSSet *)arg1 ;
-(void)setOrderedViewModes:(NSArray *)arg1 ;
-(char)lastLayoutWidthFits;
-(void)setSelectedViewMode:(int)arg1 ;
-(NSSet *)disallowedViewModes;
-(NSArray *)orderedViewModes;
-(id)init;
@end

