/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:28 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MNGuidanceDisplay <NSObject>
@property (assign,getter=isGuidanceEnabled,nonatomic) char guidanceEnabled; 
@optional
-(void)setGuidanceEnabled:(char)arg1;
-(char)isGuidanceEnabled;
-(void)setGuidanceEnabled:(char)arg1 animated:(char)arg2;
-(void)willEndNavigation;
-(void)willResumeNavigation;
-(void)setCurrentRoadDescriptionIsUnreliable:(char)arg1;
-(void)willPauseNavigation;
-(void)willStartNavigation;
-(void)didStartNavigation;
-(void)hideRecalculating;
-(void)showRecalculationFailed;

@required
-(void)setDestinationDisplayName:(id)arg1;
-(void)showNewManeuver:(int)arg1 junction:(id)arg2 instructions:(id)arg3 shorterAlternativeInstructions:(id)arg4 shieldType:(int)arg5 shieldText:(id)arg6 drivingSide:(int)arg7;
-(void)setETA:(id)arg1;
-(void)showRecalculating;
-(void)showProceedingToRouteDistance:(double)arg1 displayString:(id)arg2;
-(void)showArrived;
-(void)showSecondaryManeuver:(int)arg1 junction:(id)arg2 instructions:(id)arg3 shorterAlternativeInstructions:(id)arg4 shieldType:(int)arg5 shieldText:(id)arg6 drivingSide:(int)arg7;
-(void)hideSecondaryManeuver;
-(void)setTimeToManeuver:(double)arg1 distanceToManeuver:(double)arg2;
-(void)showManeuverAlertForAnnouncementStage:(unsigned)arg1;
-(void)showNoGuidance;

@end

