/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:33 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MNMapMatcher.h>

@interface MNWalkMapMatcher : MNMapMatcher {

	int _numProgressionsOffRoute;

}
-(id)matchLocation:(id)arg1 alongRoute:(id)arg2 onDate:(id)arg3 activeTransportType:(int)arg4 ;
-(int)transportType;
@end

