/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:28 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UITableViewController.h>
#import <Maps/RAPAddressCellDelegate.h>
#import <Maps/RAPCategoryChooserDelegate.h>

@class RAPReport, RAPPlaceCorrectionsQuestion, UIBarButtonItem, ReportAProblemCategoryChooserViewController, RAPPhotoPickerController, RAPAddNewPlaceType, RAPMapFeatureTableViewCell, NSString;

@interface RAPAddressCorrectionsViewController : UITableViewController <RAPAddressCellDelegate, RAPCategoryChooserDelegate> {

	RAPReport* _report;
	RAPPlaceCorrectionsQuestion* _question;
	/*^block*/id _completion;
	UIBarButtonItem* _sendButtonItem;
	ReportAProblemCategoryChooserViewController* _categoryViewController;
	float _verticalBarOffset;
	RAPPhotoPickerController* _photoPicker;
	RAPAddNewPlaceType* _previouslySelectedAddNewPlaceType;
	RAPMapFeatureTableViewCell* _locationCell;

}

@property (nonatomic,retain) RAPMapFeatureTableViewCell * locationCell;              //@synthesize locationCell=_locationCell - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithReport:(id)arg1 question:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)reportAProblemCellShouldAdvanceToPreviousResponder:(id)arg1 ;
-(char)_isLocationSection:(int)arg1 ;
-(int)_photosSection;
-(int)_locationIsMissingSection;
-(id)_problemItemForType:(int)arg1 ;
-(char)_isAddCategoryButtonIndexPath:(id)arg1 ;
-(unsigned)_indexOfCorrectableItemForSection:(int)arg1 ;
-(int)_correctableItemSectionOffset;
-(id)_indexPathForAddCategoryButton;
-(void)_makeFirstResponderCellAtIndexPath:(id)arg1 fromDirection:(int)arg2 ;
-(char)_isCommentSection:(int)arg1 ;
-(int)_commentSection;
-(char)_isLocationIsMissingSection:(int)arg1 ;
-(char)_hasLocationSection;
-(void)didReceiveSelectedCategory:(id)arg1 forIndexPath:(id)arg2 ;
-(id)_sendButtonItem;
-(char)_isMultipleCategoriesSection:(int)arg1 ;
-(void)valueForAddressType:(int)arg1 changedTo:(id)arg2 ;
-(int)_indexForMultipleCategoriesSection;
-(void)_performDeletionForCategoryAtIndexPath:(id)arg1 animated:(char)arg2 ;
-(RAPMapFeatureTableViewCell *)locationCell;
-(char)_isPhotosSection:(int)arg1 ;
-(id)_addNewPlaceQuestion;
-(void)reportAProblemCellDidBecomeFirstResponder:(id)arg1 ;
-(void)setLocationCell:(RAPMapFeatureTableViewCell *)arg1 ;
-(void)deleteCategoryAtIndexPath:(id)arg1 ;
-(void)_send;
-(void)reportAProblemCellDidResignFirstResponder:(id)arg1 ;
-(id)snapshotOptionsWithQuestion:(id)arg1 ;
-(int)_locationSection;
-(void)reportAProblemCellCorrectnessStatusChanged:(id)arg1 ;
-(id)_photoPicker;
-(void)_beginPickingCategoriesForRowAtIndexPath:(id)arg1 ;
-(char)_hasLocationIsMissingSection;
-(void)reportAProblemCellShouldAdvanceToNextResponder:(id)arg1 ;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(char)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
@end

