/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:31 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/RAPTransitLine.h>

@interface RAPDirectionsLine : RAPTransitLine {

	unsigned _lineIndex;

}

@property (getter=_lineIndex,nonatomic,readonly) unsigned lineIndex;              //@synthesize lineIndex=_lineIndex - In the implementation block
-(id)_initWithName:(id)arg1 systemName:(id)arg2 artworkData:(id)arg3 lineIndex:(unsigned)arg4 lineFeatureID:(unsigned long long)arg5 primaryDescriptionText:(id)arg6 secondaryDescriptionText:(id)arg7 ;
-(unsigned)_lineIndex;
@end

