/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:30 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIViewController.h>
#import <libobjc.A.dylib/MKMapViewDelegate.h>
#import <Maps/MKMapViewDelegatePrivate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol RAPAddressLocation;
@class MKMapView, UIBarButtonItem, MKUserTrackingBarButtonItem, UISegmentedControl, NSString, ReportAProblemLocationInstructionsView, RAPMapFeaturePickerPinAnnotation, RAPTransitLinesAnnotation, NSArray, VKLabelMarker, RAPReportContext;

@interface RAPMapFeaturePickerViewController : UIViewController <MKMapViewDelegate, MKMapViewDelegatePrivate, UIGestureRecognizerDelegate> {

	int _kind;
	SCD_Struct_RA13 _rect;
	char _hasPreferredMapType;
	unsigned _preferredMapType;
	MKMapView* _mapView;
	/*^block*/id _selection;
	UIBarButtonItem* _commitBarItem;
	UIBarButtonItem* _cancelBarItem;
	/*^block*/id _commit;
	/*^block*/id _cancel;
	MKUserTrackingBarButtonItem* _trackingItem;
	UISegmentedControl* _mapModeControl;
	NSString* _prompt;
	ReportAProblemLocationInstructionsView* _instructionsView;
	char _settingInitialAnnotationCoordinate;
	RAPMapFeaturePickerPinAnnotation* _annotation;
	char _creatingMapViewReportContext;
	SCD_Struct_RA7 _initialFeatureCoordinate;
	NSString* _annotationTitle;
	RAPTransitLinesAnnotation* _transitLinesAnnotation;
	char _canCommit;
	NSArray* _selectedTransitLineMarkers;
	VKLabelMarker* _selectedLabelMarker;
	id<RAPAddressLocation> _selectedAddressLocation;
	RAPReportContext* _mapViewReportContext;
	SCD_Struct_RA7 _selectedCoordinate;
	SCD_Struct_RA13 _selectedMapRect;

}

@property (nonatomic,readonly) NSArray * selectedTransitLineMarkers;                        //@synthesize selectedTransitLineMarkers=_selectedTransitLineMarkers - In the implementation block
@property (nonatomic,readonly) VKLabelMarker * selectedLabelMarker;                         //@synthesize selectedLabelMarker=_selectedLabelMarker - In the implementation block
@property (nonatomic,readonly) SCD_Struct_RA7 selectedCoordinate;                           //@synthesize selectedCoordinate=_selectedCoordinate - In the implementation block
@property (nonatomic,readonly) SCD_Struct_RA13 selectedMapRect;                             //@synthesize selectedMapRect=_selectedMapRect - In the implementation block
@property (nonatomic,readonly) id<RAPAddressLocation> selectedAddressLocation;              //@synthesize selectedAddressLocation=_selectedAddressLocation - In the implementation block
@property (nonatomic,readonly) RAPReportContext * mapViewReportContext;                     //@synthesize mapViewReportContext=_mapViewReportContext - In the implementation block
@property (nonatomic,readonly) char canCommit;                                              //@synthesize canCommit=_canCommit - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_selectionDidChange;
-(SCD_Struct_RA7)selectedCoordinate;
-(char)_annotationShowsCalloutForCurrentKind;
-(void)setHandlerBlocksForUserCommittedSelection:(/*^block*/id)arg1 cancelled:(/*^block*/id)arg2 ;
-(NSArray *)selectedTransitLineMarkers;
-(void)getSystemNamesForMarkers:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_annotationCoordinateDidChange:(id)arg1 ;
-(id)initForPickingFeatureOfKind:(int)arg1 withPrompt:(id)arg2 title:(id)arg3 initialFeatureCoordinate:(SCD_Struct_RA7)arg4 annotationTitle:(id)arg5 inMapRect:(SCD_Struct_RA13)arg6 selection:(/*^block*/id)arg7 ;
-(id)initForPickingFeatureOfKind:(int)arg1 withPrompt:(id)arg2 title:(id)arg3 inMapRect:(SCD_Struct_RA13)arg4 selection:(/*^block*/id)arg5 ;
-(char)_kindTracksLabelMarkerSelection;
-(id)initForPickingFeatureOfKind:(int)arg1 withPrompt:(id)arg2 title:(id)arg3 inMapRect:(SCD_Struct_RA13)arg4 preferredMapType:(unsigned)arg5 selection:(/*^block*/id)arg6 ;
-(char)canCommit;
-(SCD_Struct_RA13)selectedMapRect;
-(void)setHandlerBlocksForUserCommittedSelection:(/*^block*/id)arg1 withRightBarButtonItemTitle:(id)arg2 ;
-(id<RAPAddressLocation>)selectedAddressLocation;
-(RAPReportContext *)mapViewReportContext;
-(SCD_Struct_RA7)_currentValidInitialFeatureCoordinate;
-(void)_mapTappedForTransitLineSelection:(id)arg1 ;
-(void)_updateCommitBarItem;
-(void)setSelectedLabelMarker:(VKLabelMarker *)arg1 ;
-(char)_kindAllowsChangingMode;
-(VKLabelMarker *)selectedLabelMarker;
-(void)mapView:(id)arg1 didDeselectLabelMarker:(id)arg2 ;
-(char)mapView:(id)arg1 shouldSelectLabelMarker:(id)arg2 ;
-(void)mapView:(id)arg1 didSelectLabelMarker:(id)arg2 ;
-(void)mapViewDidChangeVisibleRegion:(id)arg1 ;
-(void)mapView:(id)arg1 regionDidChangeAnimated:(char)arg2 ;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2 ;
-(char)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewWillDisappear:(char)arg1 ;
-(void)_commit;
-(void)_cancel;
@end

