/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:31 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/RAPReportTableViewController.h>

@class RAPProblemNotListedQuestion, RAPReportComposerCommentPart;

@interface RAPReportComposerProblemNotListedViewController : RAPReportTableViewController {

	RAPProblemNotListedQuestion* _question;
	RAPReportComposerCommentPart* _commentPart;

}
-(id)tableParts;
-(id)initWithReport:(id)arg1 question:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)rapReportComposerCommentTableViewCell;
-(void)viewDidAppear:(char)arg1 ;
@end

