/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:25 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/LabelListView.h>

@interface RouteStepLabelListView : LabelListView {

	char _tableMode;

}

@property (assign,nonatomic) char tableMode;              //@synthesize tableMode=_tableMode - In the implementation block
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 ;
+(id)voiceOverStringsForRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 ;
+(float)heightForWidth:(float)arg1 route:(id)arg2 step:(id)arg3 ;
+(id)fontsForStrings:(id)arg1 route:(id)arg2 step:(id)arg3 tableMode:(char)arg4 ;
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 isPrinting:(char)arg4 ;
-(void)setRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 ;
-(void)setTableMode:(char)arg1 ;
-(char)tableMode;
-(id)initWithRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 ;
@end

