/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:30 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MainChromeTopBarContent.h>

@class RoutePickingModeSelector, UIView, RoutePickingFieldView, MainChromeViewController, UIBarButtonItem, NSSet, NSString;

@interface RoutePickingBar : NSObject <MainChromeTopBarContent> {

	RoutePickingModeSelector* _modeSelectorInPaletteWhileNonmodal;
	UIView* _nonmodalPaletteView;
	RoutePickingFieldView* _field;
	char _dimmed;
	MainChromeViewController* _chromeViewController;
	UIBarButtonItem* _shareItem;
	UIBarButtonItem* _clearItem;
	float _maxSelectorWidth;

}

@property (assign,nonatomic) MainChromeViewController * chromeViewController;              //@synthesize chromeViewController=_chromeViewController - In the implementation block
@property (assign,nonatomic) int selectedVariant; 
@property (nonatomic,retain) NSSet * selectableVariants; 
@property (nonatomic,retain) UIBarButtonItem * clearItem;                                  //@synthesize clearItem=_clearItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * shareItem;                                  //@synthesize shareItem=_shareItem - In the implementation block
@property (assign,nonatomic) float maxSelectorWidth;                                       //@synthesize maxSelectorWidth=_maxSelectorWidth - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setSelectableVariants:(NSSet *)arg1 ;
-(void)setSelectedVariant:(int)arg1 ;
-(NSSet *)selectableVariants;
-(int)selectedVariant;
-(MainChromeViewController *)chromeViewController;
-(void)setBackdropLightness:(int)arg1 animation:(id)arg2 ;
-(void)setChromeViewController:(MainChromeViewController *)arg1 ;
-(id)sharePresentationSource;
-(char)showsVariantSelectionPaletteView;
-(void)performInitialConfigurationOnField:(id)arg1 ;
-(id)directionsSearchPresentationSource;
-(id)paletteView;
-(float)paletteViewHeight;
-(float)modeSelectorWidth;
-(UIBarButtonItem *)clearItem;
-(id)modeSelectorInPaletteWhileNonmodal;
-(void)setMaxSelectorWidth:(float)arg1 ;
-(id)nonmodalPaletteView;
-(UIBarButtonItem *)shareItem;
-(id)directionsStepsListPresentationSource;
-(float)maxSelectorWidth;
-(void)setShareItem:(UIBarButtonItem *)arg1 ;
-(void)setClearItem:(UIBarButtonItem *)arg1 ;
-(id)initWithFieldView:(id)arg1 selectedVariantChangeBlock:(/*^block*/id)arg2 ;
-(id)init;
-(id)field;
@end

