/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:31 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/SearchResultRepr.h>
#import <Maps/RAPPlace.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/MKLocatableObject.h>
#import <libobjc.A.dylib/MKAnnotation.h>
#import <Maps/MapsSynced.h>

@class NSString, AddressBookAddress, UIImage, GEOComposedWaypoint, MSPBookmarkStorage, MSPPinStorage, GEORPPlaceInfo, MKMapItem, NSData;

@interface SearchResult : SearchResultRepr <RAPPlace, NSCopying, MKLocatableObject, MKAnnotation, MapsSynced> {

	NSString* _singleLineAddress;
	NSString* _singleLineAddressWithHomeCountry;
	char _hasMergedFormattedAddress;
	NSString* _formattedAddress;
	NSString* _formattedAddressMultiline;
	SCD_Struct_RA7 _coordinate;
	char _originatedFromHistory;
	char _originatedFromTrace;
	char _originatedFromBookmarks;
	AddressBookAddress* _address;
	int _appearance;
	unsigned long long _businessID;
	UIImage* _parkingImage;
	GEOComposedWaypoint* _composedWaypoint;
	MSPBookmarkStorage* _bookmarkStorage;
	MSPPinStorage* _pinStorage;
	GEORPPlaceInfo* _placeInfo;
	MKMapItem* _mapItem;

}

@property (nonatomic,readonly) MSPBookmarkStorage * bookmarkStorage; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) SCD_Struct_RA7 coordinate;                                  //@synthesize coordinate=_coordinate - In the implementation block
@property (assign,getter=isReverseGeocoded,nonatomic) char reverseGeocoded; 
@property (nonatomic,readonly) char needsReverseGeocodeCheck; 
@property (assign,nonatomic) char originatedFromHistory;                                 //@synthesize originatedFromHistory=_originatedFromHistory - In the implementation block
@property (assign,nonatomic) char originatedFromTrace;                                   //@synthesize originatedFromTrace=_originatedFromTrace - In the implementation block
@property (nonatomic,readonly) char isDynamicCurrentLocation; 
@property (assign,nonatomic) int appearance;                                             //@synthesize appearance=_appearance - In the implementation block
@property (nonatomic,readonly) unsigned long long businessID; 
@property (nonatomic,readonly) int localSearchProviderID; 
@property (nonatomic,readonly) NSString * infoCardTitle; 
@property (nonatomic,readonly) NSString * locationTitle; 
@property (nonatomic,readonly) NSString * rawLocationTitle; 
@property (nonatomic,readonly) NSString * disambiguationTitle; 
@property (nonatomic,readonly) NSString * tweetableTitle; 
@property (nonatomic,readonly) NSString * defaultName; 
@property (nonatomic,readonly) NSString * countryCode; 
@property (nonatomic,readonly) NSString * locality; 
@property (nonatomic,retain) GEOComposedWaypoint * composedWaypoint;                     //@synthesize composedWaypoint=_composedWaypoint - In the implementation block
@property (nonatomic,readonly) MSPPinStorage * pinStorage;                               //@synthesize pinStorage=_pinStorage - In the implementation block
@property (nonatomic,retain) MKMapItem * mapItem;                                        //@synthesize mapItem=_mapItem - In the implementation block
@property (nonatomic,retain) GEORPPlaceInfo * placeInfo;                                 //@synthesize placeInfo=_placeInfo - In the implementation block
@property (nonatomic,retain) NSString * bookmarkTitle; 
@property (nonatomic,retain) AddressBookAddress * address; 
@property (nonatomic,copy,readonly) NSString * title; 
@property (nonatomic,copy,readonly) NSString * subtitle; 
@property (nonatomic,copy) NSString * syncIdentifier; 
@property (nonatomic,readonly) NSData * syncData; 
@property (assign,nonatomic) double position; 
+(id)currentLocationSearchResult;
+(id)keyPathsForValuesAffectingLocationTitle;
+(id)customSearchResultWithCoordinate:(SCD_Struct_RA7)arg1 ;
+(id)keyPathsForValuesAffectingSingleLineAddressWithHomeCountry;
+(id)keyPathsForValuesAffectingSingleLineAddress;
+(id)keyPathsForValuesAffectingSubtitle;
+(id)keyPathsForValuesAffectingName;
+(id)keyPathsForValuesAffectingTitle;
-(id)initWithSearchResult:(id)arg1 ;
-(char)updateFromSyncData:(id)arg1 ;
-(id)initWithDroppedPin:(id)arg1 ;
-(NSString *)bookmarkTitle;
-(void)setBookmarkTitle:(NSString *)arg1 ;
-(SCD_Struct_RA7)_offsetCoordinate:(float)arg1 ;
-(id)singleLineAddressWithHomeCountry;
-(char)needsReverseGeocodeCheck;
-(void)setReverseGeocoded:(char)arg1 ;
-(char)canDropAPin;
-(id)siriRepresentation;
-(id)userVisibleTitle;
-(char)requiresAdditionalNavData;
-(id)initWithFavoritePlace:(id)arg1 ;
-(void)updateWithReverseGeocodedMapItem:(id)arg1 ;
-(id)initWithMapItem:(id)arg1 searchResultType:(unsigned)arg2 resultIndex:(int)arg3 ;
-(id)initWithMapItem:(id)arg1 searchResultType:(unsigned)arg2 addressBookAddress:(id)arg3 resultIndex:(int)arg4 ;
-(char)_isEqualToSearchResult:(id)arg1 loose:(char)arg2 ;
-(char)_hasUID;
-(id)initWithSearchResult:(id)arg1 address:(id)arg2 ;
-(char)originatedFromTrace;
-(NSString *)rawLocationTitle;
-(char)hasOriginatedFromBookmarks;
-(void)setOriginatedFromTrace:(char)arg1 ;
-(GEOComposedWaypoint *)composedWaypoint;
-(void)becomeDefaultTypeIfCustomType;
-(void)setOriginalType:(unsigned)arg1 ;
-(void)setOriginatedFromHistory:(char)arg1 ;
-(void)setAddressFromSearchResult:(id)arg1 ;
-(char)originatedFromHistory;
-(MSPPinStorage *)pinStorage;
-(id)copyWithCoordinate:(SCD_Struct_RA7)arg1 ;
-(id)copyWithType:(unsigned)arg1 ;
-(id)copyForBookmarksWithType:(unsigned)arg1 name:(id)arg2 zoomLevel:(unsigned)arg3 ;
-(void)clearLocationInformation;
-(char)updateFromBookmarkRepresentation:(id)arg1 ;
-(id)unknownContact;
-(id)initWithBookmarkRepresentation:(id)arg1 ;
-(id)bookmarkRepresentation;
-(id)initWithComposedWaypoint:(id)arg1 preserveLocationInfo:(char)arg2 ;
-(void)updateWithGEOMapItem:(id)arg1 ;
-(NSString *)defaultName;
-(char)isDynamicCurrentLocation;
-(id)mapsURLfromMapView:(id)arg1 ;
-(void)_updateTypeAndOriginalTypeIfNeeded;
-(id)initWithComposedWaypoint:(id)arg1 ;
-(id)initWithGEOPlace:(id)arg1 ;
-(id)initWithGEOMapItem:(id)arg1 ;
-(char)isEqualToSearchResult:(id)arg1 ;
-(char)isEqualToSearchResult:(id)arg1 forPurpose:(int)arg2 ;
-(char)isLocationEqual:(id)arg1 withinDistance:(double)arg2 ;
-(void)setCoordinate:(SCD_Struct_RA7)arg1 preserveLocationInfo:(char)arg2 ;
-(NSString *)locationTitle;
-(id)_locationTitleNeedsRaw:(char)arg1 ;
-(void)setComposedWaypoint:(GEOComposedWaypoint *)arg1 ;
-(void)_syncGEOPlaceWithCoordinate;
-(char)isAddressBookResult;
-(char)isReverseGeocoded;
-(void)markAsOriginatingFromBookmarks;
-(char)isInMapRect:(SCD_Struct_RA13)arg1 ;
-(char)isInMapRegion:(id)arg1 ;
-(NSString *)infoCardTitle;
-(id)initWithMapItem:(id)arg1 syncIdentifier:(id)arg2 ;
-(id)coordinateString;
-(NSString *)disambiguationTitle;
-(NSString *)tweetableTitle;
-(void)clearAddressCache;
-(id)initWithSearchResultStrippingName:(id)arg1 address:(id)arg2 ;
-(char)_hasStructuredAddress;
-(id)externalAccessoryRepresentationWithError:(out id*)arg1 ;
-(id)routableAddress;
-(id)_formattedAddressMultiline;
-(id)_formattedAddress;
-(id)singleLineAddress;
-(MKMapItem *)mapItem;
-(void)setMapItem:(MKMapItem *)arg1 ;
-(void)setCoordinate:(SCD_Struct_RA7)arg1 ;
-(SCD_Struct_RA7)coordinate;
-(AddressBookAddress *)address;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(NSString *)description;
-(NSString *)debugDescription;
-(id)name;
-(void)setType:(unsigned)arg1 ;
-(NSString *)title;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithData:(id)arg1 ;
-(void)_commonInit;
-(id)initWithType:(unsigned)arg1 ;
-(int)appearance;
-(NSString *)subtitle;
-(int)source;
-(NSData *)syncData;
-(void)writeTo:(id)arg1 ;
-(void)setAddress:(AddressBookAddress *)arg1 ;
-(id)mapsURL;
-(int)localSearchProviderID;
-(NSString *)countryCode;
-(id)_flyover;
-(id)addressDictionary;
-(NSString *)locality;
-(void)setPlaceInfo:(GEORPPlaceInfo *)arg1 ;
-(GEORPPlaceInfo *)placeInfo;
-(unsigned long long)businessID;
-(id)initWithMapItem:(id)arg1 ;
-(id)initWithBookmarkStorage:(id)arg1 ;
-(MSPBookmarkStorage *)bookmarkStorage;
-(char)readFrom:(id)arg1 ;
-(void)setAppearance:(int)arg1 ;
@end

