/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:27 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SearchResultsListViewControllerDelegate <NSObject>
@required
-(void)searchResultsListViewController:(id)arg1 didTapDisclosureForSearchResult:(id)arg2;
-(void)searchResultsListViewController:(id)arg1 didPopRowForSearchResult:(id)arg2;
-(void)searchResultsListViewController:(id)arg1 didCommitPreviewForSearchResult:(id)arg2 withCenterCoordinate:(SCD_Struct_RA7)arg3 zoomLevel:(float)arg4;
-(void)searchResultsListViewController:(id)arg1 didTapRowForSearchResult:(id)arg2;
-(id)mapView;

@end

