/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:31 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/QuickActionMenuPresenter.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class UITableView, SearchResultTouchCancellingGesture, NSString;

@interface SearchResultQuickActionMenuPresenter : QuickActionMenuPresenter <UIGestureRecognizerDelegate> {

	UITableView* _tableView;
	SearchResultTouchCancellingGesture* _cancellingGesture;

}

@property (assign,nonatomic,__weak) id<SearchResultQuickActionMenuPresenterDelegate> delegate; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)actionMenuDidFinish;
-(char)_shouldBeginOrbGestureAtLocation:(CGPoint)arg1 inView:(id)arg2 ;
-(id)initWithPresentingViewController:(id)arg1 inView:(id)arg2 ;
-(id)initWithPresentingViewController:(id)arg1 inTableView:(id)arg2 ;
-(char)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
@end

