/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:33 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <libobjc.A.dylib/MKMapViewDelegate.h>
#import <Maps/MNNavigationSessionUIDelegate.h>
#import <Maps/StarkDrivingNavigationItemDelegate.h>
#import <Maps/StarkChromeModeController.h>

@protocol MapsChromeViews;
@class StarkDrivingNavigationItem, MNNavigationModeController, MapsChromeViewController, NSString, UIView, ChromeViewController;

@interface StarkOverviewModeController : NSObject <MKMapViewDelegate, MNNavigationSessionUIDelegate, StarkDrivingNavigationItemDelegate, StarkChromeModeController> {

	id<MapsChromeViews> _views;
	/*^block*/id _completion;
	char _allowPouncingOnResignToNavigation;
	char _showsSearchResults;
	char _wasDisplayedByNavigation;
	char _initialCenteringComplete;
	StarkDrivingNavigationItem* _navigationItem;
	MNNavigationModeController* _drivingMode;
	SCD_Struct_RA13 _routeRemainingRect;
	char _resumeButtonHidden;
	char _haveZoomed;
	MapsChromeViewController* _chromeViewController;

}

@property (assign,nonatomic) char resumeButtonHidden;                                  //@synthesize resumeButtonHidden=_resumeButtonHidden - In the implementation block
@property (assign,nonatomic) char haveZoomed;                                          //@synthesize haveZoomed=_haveZoomed - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,__weak,readonly) UIView * preferredFocusedView; 
@property (assign,nonatomic) ChromeViewController * chromeViewController; 
-(char)shouldTimeoutAfterDisconnect;
-(ChromeViewController *)chromeViewController;
-(void)setChromeViewController:(ChromeViewController *)arg1 ;
-(void)navigationSession:(id)arg1 displayPrimaryStepManeuverType:(int)arg2 junctionType:(int)arg3 junctionElements:(SCD_Struct_Di20*)arg4 count:(unsigned long)arg5 instructions:(id)arg6 shorterAlternativeInstructions:(id)arg7 shieldType:(int)arg8 shieldText:(id)arg9 drivingSide:(int)arg10 maneuverStepIndex:(unsigned)arg11 isSynthetic:(char)arg12 ;
-(void)navigationSession:(id)arg1 currentStepIndex:(unsigned)arg2 distanceUntilManeuver:(double)arg3 timeUntilManeuver:(double)arg4 ;
-(void)navigationSession:(id)arg1 updateETA:(id)arg2 ;
-(void)directionsSessionUpdatedTrafficIncidents:(id)arg1 ;
-(void)navigationSession:(id)arg1 proceedToRouteDistance:(double)arg2 displayString:(id)arg3 eta:(id)arg4 closestStepIndex:(unsigned)arg5 ;
-(void)navigationSession:(id)arg1 startingStepIndex:(unsigned)arg2 ;
-(void)directionsSessionUpdatedETA:(id)arg1 ;
-(void)directionsSession:(id)arg1 didChangeRoutePreloadSession:(id)arg2 ;
-(void)navigationSession:(id)arg1 updatePointOfInterest:(SCD_Struct_RA7)arg2 focusStyle:(int)arg3 ;
-(void)directionsSessionDidCancelRoute:(id)arg1 ;
-(void)navigationSession:(id)arg1 ignoredLocation:(id)arg2 ;
-(void)directionsSession:(id)arg1 didSwitchToNewRoute:(id)arg2 ;
-(void)navigationSession:(id)arg1 didChangeState:(int)arg2 ;
-(void)directionsSessionDidCancelRecalculate:(id)arg1 ;
-(void)directionsSession:(id)arg1 didRecalculateNewRoute:(id)arg2 ;
-(void)navigationSession:(id)arg1 updatedMatchedLocation:(id)arg2 ;
-(void)directionsSessionWillRecalculateRoute:(id)arg1 ;
-(void)navigationSession:(id)arg1 failedWithErrorCode:(int)arg2 ;
-(void)directionsSessionDidFailToReceiveRoute:(id)arg1 error:(id)arg2 ;
-(void)directionsSessionWillRequestRoute:(id)arg1 ;
-(void)directionsSession:(id)arg1 didReceiveRouteSet:(id)arg2 ;
-(void)navigationSession:(id)arg1 didEnableGuidance:(char)arg2 ;
-(void)directionsSession:(id)arg1 didAppendRoutesInRouteSet:(id)arg2 ;
-(void)navigationSession:(id)arg1 willStartForRoute:(id)arg2 ;
-(void)navigationSessionWillEnd:(id)arg1 ;
-(void)directionsSessionDidFailToRecordTrace:(id)arg1 ;
-(void)navigationSessionDidStart:(id)arg1 ;
-(void)navigationSessionWillResumeNavigatorFromPause:(id)arg1 ;
-(void)directionsSession:(id)arg1 failedWithError:(id)arg2 ;
-(void)navigationSessionWillStopNavigator:(id)arg1 ;
-(void)navigationSession:(id)arg1 matchedToStepIndex:(unsigned)arg2 andLegIndex:(unsigned)arg3 ;
-(void)navigationSessionWillPauseNavigator:(id)arg1 ;
-(void)navigationSession:(id)arg1 willStartNavigatorForRoute:(id)arg2 ;
-(void)navigationSessionHasReachedEndOfLeg:(id)arg1 willContinueGuidance:(char)arg2 ;
-(void)navigationSessionHasArrived:(id)arg1 ;
-(void)navigationSessionTransportTypeChanged:(id)arg1 newTransportType:(int)arg2 ;
-(void)navigationSessionDetectedNewTransportType:(id)arg1 newTransportType:(int)arg2 ;
-(void)navigationSessionHideSecondaryStep:(id)arg1 ;
-(void)navigationSession:(id)arg1 displayManeuverAlertForAnnouncementStage:(unsigned)arg2 ;
-(void)navigationSession:(id)arg1 displaySecondaryStepManeuverType:(int)arg2 junctionType:(int)arg3 junctionElements:(SCD_Struct_Di20*)arg4 count:(unsigned long)arg5 instructions:(id)arg6 shorterAlternativeInstructions:(id)arg7 shieldType:(int)arg8 shieldText:(id)arg9 drivingSide:(int)arg10 ;
-(void)navigationSession:(id)arg1 etaDateString:(id)arg2 ;
-(id)starkChromeViewController;
-(id)overlayItemsForState:(id)arg1 ;
-(char)starkTopBarModifiesInsets;
-(void)updateMapForAutohidingContentChangeWithGroupAnimation:(id)arg1 ;
-(id)parentFocusEnvironment;
-(void)resignCurrentModeAnimated:(char)arg1 toMode:(id)arg2 ;
-(void)willProvideAnnotationView:(id)arg1 forAnnotation:(id)arg2 ;
-(void)layoutForUnobscuredBoundsChange;
-(char)pressesBegan:(id)arg1 ;
-(void)becomeCurrentModeWithViews:(id)arg1 animated:(char)arg2 state:(id)arg3 fromMode:(id)arg4 ;
-(UIEdgeInsets)_mapViewInsets;
-(void)_invokeCompletionWithOutcome:(int)arg1 ;
-(void)drivingNavigationItemDidToggleOverview:(id)arg1 ;
-(id)mapViewForDrivingNavigationItem:(id)arg1 ;
-(char)drivingNavigationItemAllowsZooming:(id)arg1 ;
-(void)drivingNavigationItemZoomOut:(id)arg1 ;
-(void)drivingNavigationItemZoomIn:(id)arg1 ;
-(void)drivingNavigationItemDidEndRoute:(id)arg1 ;
-(SCD_Struct_RA13)_boundingMapRectForLocation:(id)arg1 ;
-(char)_interactionModelAllowsResumeButton;
-(id)_defaultLocation;
-(void)setResumeButtonHidden:(char)arg1 ;
-(char)haveZoomed;
-(void)_routeMayHaveChanged;
-(void)_updateRouteRemainingRect;
-(void)setHaveZoomed:(char)arg1 ;
-(char)resumeButtonHidden;
-(id)initWithNavigationMode:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)navigationSession:(id)arg1 remainingTime:(double)arg2 remainingDistance:(double)arg3 distanceUntilManeuver:(double)arg4 timeUntilManeuver:(double)arg5 ;
-(void)_updateRoute:(id)arg1 ;
-(void)resumeNavigation;
-(void)_zoomByFactor:(float)arg1 ;
-(id)mapViewCurrentRouteMatch:(id)arg1 ;
-(void)mapView:(id)arg1 regionDidChangeAnimated:(char)arg2 ;
-(void)dealloc;
-(id)navigationItem;
-(void)setNeedsFocusUpdate;
-(UIView *)preferredFocusedView;
-(void)updateFocusIfNeeded;
-(char)shouldUpdateFocusInContext:(id)arg1 ;
-(void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2 ;
-(id)initWithCompletionHandler:(/*^block*/id)arg1 ;
@end

