/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:32 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/StarkButton.h>

@interface StarkFloatingButton : StarkButton {

	int _starkFloatingButtonStyle;

}

@property (assign,nonatomic) int starkFloatingButtonStyle;              //@synthesize starkFloatingButtonStyle=_starkFloatingButtonStyle - In the implementation block
-(int)starkFloatingButtonStyle;
-(void)setStarkFloatingButtonStyle:(int)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
@end

