/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:33 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/StarkWaypointsController.h>

@interface StarkExistingWaypointsController : StarkWaypointsController
-(char)shouldStartLoadWhenBecomingCurrent;
-(id)titleForCurrentDestination;
-(id)subtitleForCurrentDestination;
-(id)_address;
-(char)hasBothTitleAndAddress;
-(id)_titleOrName;
-(id)_waypoint;
@end

