/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:30 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/AuxiliaryDebugViewController.h>

@protocol MapsDebugViewControllerDelegate;
@class NSMutableArray;

@interface VectorKitDebugRenderController : AuxiliaryDebugViewController {

	NSMutableArray* _debugFeatureSwitches;
	NSMutableArray* _debugRoadSwitches;
	id<MapsDebugViewControllerDelegate> _delegate;

}
+(id)navigationDestinationTitle;
-(void)featureDisableSwitchChanged:(id)arg1 ;
-(void)roadClassDisableSwitchChanged:(id)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(id)delegate;
-(void)viewDidLoad;
@end

