/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:13:00 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SVSDataStoreEntry : NSObject {

	int _type;
	id _value;

}

@property (nonatomic,readonly) int type;              //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) id value;              //@synthesize value=_value - In the implementation block
-(id)_propertyListStringForType;
-(int)_typeForPropertyListString:(id)arg1 ;
-(id)initWithPropertyListRepresentation:(id)arg1 error:(id*)arg2 ;
-(id)_valuePropertyListRepresentation;
-(id)_valueForPropertyListRepresentation:(id)arg1 type:(int)arg2 ;
-(id)initWithType:(int)arg1 value:(id)arg2 ;
-(id)propertyListRepresentation;
-(int)type;
-(id)value;
@end

