/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:13:00 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SVSSiriViewControllerServing <NSObject,AFUISiriSessionDelegate,AFUISpeechSynthesisDelegate>
@required
-(void)siriDidActivateFromSource:(int)arg1;
-(void)didReceiveDismissalAction:(char)arg1 delayForTTS:(char)arg2 completion:(/*^block*/id)arg3;
-(void)setHostFrontMostAppOrientation:(int)arg1;
-(void)siriWillActivateFromSource:(int)arg1;
-(void)setRequestOptions:(id)arg1;
-(void)showPresentationWithIdentifier:(id)arg1 properties:(id)arg2;
-(void)siriDidDeactivate;
-(void)siriWillShowPasscodeUnlockAndCancelRequest:(char)arg1;
-(void)siriWillHidePasscodeUnlockForResult:(int)arg1;
-(void)siriDidHidePasscodeUnlock;
-(void)setStatusBarFrameValue:(id)arg1;
-(void)userInteractionDidOccur;
-(void)setSpeechSynthesis:(id)arg1;
-(void)didReceiveHelpAction;
-(void)didReceiveReportBugAction;
-(void)didReceiveBugButtonLongPress;
-(void)didReceiveShortTapAction;
-(void)siriWillShowPasscodeUnlock;
-(void)setSession:(id)arg1;

@end

