/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:59 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSUUID;


@protocol SVSStarkItemController <NSObject>
@property (assign,nonatomic,__weak) id<SVSStarkItemControllerDelegate> delegate; 
@property (assign,nonatomic) int interactionStyle; 
@property (nonatomic,copy) NSUUID * conversationItemIdentifier; 
@optional
-(void)updateAfterSpeechQueueEmpties;

@required
-(int)interactionStyle;
-(void)setInteractionStyle:(int)arg1;
-(void)setDelegate:(id)arg1;
-(id<SVSStarkItemControllerDelegate>)delegate;
-(char)isActive;
-(NSUUID *)conversationItemIdentifier;
-(void)setConversationItemIdentifier:(id)arg1;

@end

