/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:36 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol DDDetectionControllerDelegate
@optional
-(id)detectionController:(id)arg1 coreRecentsWeightForResult:(DDResultRef)arg2 fromScanQuery:(DDScanQueryRef)arg3 inContainer:(id)arg4 partOfSignature:(char)arg5;

@end

