/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:38 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MCSOperation.h>

@interface MCSMessageOperation : MCSOperation
-(id)localizedErrorDescriptionForMessageCount:(unsigned)arg1 ;
-(id)localizedErrorTitleForMessageCount:(unsigned)arg1 ;
-(id)localizedShortOperationDescription;
-(char)willMarkRead;
-(char)willMarkUnread;
-(char)willUnflag;
-(char)willFlag;
-(char)commitToMessages:(id)arg1 failures:(id)arg2 newMessages:(id)arg3 ;
-(char)revertOnMessages:(id)arg1 failures:(id)arg2 newMessages:(id)arg3 ;
-(char)isRevertibleWithMessages:(id)arg1 ;
@end

