/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:38 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface MessageSuggestionUtilities : NSObject
+(void)requestEventEditingControllerForRealtimeEvent:(id)arg1 inEventStore:(id)arg2 completion:(/*^block*/id)arg3 ;
+(id)confirmationForCanceledEvent:(id)arg1 handler:(/*^block*/id)arg2 ;
+(void)ignoreAction:(id)arg1 ;
+(id)iconStackImageForCallsToAction:(id)arg1 ;
+(void)requestEventEditingControllerForRealtimeEvent:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

