/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:37 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface MFMailDataProviderAutoFetchData : NSObject {

	char _bulletinExpectedFromFetch;
	NSString* _currentAccountIDOfSoundToPlay;
	unsigned _loudestState;
	unsigned long long _fetchStart;

}

@property (nonatomic,retain) NSString * currentAccountIDOfSoundToPlay;              //@synthesize currentAccountIDOfSoundToPlay=_currentAccountIDOfSoundToPlay - In the implementation block
@property (assign,nonatomic) unsigned loudestState;                                 //@synthesize loudestState=_loudestState - In the implementation block
@property (assign,nonatomic) char bulletinExpectedFromFetch;                        //@synthesize bulletinExpectedFromFetch=_bulletinExpectedFromFetch - In the implementation block
@property (assign,nonatomic) unsigned long long fetchStart;                         //@synthesize fetchStart=_fetchStart - In the implementation block
-(NSString *)currentAccountIDOfSoundToPlay;
-(void)setCurrentAccountIDOfSoundToPlay:(NSString *)arg1 ;
-(unsigned)loudestState;
-(void)setLoudestState:(unsigned)arg1 ;
-(char)bulletinExpectedFromFetch;
-(void)setBulletinExpectedFromFetch:(char)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setFetchStart:(unsigned long long)arg1 ;
-(unsigned long long)fetchStart;
@end

