/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:37 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MFMessageBulletinsObserverDelegate <NSObject>
@required
-(void)protectedDataBecameAvailableForNotificationService:(id)arg1;
-(void)messagesInvalidatedForNotificationService:(id)arg1;
-(void)invalidateSectionParametersForNotificationService:(id)arg1;
-(void)notificationService:(id)arg1 didChangeAccounts:(id)arg2 error:(id)arg3;
-(void)notificationService:(id)arg1 didFetchMessages:(id)arg2;
-(void)notificationService:(id)arg1 didFetchSummaryForMessages:(id)arg2;
-(void)notificationService:(id)arg1 didRemoveMessageIds:(id)arg2;

@end

