/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:39 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>
#import <MobileMail/MFAtomTextViewAtomLayout.h>

@class MFSearchSuggestion, _MFSearchAtomBackgroundView, UIImageView, UILabel, NSArray, NSString;

@interface MFSearchAtomView : UIView <MFAtomTextViewAtomLayout> {

	struct {
		unsigned enabled : 1;
		unsigned selected : 1;
	}  _flags;
	MFSearchSuggestion* _suggestion;
	_MFSearchAtomBackgroundView* _backgroundView;
	UIImageView* _leadingImage;
	UILabel* _textLabel;
	NSArray* _defaultConstraints;
	NSArray* _withImageConstraints;
	NSArray* _withoutImageConstraints;

}

@property (nonatomic,retain) MFSearchSuggestion * suggestion;                           //@synthesize suggestion=_suggestion - In the implementation block
@property (nonatomic,retain) _MFSearchAtomBackgroundView * backgroundView;              //@synthesize backgroundView=_backgroundView - In the implementation block
@property (nonatomic,retain) UIImageView * leadingImage;                                //@synthesize leadingImage=_leadingImage - In the implementation block
@property (nonatomic,retain) UILabel * textLabel;                                       //@synthesize textLabel=_textLabel - In the implementation block
@property (nonatomic,copy) NSArray * defaultConstraints;                                //@synthesize defaultConstraints=_defaultConstraints - In the implementation block
@property (nonatomic,copy) NSArray * withImageConstraints;                              //@synthesize withImageConstraints=_withImageConstraints - In the implementation block
@property (nonatomic,copy) NSArray * withoutImageConstraints;                           //@synthesize withoutImageConstraints=_withoutImageConstraints - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,getter=isEnabled,nonatomic) char enabled; 
@property (assign,getter=isSelected,nonatomic) char selected; 
@property (nonatomic,readonly) CGRect selectionBounds; 
+(char)requiresConstraintBasedLayout;
-(MFSearchSuggestion *)suggestion;
-(void)setSuggestion:(MFSearchSuggestion *)arg1 ;
-(float)_bottomMargin;
-(void)setDefaultConstraints:(NSArray *)arg1 ;
-(NSArray *)defaultConstraints;
-(CGRect)selectionBounds;
-(void)_updateImageColor;
-(float)_topToBaselineDelta;
-(void)setWithImageConstraints:(NSArray *)arg1 ;
-(void)setWithoutImageConstraints:(NSArray *)arg1 ;
-(UIImageView *)leadingImage;
-(void)setLeadingImage:(UIImageView *)arg1 ;
-(NSArray *)withImageConstraints;
-(NSArray *)withoutImageConstraints;
-(void)setSelected:(char)arg1 animated:(char)arg2 style:(int)arg3 ;
-(void)_updateTextColor;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setEnabled:(char)arg1 ;
-(char)isEnabled;
-(id)_font;
-(char)isSelected;
-(void)setBackgroundView:(_MFSearchAtomBackgroundView *)arg1 ;
-(void)setSelected:(char)arg1 ;
-(UILabel *)textLabel;
-(_MFSearchAtomBackgroundView *)backgroundView;
-(void)updateConstraints;
-(id)viewForLastBaselineLayout;
-(void)setEnabled:(char)arg1 animated:(char)arg2 ;
-(void)setTextLabel:(UILabel *)arg1 ;
@end

