/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:39 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@protocol MFSearchSuggestionsControllerDelegate;
@class _MFSearchSuggestionsTableViewModel, NSMutableSet;

@interface MFSearchSuggestionsController : UITableViewController {

	_MFSearchSuggestionsTableViewModel* _tableViewModel;
	NSMutableSet* _touchedCategories;
	id<MFSearchSuggestionsControllerDelegate> _delegate;

}

@property (assign,nonatomic) id<MFSearchSuggestionsControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) char hasSuggestions; 
+(/*^block*/id)categoryComparator;
-(void)beginUpdatingSuggestions;
-(void)clearSuggestions;
-(void)updateSuggestions:(id)arg1 categories:(id)arg2 ;
-(char)hasSuggestions;
-(void)endUpdatingSuggestions;
-(void)setTableViewModel:(id)arg1 animated:(char)arg2 ;
-(char)_delegateAllowsCategory:(id)arg1 cachedValues:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(id<MFSearchSuggestionsControllerDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(id<MFSearchSuggestionsControllerDelegate>)delegate;
-(id)initWithStyle:(int)arg1 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(id)initWithDelegate:(id)arg1 ;
@end

