/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:37 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableArray;

@interface MFSpringAnimationDelegate : NSObject {

	NSMutableArray* _completionBlocks;

}

@property (nonatomic,readonly) NSMutableArray * completionBlocks;              //@synthesize completionBlocks=_completionBlocks - In the implementation block
-(void)dealloc;
-(id)init;
-(void)animationDidStop:(id)arg1 finished:(char)arg2 ;
-(NSMutableArray *)completionBlocks;
@end

