/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:38 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NNMKSyncProviderDelegate <NSObject>
@required
-(void)syncProvider:(id)arg1 didUpdateMessagesStatus:(id)arg2;
-(void)syncProviderDidRequestAccounts:(id)arg1;
-(void)syncProvider:(id)arg1 didRequestMessagesBeforeDate:(id)arg2 count:(unsigned)arg3;
-(void)syncProvider:(id)arg1 didRequestMessagesBeforeDate:(id)arg2 count:(unsigned)arg3 forConversationWithId:(id)arg4;
-(void)syncProvider:(id)arg1 didRequestFirstMessages:(unsigned)arg2;
-(void)syncProvider:(id)arg1 didRequestContentForMessageWithId:(id)arg2 highPriority:(char)arg3;
-(void)syncProvider:(id)arg1 didRequestStopDownloadingContentAndAttachmentsForMessageWithId:(id)arg2;
-(void)syncProviderDidRequestStopDownloadingAllContentAndAttachments:(id)arg1;
-(void)syncProviderDidRequestFetchResume:(id)arg1;
-(void)syncProviderDidRequestFetchManual:(id)arg1 forConversationId:(id)arg2;
-(void)syncProvider:(id)arg1 didRequestSendComposedMessage:(id)arg2;
-(void)syncProvider:(id)arg1 didRequestResendMessagesWithIds:(id)arg2;
-(void)syncProvider:(id)arg1 didRequestResendAccountWithId:(id)arg2;
-(void)syncProvider:(id)arg1 didRequestVerificationOfMessagesAndIds:(id)arg2 afterDate:(id)arg3;

@end

