/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:39 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSMutableCopying.h>

@class NSString, NSArray, MFMessageCriterion, MFSparseMutable64IndexSet;

@interface SourceSearchContext : NSObject <NSCopying, NSMutableCopying> {

	char _shouldSearchAllMail;
	NSString* _searchText;
	NSArray* _searchTerms;
	MFMessageCriterion* _criterion;

}

@property (nonatomic,copy) NSString * searchText;                                                     //@synthesize searchText=_searchText - In the implementation block
@property (nonatomic,copy) NSArray * searchTerms;                                                     //@synthesize searchTerms=_searchTerms - In the implementation block
@property (nonatomic,retain) MFMessageCriterion * criterion;                                          //@synthesize criterion=_criterion - In the implementation block
@property (assign,nonatomic) char shouldSearchAllMail;                                                //@synthesize shouldSearchAllMail=_shouldSearchAllMail - In the implementation block
@property (nonatomic,copy,readonly) NSArray * referencedMailboxes; 
@property (nonatomic,copy,readonly) MFSparseMutable64IndexSet * referencedConversations; 
-(NSArray *)referencedMailboxes;
-(MFSparseMutable64IndexSet *)referencedConversations;
-(void)setShouldSearchAllMail:(char)arg1 ;
-(char)shouldSearchAllMail;
-(void)setSearchText:(NSString *)arg1 ;
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(NSString *)searchText;
-(void)setSearchTerms:(NSArray *)arg1 ;
-(NSArray *)searchTerms;
-(MFMessageCriterion *)criterion;
-(void)setCriterion:(MFMessageCriterion *)arg1 ;
@end

