/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:13:03 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIAnimation.h>

@protocol WAAnimationDelegate;
@interface WAAnimation : UIAnimation {

	double _w0;
	double _zeta;
	double _wd;
	double _A;
	double _B;
	id<WAAnimationDelegate> _wa_delegate;
	double _animationDuration;

}

@property (assign,nonatomic,__weak) id<WAAnimationDelegate> wa_delegate;              //@synthesize wa_delegate=_wa_delegate - In the implementation block
@property (assign,nonatomic) double animationDuration;                                //@synthesize animationDuration=_animationDuration - In the implementation block
-(id<WAAnimationDelegate>)wa_delegate;
-(void)setWa_delegate:(id<WAAnimationDelegate>)arg1 ;
-(void)setAnimationDuration:(double)arg1 ;
-(void)setProgress:(float)arg1 ;
-(id)initWithTarget:(id)arg1 ;
-(float)progressForFraction:(float)arg1 ;
-(double)animationDuration;
-(float)eval:(float)arg1 ;
@end

