/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:11 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/HomeUIService.app/HomeUIService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <libobjc.A.dylib/CRCameraReaderDelegate.h>
#import <HomeUIService/HSSetupStep.h>

@protocol HSSetupStepDelegate;
@class UIView, CRCameraReader, UILabel, HSSetupCodeView, UIButton, NSString;

@interface HSSetupCameraViewController : UIViewController <CRCameraReaderDelegate, HSSetupStep> {

	char _dismissOnFailure;
	UIView* _cameraContainerView;
	CRCameraReader* _cameraReader;
	UILabel* _interruptionLabel;
	HSSetupCodeView* _setupCodeView;
	UIButton* _actionButton;
	unsigned _backgroundTaskIdentifier;
	id<HSSetupStepDelegate> _delegate;

}

@property (nonatomic,retain) UIView * cameraContainerView;                         //@synthesize cameraContainerView=_cameraContainerView - In the implementation block
@property (nonatomic,retain) CRCameraReader * cameraReader;                        //@synthesize cameraReader=_cameraReader - In the implementation block
@property (nonatomic,retain) UILabel * interruptionLabel;                          //@synthesize interruptionLabel=_interruptionLabel - In the implementation block
@property (nonatomic,retain) HSSetupCodeView * setupCodeView;                      //@synthesize setupCodeView=_setupCodeView - In the implementation block
@property (nonatomic,retain) UIButton * actionButton;                              //@synthesize actionButton=_actionButton - In the implementation block
@property (assign,nonatomic) unsigned backgroundTaskIdentifier;                    //@synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier - In the implementation block
@property (assign,nonatomic,__weak) id<HSSetupStepDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char dismissOnFailure;                                //@synthesize dismissOnFailure=_dismissOnFailure - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(HSSetupCodeView *)setupCodeView;
-(void)setupDidFailWithError:(id)arg1 ;
-(void)setDismissOnFailure:(char)arg1 ;
-(void)_configureCloseButton;
-(char)dismissOnFailure;
-(void)setupDidSucceed;
-(void)setupDidDisconnect;
-(void)setupDidBackground;
-(void)setSetupCodeView:(HSSetupCodeView *)arg1 ;
-(void)_configureManualEntryButton;
-(void)_cameraWasInterrupted:(id)arg1 ;
-(void)_loadCameraReader;
-(CRCameraReader *)cameraReader;
-(void)setCameraReader:(CRCameraReader *)arg1 ;
-(UIView *)cameraContainerView;
-(void)_addInterruptionLabel;
-(UILabel *)interruptionLabel;
-(void)setInterruptionLabel:(UILabel *)arg1 ;
-(void)showManualCodeUI:(id)arg1 ;
-(void)_unloadCameraReader;
-(void)_handleSetupCode:(id)arg1 ;
-(void)setCameraContainerView:(UIView *)arg1 ;
-(UIButton *)actionButton;
-(void)cameraReaderDidCancel:(id)arg1 ;
-(void)cameraReaderDidEnd:(id)arg1 ;
-(void)cameraReader:(id)arg1 didFailWithError:(id)arg2 ;
-(void)cameraReaderDidDisplayMessage:(id)arg1 ;
-(void)cameraReaderDidFindTarget:(id)arg1 ;
-(void)cameraReader:(id)arg1 didRecognizeObjects:(id)arg2 ;
-(void)setDelegate:(id<HSSetupStepDelegate>)arg1 ;
-(id<HSSetupStepDelegate>)delegate;
-(int)preferredStatusBarStyle;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewWillDisappear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)_prepareConstraints;
-(void)setBackgroundTaskIdentifier:(unsigned)arg1 ;
-(unsigned)backgroundTaskIdentifier;
-(void)updateUI;
-(void)setActionButton:(UIButton *)arg1 ;
-(void)cancel:(id)arg1 ;
@end

