/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:11 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/HomeUIService.app/HomeUIService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <HomeUIService/HomeUIService-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UITextFieldDelegate.h>

@protocol HSSetupCodeFieldDelegate;
@class NSArray, HSSetupCodeFieldItem, UITextField, NSString;

@interface HSSetupCodeField : UIView <UITextFieldDelegate> {

	id<HSSetupCodeFieldDelegate> _delegate;
	NSArray* _items;
	HSSetupCodeFieldItem* _activeItem;
	float _itemSpacing;
	float _sectionSpacing;
	NSArray* _itemSequence;
	UITextField* _hiddenInputField;

}

@property (assign,nonatomic,__weak) id<HSSetupCodeFieldDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSArray * items;                                         //@synthesize items=_items - In the implementation block
@property (assign,nonatomic,__weak) HSSetupCodeFieldItem * activeItem;                  //@synthesize activeItem=_activeItem - In the implementation block
@property (assign,nonatomic) float itemSpacing;                                         //@synthesize itemSpacing=_itemSpacing - In the implementation block
@property (assign,nonatomic) float sectionSpacing;                                      //@synthesize sectionSpacing=_sectionSpacing - In the implementation block
@property (nonatomic,readonly) NSString * setupCode; 
@property (getter=isComplete,nonatomic,readonly) char complete; 
@property (nonatomic,retain) NSArray * itemSequence;                                    //@synthesize itemSequence=_itemSequence - In the implementation block
@property (nonatomic,retain) UITextField * hiddenInputField;                            //@synthesize hiddenInputField=_hiddenInputField - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)hideKeypad;
-(void)showKeypad;
-(NSString *)setupCode;
-(void)fieldTapped:(id)arg1 ;
-(HSSetupCodeFieldItem *)activeItem;
-(void)setActiveItem:(HSSetupCodeFieldItem *)arg1 ;
-(UITextField *)hiddenInputField;
-(NSArray *)itemSequence;
-(float)sectionSpacing;
-(void)_activateNext;
-(void)_activateLast;
-(void)setSectionSpacing:(float)arg1 ;
-(void)setItemSequence:(NSArray *)arg1 ;
-(void)setHiddenInputField:(UITextField *)arg1 ;
-(char)isComplete;
-(void)setDelegate:(id<HSSetupCodeFieldDelegate>)arg1 ;
-(id)init;
-(id<HSSetupCodeFieldDelegate>)delegate;
-(NSArray *)items;
-(char)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(char)textFieldShouldReturn:(id)arg1 ;
-(void)setItemSpacing:(float)arg1 ;
-(float)itemSpacing;
-(void)clear;
-(void)_prepareConstraints;
@end

