/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:09 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <GameCenterPrivateUI/GKSimpleComposeController.h>

@class GKComposeHeaderField, GKChallenge, NSArray;

@interface GKChallengeComposeController : GKSimpleComposeController {

	GKComposeHeaderField* _challengeField;
	GKChallenge* _challenge;
	NSArray* _playersToLoad;

}

@property (nonatomic,retain) GKComposeHeaderField * challengeField;              //@synthesize challengeField=_challengeField - In the implementation block
@property (nonatomic,retain) GKChallenge * challenge;                            //@synthesize challenge=_challenge - In the implementation block
@property (nonatomic,retain) NSArray * playersToLoad;                            //@synthesize playersToLoad=_playersToLoad - In the implementation block
+(id)friendPickerFlowForChallenge:(id)arg1 selectPlayers:(id)arg2 defaultMessage:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
+(id)composeFlowForChallenge:(id)arg1 players:(id)arg2 defaultMessage:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
+(void)composeAndSendFlowForChallenge:(id)arg1 selectPlayers:(id)arg2 defaultMessage:(id)arg3 forcePicker:(char)arg4 readyHandler:(/*^block*/id)arg5 completionHandler:(/*^block*/id)arg6 ;
-(id)initWithChallenge:(id)arg1 defaultMessage:(id)arg2 players:(id)arg3 ;
-(void)setPlayersToLoad:(NSArray *)arg1 ;
-(void)setChallengeField:(GKComposeHeaderField *)arg1 ;
-(void)updateChallengeText;
-(GKComposeHeaderField *)challengeField;
-(NSArray *)playersToLoad;
-(void)cancel;
-(void)dealloc;
-(id)init;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)donePressed;
-(GKChallenge *)challenge;
-(void)setChallenge:(GKChallenge *)arg1 ;
@end

