/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:08 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Game Center/Game Center-Structs.h>
#import <GameCenterPrivateUI/GKCollectionViewCell.h>

@class GKGame, GKPlayer, GKLabel, GKHairlineView;

@interface GKFriendPlaySuggestionCell : GKCollectionViewCell {

	GKGame* _game;
	GKPlayer* _friend;
	GKLabel* _titleLabel;
	GKHairlineView* _underlineView;

}

@property (nonatomic,retain) GKGame * game;                               //@synthesize game=_game - In the implementation block
@property (nonatomic,retain) GKPlayer * friend;                           //@synthesize friend=_friend - In the implementation block
@property (nonatomic,retain) GKLabel * titleLabel;                        //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) GKHairlineView * underlineView;              //@synthesize underlineView=_underlineView - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(GKLabel *)titleLabel;
-(void)setTitleLabel:(GKLabel *)arg1 ;
-(void)setGame:(GKGame *)arg1 ;
-(GKGame *)game;
-(GKHairlineView *)underlineView;
-(void)setUnderlineView:(GKHairlineView *)arg1 ;
-(GKPlayer *)friend;
-(void)setFriend:(GKPlayer *)arg1 ;
@end

