/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:08 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Game Center/Game Center-Structs.h>
#import <GameCenterPrivateUI/GKCollectionViewController.h>
#import <UIKit/UIPopoverPresentationControllerDelegate.h>
#import <UIKit/UICollectionViewDelegate.h>

@protocol GKScoreDetailDelegate;
@class NSString, GKPlayer, GKLeaderboard, GKGameRecord, GKLeaderboardScoresDataSource;

@interface GKLeaderboardScoresViewController : GKCollectionViewController <UIPopoverPresentationControllerDelegate, UICollectionViewDelegate> {

	int _timeScope;
	NSString* _noScoresMessage;
	id<GKScoreDetailDelegate> _scoreDetailDelegate;
	unsigned _controllerMode;
	GKPlayer* _player;
	GKLeaderboard* _leaderboard;
	GKGameRecord* _game;
	GKLeaderboardScoresDataSource* _friendsDataSource;
	GKLeaderboardScoresDataSource* _globalDataSource;
	int _numberOfLeaderboardColumns;
	NSRange _shownRange;

}

@property (assign,nonatomic) int timeScope;                                                  //@synthesize timeScope=_timeScope - In the implementation block
@property (nonatomic,readonly) NSString * noScoresMessage;                                   //@synthesize noScoresMessage=_noScoresMessage - In the implementation block
@property (assign,nonatomic) id<GKScoreDetailDelegate> scoreDetailDelegate;                  //@synthesize scoreDetailDelegate=_scoreDetailDelegate - In the implementation block
@property (assign,nonatomic) unsigned controllerMode;                                        //@synthesize controllerMode=_controllerMode - In the implementation block
@property (nonatomic,retain) GKPlayer * player;                                              //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) GKLeaderboard * leaderboard;                                    //@synthesize leaderboard=_leaderboard - In the implementation block
@property (nonatomic,retain) GKGameRecord * game;                                            //@synthesize game=_game - In the implementation block
@property (nonatomic,retain) GKLeaderboardScoresDataSource * friendsDataSource;              //@synthesize friendsDataSource=_friendsDataSource - In the implementation block
@property (nonatomic,retain) GKLeaderboardScoresDataSource * globalDataSource;               //@synthesize globalDataSource=_globalDataSource - In the implementation block
@property (assign,nonatomic) NSRange shownRange;                                             //@synthesize shownRange=_shownRange - In the implementation block
@property (assign,nonatomic) int numberOfLeaderboardColumns;                                 //@synthesize numberOfLeaderboardColumns=_numberOfLeaderboardColumns - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithLeaderboard:(id)arg1 game:(id)arg2 player:(id)arg3 ;
-(int)numberOfLeaderboardColumns;
-(void)didTouchTimeScope:(id)arg1 ;
-(void)updateShowcaseCellMetrics;
-(void)didTouchShowcaseFriends:(id)arg1 ;
-(void)didTouchShowMoreFriends:(id)arg1 ;
-(void)addShowcaseCellToMetrics:(id)arg1 ;
-(void)didTouchShowcaseGlobal:(id)arg1 ;
-(void)didTouchShowMoreGlobal:(id)arg1 ;
-(void)setGlobalDataSource:(GKLeaderboardScoresDataSource *)arg1 ;
-(GKLeaderboardScoresDataSource *)globalDataSource;
-(void)showScore:(id)arg1 fromCell:(id)arg2 leaderboard:(id)arg3 ;
-(void)setNumberOfLeaderboardColumns:(int)arg1 ;
-(NSString *)noScoresMessage;
-(id<GKScoreDetailDelegate>)scoreDetailDelegate;
-(void)setScoreDetailDelegate:(id<GKScoreDetailDelegate>)arg1 ;
-(unsigned)controllerMode;
-(void)setControllerMode:(unsigned)arg1 ;
-(NSRange)shownRange;
-(void)setShownRange:(NSRange)arg1 ;
-(void)setPlayer:(GKPlayer *)arg1 ;
-(GKPlayer *)player;
-(void)dealloc;
-(void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2 ;
-(id)title;
-(void)loadView;
-(void)popoverPresentationControllerDidDismissPopover:(id)arg1 ;
-(void)popoverPresentationController:(id)arg1 willRepositionPopoverToRect:(inout CGRect*)arg2 inView:(inout id*)arg3 ;
-(GKLeaderboard *)leaderboard;
-(void)setLeaderboard:(GKLeaderboard *)arg1 ;
-(void)configureDataSource;
-(void)didEnterNoContentState;
-(void)updateDynamicColumnCountsForViewSize:(CGSize)arg1 ;
-(void)updateMetrics;
-(void)didExitRefreshingState;
-(void)setGame:(GKGameRecord *)arg1 ;
-(GKGameRecord *)game;
-(int)timeScope;
-(void)setTimeScope:(int)arg1 ;
-(GKLeaderboardScoresDataSource *)friendsDataSource;
-(void)setFriendsDataSource:(GKLeaderboardScoresDataSource *)arg1 ;
@end

