/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:08 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Game Center/Game Center-Structs.h>
#import <Game Center/GKProfileViewController.h>

@class GKPlayer, GKPlayerProfileHeaderView, GKValueWithCaptionBubbleControl;

@interface GKPlayerProfileBubbleViewController : GKProfileViewController {

	GKPlayer* _player;
	GKPlayerProfileHeaderView* _headerView;
	GKValueWithCaptionBubbleControl* _gamesBubble;
	GKValueWithCaptionBubbleControl* _pointsBubble;
	GKValueWithCaptionBubbleControl* _friendsBubble;
	CGSize _sizeToWhichViewIsTransitioning;

}

@property (nonatomic,retain) GKPlayer * player;                                           //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) GKPlayerProfileHeaderView * headerView;                      //@synthesize headerView=_headerView - In the implementation block
@property (retain,readonly) GKValueWithCaptionBubbleControl * gamesBubble;                //@synthesize gamesBubble=_gamesBubble - In the implementation block
@property (retain,readonly) GKValueWithCaptionBubbleControl * pointsBubble;               //@synthesize pointsBubble=_pointsBubble - In the implementation block
@property (retain,readonly) GKValueWithCaptionBubbleControl * friendsBubble;              //@synthesize friendsBubble=_friendsBubble - In the implementation block
@property (assign,nonatomic) CGSize sizeToWhichViewIsTransitioning;                       //@synthesize sizeToWhichViewIsTransitioning=_sizeToWhichViewIsTransitioning - In the implementation block
+(Class)headerViewClass;
-(GKValueWithCaptionBubbleControl *)gamesBubble;
-(GKValueWithCaptionBubbleControl *)friendsBubble;
-(GKValueWithCaptionBubbleControl *)pointsBubble;
-(void)didTouchGamesBubble;
-(void)didTouchPointsBubble;
-(void)didTouchFriendsBubble;
-(void)setAccentColor:(id)arg1 ;
-(void)setSizeToWhichViewIsTransitioning:(CGSize)arg1 ;
-(void)_updateTextForBubbleOfType:(int)arg1 ;
-(CGSize)sizeToWhichViewIsTransitioning;
-(void)setPlayer:(GKPlayer *)arg1 ;
-(GKPlayer *)player;
-(void)dealloc;
-(id)init;
-(void)loadView;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(GKPlayerProfileHeaderView *)headerView;
-(void)setHeaderView:(GKPlayerProfileHeaderView *)arg1 ;
-(void)didUpdateModel;
-(void)configureControlForBubble:(id)arg1 ;
@end

