/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:56 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AdSheet/ADJavaScriptObject.h>
#import <libobjc.A.dylib/ABNewPersonViewControllerDelegate.h>
#import <AdSheet/ADContactsJSO_Bindings.h>

@class NSDictionary, NSString;

@interface ADContactsJSO : ADJavaScriptObject <ABNewPersonViewControllerDelegate, ADContactsJSO_Bindings> {

	char _readyToPresent;
	void* _contactRecord;

}

@property (assign,nonatomic) void* contactRecord;                   //@synthesize contactRecord=_contactRecord - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) char readyToPresent;                 //@synthesize readyToPresent=_readyToPresent - In the implementation block
@property (nonatomic,copy) NSDictionary * contactInfo; 
+(void)initializeInContext:(id)arg1 ;
-(void)setContactRecord:(void*)arg1 ;
-(void)presentComposer;
-(char)readyToPresent;
-(void*)contactRecord;
-(void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(void*)arg2 ;
-(void)dealloc;
-(NSDictionary *)contactInfo;
-(void)setContactInfo:(NSDictionary *)arg1 ;
@end

