/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:57 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class _ADLocationPermissionRequest, NSMutableArray, NSObject, NSMutableDictionary, NSFileManager;

@interface ADLocationPermissionManager : NSObject {

	_ADLocationPermissionRequest* _currentRequest;
	NSMutableArray* _pendingRequests;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	NSMutableDictionary* _cache;
	NSFileManager* _fileManager;

}

@property (nonatomic,retain) _ADLocationPermissionRequest * currentRequest;              //@synthesize currentRequest=_currentRequest - In the implementation block
@property (nonatomic,retain) NSMutableArray * pendingRequests;                           //@synthesize pendingRequests=_pendingRequests - In the implementation block
@property (assign,nonatomic) NSObject*<OS_dispatch_queue> dispatchQueue;                 //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * cache;                                //@synthesize cache=_cache - In the implementation block
@property (nonatomic,retain) NSFileManager * fileManager;                                //@synthesize fileManager=_fileManager - In the implementation block
+(void)cancelOutstandingRequests;
+(void)clearPermissionCache;
+(void)allowLocationAccessForAdWithIdentifier:(id)arg1 title:(id)arg2 queue:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
+(id)sharedManager;
-(void)_enqueueRequestForAdWithIdentifier:(id)arg1 title:(id)arg2 queue:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)_cancelOutstandingRequests;
-(void)_clearPermissionCache;
-(char)_hasPermissionForAdWithIdentifier:(id)arg1 ;
-(void)_recordPermissionForAdWithIdentifier:(id)arg1 ;
-(void)_checkPendingRequests;
-(void)setCurrentRequest:(_ADLocationPermissionRequest *)arg1 ;
-(id)init;
-(NSMutableDictionary *)cache;
-(void)setCache:(NSMutableDictionary *)arg1 ;
-(_ADLocationPermissionRequest *)currentRequest;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSMutableArray *)pendingRequests;
-(void)setPendingRequests:(NSMutableArray *)arg1 ;
-(NSFileManager *)fileManager;
-(void)setFileManager:(NSFileManager *)arg1 ;
@end

