/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:57 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ADSOptInConnection_RPC
@required
-(void)refreshOptInStatus;
-(void)handleAccountChange;
-(void)getiAdIDsWithCompletionHandler:(/*^block*/id)arg1;
-(void)refreshOptInStatusRefreshingWeakToken:(char)arg1 withCompletionHandler:(/*^block*/id)arg2;
-(void)setOptInStatus:(char)arg1 completionHandler:(/*^block*/id)arg2;

@end

