/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:11:57 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSURL, UIImage;

@interface ADTwitterImageRecord : NSObject {

	NSURL* _URL;
	UIImage* _image;

}

@property (nonatomic,copy) NSURL * URL;                    //@synthesize URL=_URL - In the implementation block
@property (nonatomic,retain) UIImage * image;              //@synthesize image=_image - In the implementation block
-(void)setImage:(UIImage *)arg1 ;
-(void)dealloc;
-(UIImage *)image;
-(NSURL *)URL;
-(void)setURL:(NSURL *)arg1 ;
@end

