/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:48 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <MobileTimer/StateManagement.h>
#import <MobileTimer/StopWatchControlsTarget.h>

@class MTStopwatchControlsView, StopwatchPadControls, UITableView, CADisplayLink, NSDate, NSMutableArray, NSTimer, NSUserActivity, NSString;

@interface StopWatchViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, StateManagement, StopWatchControlsTarget> {

	MTStopwatchControlsView* _lapControls;
	StopwatchPadControls* _padControls;
	UITableView* _lapTimeTable;
	CADisplayLink* _displayLink;
	NSDate* _startTime;
	double _offset;
	double _currentInterval;
	double _previousLapsTotalInterval;
	NSMutableArray* _laps;
	char _isTimerRunning;
	NSTimer* _restoreIdleTimerTimer;
	int _mode;
	int _style;
	NSUserActivity* _userActivity;
	float _estimatedRowHeight;

}

@property (assign,nonatomic) float estimatedRowHeight;              //@synthesize estimatedRowHeight=_estimatedRowHeight - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)updateShortcutItemForCurrentState;
-(void)_updateTableWithRowAndEstimatedRowHeight;
-(void)_restoreIdleTimer;
-(void)_clearAllLaps;
-(void)_addLap:(double)arg1 ;
-(id)shortcutItemForCurrentState;
-(id)shortcutItemForMode:(int)arg1 ;
-(id)startStopwatchShortcutItemForMode:(int)arg1 ;
-(id)stopStopwatchShortcutItem;
-(void)pauseLapTimer;
-(double)_timeAdjustedFor30fpsDisplay:(double)arg1 ;
-(unsigned)_placeholderCellCount;
-(double)runningTotalForLap:(int)arg1 ;
-(void)startLapTimer;
-(void)resumeLapTimer;
-(void)lapLapTimer;
-(void)resetLapTimer;
-(id)defaultShortcutItem;
-(void)handleStartStopwatchShortcutAction;
-(void)handleStopStopwatchShortcutAction;
-(void)_tick:(id)arg1 ;
-(void)saveState;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(char)prefersStatusBarHidden;
-(void)loadView;
-(void)viewDidLayoutSubviews;
-(void)setStyle:(int)arg1 ;
-(void)setEstimatedRowHeight:(float)arg1 ;
-(float)estimatedRowHeight;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(id)defaultPNGName;
-(void)setMode:(int)arg1 ;
-(void)_startTimer;
-(void)_stopTimer;
-(void)updateTime;
-(void)reloadState;
-(Class)tableCellClass;
-(void)handleLocaleChange;
@end

