/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:48 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UILabel, UIView, MTStopwatchController;

@interface StopwatchPadControls : UIView {

	UILabel* _timeLabel;
	UILabel* _currentLapTimeLabel;
	UIView* _middleKeylineView;
	UIView* _bottomKeylineView;
	UIView* _buttonsBackgroundView;
	MTStopwatchController* _controller;
	double _time;
	double _currentLapTime;

}

@property (assign,nonatomic) double time;                        //@synthesize time=_time - In the implementation block
@property (assign,nonatomic) double currentLapTime;              //@synthesize currentLapTime=_currentLapTime - In the implementation block
-(double)currentLapTime;
-(void)setCurrentLapTime:(double)arg1 ;
-(char)shouldUsePortraitLayout;
-(void)_configureAndAddButton:(id)arg1 ;
-(void)setButtonSize:(unsigned)arg1 ;
-(void)layoutSubviews;
-(float)defaultHeight;
-(id)target;
-(id)initWithTarget:(id)arg1 ;
-(void)setMode:(int)arg1 ;
-(int)mode;
-(void)setTime:(double)arg1 ;
-(double)time;
-(void)handleLocaleChange;
@end

