/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:48 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@protocol WorldClockCollectionEditDelegate;
@class UIButton;

@interface WeatherAttributionView : UIView {

	id<WorldClockCollectionEditDelegate> _delegate;
	UIButton* _twcButton;

}

@property (assign,nonatomic,__weak) id<WorldClockCollectionEditDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIButton * twcButton;                                              //@synthesize twcButton=_twcButton - In the implementation block
-(UIButton *)twcButton;
-(void)_twcLogoTapped;
-(void)setTwcButton:(UIButton *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<WorldClockCollectionEditDelegate>)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<WorldClockCollectionEditDelegate>)delegate;
@end

