/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:44 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobilePhone/PHStarkGenericTableViewCell.h>

@class VMVoicemail, UILabel, NSLayoutConstraint, UIDateLabel, UIImageView;

@interface PHStarkVoicemailTableViewCell : PHStarkGenericTableViewCell {

	VMVoicemail* _representedVoicemail;
	UILabel* _nameLabel;
	NSLayoutConstraint* _nameLabelBaselineConstraint;
	UILabel* _subtitleLabel;
	UIDateLabel* _dateLabel;
	UIImageView* _unreadIndicatorImageView;

}

@property (nonatomic,retain) VMVoicemail * representedVoicemail;                  //@synthesize representedVoicemail=_representedVoicemail - In the implementation block
@property (retain) UILabel * nameLabel;                                           //@synthesize nameLabel=_nameLabel - In the implementation block
@property (retain) NSLayoutConstraint * nameLabelBaselineConstraint;              //@synthesize nameLabelBaselineConstraint=_nameLabelBaselineConstraint - In the implementation block
@property (retain) UILabel * subtitleLabel;                                       //@synthesize subtitleLabel=_subtitleLabel - In the implementation block
@property (retain) UIDateLabel * dateLabel;                                       //@synthesize dateLabel=_dateLabel - In the implementation block
@property (retain) UIImageView * unreadIndicatorImageView;                        //@synthesize unreadIndicatorImageView=_unreadIndicatorImageView - In the implementation block
-(void)setRepresentedVoicemail:(VMVoicemail *)arg1 ;
-(void)setUnreadIndicatorImageView:(UIImageView *)arg1 ;
-(UIImageView *)unreadIndicatorImageView;
-(void)setNameLabelBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)nameLabelBaselineConstraint;
-(void)updatePendingState;
-(void)_voicemailFlagsDidChangeNotification:(id)arg1 ;
-(VMVoicemail *)representedVoicemail;
-(UILabel *)nameLabel;
-(void)setNameLabel:(UILabel *)arg1 ;
-(void)setDateLabel:(UIDateLabel *)arg1 ;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)prepareForReuse;
-(UILabel *)subtitleLabel;
-(void)setSubtitleLabel:(UILabel *)arg1 ;
-(void)setSubtitleString:(id)arg1 ;
-(UIDateLabel *)dateLabel;
-(void)setPendingState:(char)arg1 ;
@end

