/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:44 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobilePhone/PHStarkGenericTableViewController.h>

@class CHManager;

@interface PHStarkRecentsViewController : PHStarkGenericTableViewController {

	CHManager* _recentsManager;

}

@property (retain) CHManager * recentsManager;              //@synthesize recentsManager=_recentsManager - In the implementation block
-(void)recentsManagerSignificantChangeNotification:(id)arg1 ;
-(CHManager *)recentsManager;
-(void)programmaticallySelectRowAtIndexPath:(id)arg1 ;
-(id)titleForNoContentBanner;
-(id)subtitleForNoContentBanner;
-(void)setRecentsManager:(CHManager *)arg1 ;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)viewDidLoad;
-(void)viewDidDisappear:(char)arg1 ;
-(id)badgeString;
-(float)defaultRowHeight;
@end

