/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 6, 2015 at 5:12:43 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobilePhone/MobilePhone-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <libobjc.A.dylib/MPDetailSliderDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol PHVoicemailCellConfigurationDelegate, PHVoicemailCellDelegate;
@class UIImageView, UILabel, UIDateLabel, UIButton, PHVoicemailSlider, UIView, NSMutableArray, NSLayoutConstraint, UIGestureRecognizer, VMVoicemail, NSString, NSDate;

@interface PHVoicemailCell : UITableViewCell <MPDetailSliderDelegate, UIGestureRecognizerDelegate> {

	UIImageView* _unreadIndicatorView;
	UILabel* _nameLabel;
	UILabel* _labelLabel;
	UILabel* _durationLabel;
	UIDateLabel* _dateLabel;
	UILabel* _longDateLabel;
	UIButton* _playPauseButton;
	PHVoicemailSlider* _sliderView;
	UIButton* _speakerButton;
	UIButton* _callBackButton;
	UIButton* _deleteButton;
	UIButton* _infoButton;
	UIButton* _shareButton;
	UIView* _infoBox;
	long _createConstraintsOnceToken;
	NSMutableArray* _calculatedConstraints;
	NSMutableArray* _playbackConstraints;
	NSLayoutConstraint* _nameLabelYConstraint;
	NSLayoutConstraint* _labelLabelYConstraint;
	NSLayoutConstraint* _durationLabelEdgeConstraint;
	NSLayoutConstraint* _infoBoxCenterConstraint;
	NSLayoutConstraint* _infoButtonXConstraint;
	NSLayoutConstraint* _infoButtonYConstraint;
	NSLayoutConstraint* _unreadIndicatorYConstraint;
	NSLayoutConstraint* _playPauseAndControlsYConstraint;
	NSLayoutConstraint* _buttonsYConstraint;
	NSLayoutConstraint* _unreadIndicatorXConstraint;
	NSLayoutConstraint* _expandedHeightConstraint;
	char _animatingUpdateToUnreadIndicator;
	char _shouldReupdateUnreadIndicator;
	char _playWhenAvailable;
	char _trackingTouchInCloseVoicemailArea;
	UIGestureRecognizer* _closeVoicemailGestureRecognizer;
	char _showingPlayController;
	char _didSwipe;
	VMVoicemail* _voicemail;
	id<PHVoicemailCellConfigurationDelegate> _configurationDelegate;
	id<PHVoicemailCellDelegate> _delegate;
	NSString* _pickedRoute;
	NSString* _pickedRouteUID;

}

@property (nonatomic,readonly) NSString * nameString; 
@property (nonatomic,readonly) NSString * labelString; 
@property (nonatomic,readonly) NSDate * date; 
@property (nonatomic,readonly) NSString * dateLabelAccessabilityString; 
@property (nonatomic,readonly) unsigned playingStatus; 
@property (nonatomic,readonly) char unread; 
@property (nonatomic,retain) VMVoicemail * voicemail;                                                     //@synthesize voicemail=_voicemail - In the implementation block
@property (assign,nonatomic) id<PHVoicemailCellConfigurationDelegate> configurationDelegate;              //@synthesize configurationDelegate=_configurationDelegate - In the implementation block
@property (assign,nonatomic) id<PHVoicemailCellDelegate> delegate;                                        //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char showingPlayController;                                                  //@synthesize showingPlayController=_showingPlayController - In the implementation block
@property (readonly) char unread; 
@property (assign,nonatomic) char didSwipe;                                                               //@synthesize didSwipe=_didSwipe - In the implementation block
@property (readonly) int audioButtonMode; 
@property (nonatomic,retain) NSString * pickedRoute;                                                      //@synthesize pickedRoute=_pickedRoute - In the implementation block
@property (nonatomic,retain) NSString * pickedRouteUID;                                                   //@synthesize pickedRouteUID=_pickedRouteUID - In the implementation block
@property (getter=_nameLabel,retain) UILabel * nameLabel;                                                 //@synthesize nameLabel=_nameLabel - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)disabledPlayImage;
+(id)grayColor;
+(id)pauseImage;
+(id)playImage;
-(void)customAccessoryButtonTapped:(id)arg1 withEvent:(id)arg2 ;
-(void)_handlePhoneAppAddressBookChanged:(id)arg1 ;
-(void)_handleAudioDeviceControllerRoutesChanged:(id)arg1 ;
-(void)_handleContentSizeDidChange:(id)arg1 ;
-(void)_handlePlayerControllerRateOrStatusChange:(id)arg1 ;
-(void)_handlePlayerDidFinishPlaying:(id)arg1 ;
-(void)_mediaserverReset:(id)arg1 ;
-(void)_deregisterForVoicemailNotifications;
-(void)_registerForVoicemailNotifications;
-(void)_updateUnreadIndicatorAnimated:(char)arg1 ;
-(void)_resetPickedRoute;
-(VMVoicemail *)voicemail;
-(void)playPauseButtonTapped:(id)arg1 withEvent:(id)arg2 ;
-(void)speakerButtonTapped:(id)arg1 withEvent:(id)arg2 ;
-(void)_updateSpeakerButton;
-(void)_updateProx;
-(void)callButtonTapped:(id)arg1 withEvent:(id)arg2 ;
-(void)trashButtonTapped:(id)arg1 withEvent:(id)arg2 ;
-(char)_labelIsValid;
-(char)showingPlayController;
-(void)_updatePlaybackTimer;
-(void)_updatePlayPauseButton;
-(void)_loadVoicemailIntoPlayer;
-(void)setShowingPlayController:(char)arg1 animated:(char)arg2 ;
-(void)_addPlayControls;
-(void)_closeVoicemailFromGestureRecognizerTap:(id)arg1 ;
-(void)_removePlayControls;
-(NSString *)pickedRouteUID;
-(void)_updateDurationLabel;
-(void)_enumerateRoutesUsingBlock:(/*^block*/id)arg1 ;
-(void)setPickedRoute:(NSString *)arg1 ;
-(void)setPickedRouteUID:(NSString *)arg1 ;
-(void)_resetPickedRouteIfNecessary;
-(void)_handleVoicemailDataAvailableChanged:(id)arg1 ;
-(int)audioButtonMode;
-(char)_pointIsInsideCloseVoicemailRect:(CGPoint)arg1 ;
-(void)_chooseDefaultRoute;
-(void)setShowingPlayController:(char)arg1 ;
-(CGPoint)anchorPointForUpdateInWindow:(id)arg1 ;
-(void)_recalculateConstraints;
-(char)didSwipe;
-(void)setDidSwipe:(char)arg1 ;
-(NSString *)dateLabelAccessabilityString;
-(unsigned)playingStatus;
-(void)setNameLabel:(UILabel *)arg1 ;
-(NSString *)pickedRoute;
-(void)detailSliderTrackingDidBegin:(id)arg1 ;
-(void)detailSliderTrackingDidEnd:(id)arg1 ;
-(void)detailSliderTrackingDidCancel:(id)arg1 ;
-(void)detailSlider:(id)arg1 didChangeValue:(float)arg2 ;
-(void)_updateFonts;
-(id)_nameLabel;
-(void)setDelegate:(id<PHVoicemailCellDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id<PHVoicemailCellDelegate>)delegate;
-(char)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(NSDate *)date;
-(id)_automationID;
-(void)setEditing:(char)arg1 animated:(char)arg2 ;
-(void)willTransitionToState:(unsigned)arg1 ;
-(void)_updateConstraints;
-(void)setConfigurationDelegate:(id<PHVoicemailCellConfigurationDelegate>)arg1 ;
-(id<PHVoicemailCellConfigurationDelegate>)configurationDelegate;
-(void)export:(id)arg1 ;
-(NSString *)labelString;
-(id)tableViewSeparatorColor;
-(NSString *)nameString;
-(void)_updateUI;
-(char)unread;
-(void)startPlaying;
-(void)_handleVoicemailFlagsChanged:(id)arg1 ;
-(void)setVoicemail:(VMVoicemail *)arg1 ;
@end

